### PR TITLE
test-configs: update to buildroot 2020.05

### PR DESCRIPTION
**Pull request by khilman**
Signed-off-by: Kevin Hilman <khilman@baylibre.com>

### CODE REVIEW

**Comment by gctucker** [comment]
@khilman Looks like some patches from the current `latest` branch are missing in the new `2020.05` rebase:
https://github.com/kernelci/buildroot/commits/kernelci/latest
https://github.com/kernelci/buildroot/commits/kernelci/2020.05

**Comment by khilman** [comment]
> @khilman Looks like some patches from the current `latest` branch are missing in the new `2020.05` rebase:

Oops, good catch.  local branch was not up to date when rebasing.  Will respin.

**Comment by khilman** [comment]
OK, re-did the rebase and kicked off a jenkins build: https://ci.kernelci.org/job/buildroot/57/

**Comment by khilman** [comment]
Full build was successful, dropping the staging-skip label so these new image can be tested in staging.

**Comment by gctucker** [comment]
Thanks, this is being tested on staging now.

**Pull request merged**
