### PR TITLE
For merging x86 chromebook configs

### PR DESCRIPTION
**Pull request by penvirus**
The series merges Kconfigs for x86-chromebook fragment.

They are not newly added.  Instead, they used to be included in the for-kernelci branch in chrome-platform repository.  See the [patch](https://git.kernel.org/pub/scm/linux/kernel/git/chrome-platform/linux.git/commit/?h=for-kernelci&id=75a273974d7ac814b655eda546c62064a4b41d34).  (The link would be invalid after the repo get rebased, e.g. rebased when v6.3-rc1 is available.)

### CODE REVIEW

**Review by nuclearcat — CHANGES_REQUESTED** [review]
Probably this is supposed to change config/core/build-configs.yaml ?

**Comment by gctucker** [comment]
@penvirus Sorry I gave you a link to the wrong file, the actual config fragment used for builds is here:
https://github.com/kernelci/kernelci-core/blob/main/config/core/build-configs.yaml#L157

in `build-configs.yaml`.  The one in `fragments.yaml` was copied from it so it should have the same list of configs but it's only used for unit tests.  The configs listed there don't have any effect on the builds and it doesn't need to be synced with the real one.

**Comment by penvirus** [comment]
I have updated the commits to change `build-configs.yaml` instead of `fragments.yaml`.

**Comment by gctucker** [comment]
Also thanks for tidying things up and sorting the configs.

This updated fragment will be picked up on the next builds on https://staging.kernelci.org at 16:00 UTC, there's one every 8h.  That way we'll be able to confirm it's producing the correct kernel config.

**Review by nuclearcat — APPROVED** [review]
New builds appeared on staging, no regressions spotted. LGTM
https://storage.staging.kernelci.org/kernelci/staging-next/staging-next-20230305.0/x86_64/x86_64_defconfig+x86-chromebook/clang-17/config/kernel.config

**Comment by gctucker** [comment]
> New builds appeared on staging, no regressions spotted. LGTM https://storage.staging.kernelci.org/kernelci/staging-next/staging-next-20230305.0/x86_64/x86_64_defconfig+x86-chromebook/clang-17/config/kernel.config

Have you checked the resulting config is the same?

**Comment by nuclearcat** [comment]
I checked several new options did appeared, comparing with old ones.

**Comment by gctucker** [comment]
Oh I see the patch is gone now in the chrome-platform repository. Alright digging into this to get an actual diff for the record.

**Comment by gctucker** [comment]
OK so I've run:
```
./kci_build generate_fragments --build-config=chrome-platform
./kci_build init_bmeta --arch=x86_64 --build-env=gcc-10 --build-config=chrome-platform
./kci_build make_config --defconfig=x86_64_defconfig+x86-chromebook
# then in the kernel directory
make savedefconfig
```
and then copied the generated defconfig.  I did this first with the new fragment from this PR with `v6.3-rc1` which is the current new tip of the `chrome-platform/for-kernelci` branch, and then with the `KERNELCI: x86_64_defconfig: Enable support for Chromebooks devices`, but reverting back to `v6.3-rc1` before `make savedefconfig` to get the upstream `x86_64_defconfig` as a base.  The defconfig files are identical:
```
$ diff -u defconfig-chrome-platform-old defconfig-chrome-platform-new
# nothing here ;)
```

Attaching the resulting `defconfig-chrome-platform-new` as well as the generated fragments before and after this change.  The fragments look very different but the generated config is exactly the same.

[chrome-platform-configs.tar.gz](https://github.com/kernelci/kernelci-core/files/10895860/chrome-platform-configs.tar.gz)

**Comment by nuclearcat** [comment]
wget https://storage.staging.kernelci.org/kernelci/staging-next/staging-next-20230302.0/x86_64/x86_64_defconfig+x86-chromebook/clang-17/config/kernel.config -O staging-next-20230302.config
wget https://storage.staging.kernelci.org/kernelci/staging-next/staging-next-20230305.0/x86_64/x86_64_defconfig+x86-chromebook/clang-17/config/kernel.config -O staging-next-20230305.config
```
diff -Naur staging-next-20230302.config staging-next-20230305.config|grep "^+CONFIG"
+CONFIG_X86_INTEL_LPSS=y
+CONFIG_REGMAP_I2C=m
+CONFIG_REGMAP_SPI=m
+CONFIG_GOOGLE_FIRMWARE=y
+CONFIG_GOOGLE_SMI=m
+CONFIG_GOOGLE_COREBOOT_TABLE=m
+CONFIG_GOOGLE_MEMCONSOLE=m
+CONFIG_GOOGLE_MEMCONSOLE_X86_LEGACY=m
+CONFIG_GOOGLE_MEMCONSOLE_COREBOOT=m
+CONFIG_GOOGLE_VPD=m
+CONFIG_INPUT_MATRIXKMAP=m
+CONFIG_KEYBOARD_CROS_EC=m
+CONFIG_TOUCHSCREEN_ATMEL_MXT=m
+CONFIG_I2C_MUX=y
+CONFIG_I2C_CCGX_UCSI=y
+CONFIG_I2C_DESIGNWARE_BAYTRAIL=y
+CONFIG_I2C_DESIGNWARE_PCI=y
+CONFIG_I2C_CROS_EC_TUNNEL=m
+CONFIG_PINCTRL_SX150X=y
+CONFIG_PINCTRL_BAYTRAIL=y
+CONFIG_PINCTRL_INTEL=y
+CONFIG_CHARGER_CROS_USBPD=m
+CONFIG_CHARGER_WILCO=m
+CONFIG_MFD_INTEL_LPSS_ACPI=m
+CONFIG_MEDIA_SUPPORT=y
+CONFIG_MEDIA_SUPPORT_FILTER=y
+CONFIG_MEDIA_SUBDRV_AUTOSELECT=y
+CONFIG_MEDIA_CAMERA_SUPPORT=y
+CONFIG_VIDEO_DEV=y
+CONFIG_MEDIA_CONTROLLER=y
+CONFIG_VIDEO_V4L2_I2C=y
+CONFIG_MEDIA_USB_SUPPORT=y
+CONFIG_USB_VIDEO_CLASS=m
+CONFIG_USB_VIDEO_CLASS_INPUT_EVDEV=y
+CONFIG_UVC_COMMON=m
+CONFIG_VIDEOBUF2_CORE=m
+CONFIG_VIDEOBUF2_V4L2=m
+CONFIG_VIDEOBUF2_MEMOPS=m
+CONFIG_VIDEOBUF2_VMALLOC=m
+CONFIG_MEDIA_HIDE_ANCILLARY_SUBDRV=y
+CONFIG_SND_DMAENGINE_PCM=m
+CONFIG_SND_COMPRESS_OFFLOAD=m
+CONFIG_SND_DYNAMIC_MINORS=y
+CONFIG_SND_MAX_CARDS=32
+CONFIG_SND_HDA_CODEC_HDMI=m
+CONFIG_SND_HDA_GENERIC=m
+CONFIG_SND_SOC=m
+CONFIG_SND_SOC_GENERIC_DMAENGINE_PCM=y
+CONFIG_SND_SOC_COMPRESS=y
+CONFIG_SND_SOC_ACPI=m
+CONFIG_SND_DESIGNWARE_I2S=m
+CONFIG_SND_DESIGNWARE_PCM=y
+CONFIG_SND_SOC_INTEL_SST_TOPLEVEL=y
+CONFIG_SND_SST_ATOM_HIFI2_PLATFORM=m
+CONFIG_SND_SST_ATOM_HIFI2_PLATFORM_ACPI=m
+CONFIG_SND_SOC_ACPI_INTEL_MATCH=m
+CONFIG_SND_SOC_INTEL_MACH=y
+CONFIG_SND_SOC_I2C_AND_SPI=m
+CONFIG_SND_SOC_CROS_EC_CODEC=m
+CONFIG_SND_SIMPLE_CARD_UTILS=m
+CONFIG_SND_SIMPLE_CARD=m
+CONFIG_I2C_HID=m
+CONFIG_INTEL_ISH_HID=m
+CONFIG_RTC_DRV_CROS_EC=m
+CONFIG_RTC_DRV_WILCO_EC=m
+CONFIG_DW_DMAC_PCI=y
+CONFIG_CHROMEOS_PSTORE=m
+CONFIG_CROS_EC_ISHTP=m
+CONFIG_CROS_EC_SPI=m
+CONFIG_CROS_KBD_LED_BACKLIGHT=m
+CONFIG_CROS_USBPD_LOGGER=m
+CONFIG_WILCO_EC=m
+CONFIG_WILCO_EC_DEBUGFS=m
+CONFIG_WILCO_EC_EVENTS=m
+CONFIG_WILCO_EC_TELEMETRY=m
+CONFIG_IIO_CROS_EC_ACCEL_LEGACY=m
+CONFIG_IIO_CROS_EC_SENSORS_LID_ANGLE=m
+CONFIG_IIO_CROS_EC_LIGHT_PROX=m
+CONFIG_IIO_CROS_EC_BARO=m
```

**Comment by gctucker** [comment]
OK thanks.  What I wanted to double check was that the resulting kernel config was actually the same as with the patch on the `chrome-platform/for-kernelci` branch since that was the purpose of this PR.  I guess it's also useful to know that the changes in the fragment don't break anything on the other branches too e.g. `linux-next/master`.

**Pull request merged**
