### PR TITLE
test-configs: new Amlogic board: meson-g12a-u200

### PR DESCRIPTION
**Pull request by khilman**
Signed-off-by: Kevin Hilman <khilman@baylibre.com>

### CODE REVIEW

**Comment by khilman** [comment]
device-type submitted to upstream LAVA: https://git.lavasoftware.org/lava/lava/merge_requests/687

**Comment by gctucker** [comment]
There seems to be an small issue with merging this in LAVA, so putting this on hold until it's resolved.

**Comment by gctucker** [comment]
OK the LAVA merge request is green now, will get this tested on staging today.

**Comment by gctucker** [comment]
Tested OK on staging: https://staging.kernelci.org/boot/id/5d67d2eacf3a0f968949daff/

**Pull request merged**
