### PR TITLE
config: docker: net kselftest suite required openssl library

### PR DESCRIPTION
**Pull request by musamaanjum**
This library is missing and hence build errors are encountered while building kselftests specifically net suite. Hence add this library.

### CODE REVIEW

**Comment by musamaanjum** [comment]
I've verified locally this PR generates the intended docker image with libssl-dev library. I'm not sure how long and when should I verify if docker images have been updated.

@nuclearcat, how often are the docker containers generated from the updated recipe files? Is there an automatic or manual workflow?

**Comment by nuclearcat** [comment]
Compiler images usually re-generated on each staging run

**Comment by musamaanjum** [comment]
Confirmed on staging, the openssl error has been resolved:
https://staging.kernelci.org:9000/viewer?node_id=66b8af166c8dd1431f975180
https://staging.kernelci.org:9000/viewer?node_id=66b8af156c8dd1431f97517f

**Comment by musamaanjum** [comment]
@nuclearcat please merge

**Review by pawiecz — APPROVED** [review]
LGTM

(only marking PR as a merge-ready because I don't have permissions to merge in this repo)

**Comment by musamaanjum** [comment]
@nuclearcat Please review and/or merge the PR

**Comment by nuclearcat** [comment]
Excellent, thank you @musamaanjum for fixing these long standing problems!

**Pull request merged**
