### PR TITLE
build-configs-chromeos.yaml: Remove ChromiumOS build configs from main

### PR DESCRIPTION
**Pull request by nuclearcat**
We dont need ChromiumOS config fragments in main branch, otherwise they are causing unnecessary builds and complexities in filters.

### CODE REVIEW

**Review by gctucker — APPROVED** [review]
Small thing, "config fragment" is usually understood as a kernel config fragment.  Here I think you're referring to the whole KernelCI YAML build configuration relating to ChromeOS.    Maybe just saying that the YAML file is being removed would avoid this ambiguity.

**Comment by nuclearcat** [comment]
Adjusted commit message

**Comment by gctucker** [comment]
OK I'll check again and merge this tomorrow morning once the prod update is done and this has been tested on staging.

**Comment by gctucker** [comment]
Tested OK on staging and with `kci_build list_kernel_configs` to check there's no visible side-effects outside ChromeOS build configs.

**Comment by gctucker** [comment]
https://staging.kernelci.org/build/kernelci/branch/staging-mainline/kernel/staging-mainline-20230727.0/

**Pull request merged**
