### PR TITLE
test-configs.yaml: add Kontron pitx-imx8m board

### PR DESCRIPTION
**Pull request by hthiery**
Signed-off-by: Heiko Thiery <heiko.thiery@gmail.com>

### CODE REVIEW

**Comment by mgalka** [comment]
There is a MR  https://git.lavasoftware.org/lava/lava/-/merge_requests/1468 that needs to be merged before this PR gets merged

**Comment by gctucker** [comment]
Are there any baseline results on staging for this platform?

**Comment by hthiery** [comment]
@gctucker there are no results yet. there were some jobs pushed but they were not valid because of a bug in the kernelci scripts. see: https://lavalab.kontron.com/scheduler/job/14776#bottom

**Comment by gctucker** [comment]
OK thanks, there should be more jobs running today so we'll take a look again.

**Comment by hthiery** [comment]
Now the first baseline results on staging for this platform are available:

https://lavalab.kontron.com/scheduler/device/kontron-pitx-imx8m-01

**Comment by gctucker** [comment]
The LAVA merge request has been closed because the "source project has been removed"
https://git.lavasoftware.org/lava/lava/-/merge_requests/1468

**Comment by gctucker** [comment]
Ah here's the new one: https://git.lavasoftware.org/lava/lava/-/merge_requests/1482

Still failing the Gitlab CI pipeline though.

**Comment by gctucker** [comment]
As mentioned on IRC, please change the incoming branch or create a new MR on the LAVA Gitlab so it can be merged.  Then this PR should be merged.

**Comment by hthiery** [comment]
Hi, meanwhile the MR in LAVA's gitlab is merged. 

https://git.lavasoftware.org/lava/lava/-/commit/75d3c7fa0e79b9f2579802509070db23ba6851e3

**Comment by gctucker** [comment]
Ah yes I see the MR here: https://git.lavasoftware.org/lava/lava/-/merge_requests/1483

**Comment by gctucker** [comment]
Tested OK on staging again: https://staging.kernelci.org/test/plan/id/607f052d8a32999de0c7d199/

**Pull request merged**
