### PR TITLE
T25311 consolidate kci_build

### PR DESCRIPTION
**Pull request by gctucker**
Consolidate the `kernelci.build.Step` class initialisation and how it's used in `kci_build`.

### CODE REVIEW

**Comment by gctucker** [comment]
Tested OK with no regressions on staging.

**Review by mgalka — APPROVED** [review]
The new kci_build architecture seems a good step forward to me. Nicely done.

**Review by alexandrasp — APPROVED** [review]
lgtm

**Comment by gctucker** [comment]
Thanks for the reviews!

**Pull request merged**
