### PR TITLE
test-configs: Add ox820-cloudengines-pogoplug-series-3

### PR DESCRIPTION
**Pull request by montjoie**
The ox820-cloudengines-pogoplug-series-3 is on our lab since a long time
and is waiting for jobs!

- [x] `ox820-cloudengines-pogoplug-series-3` merged upstream in LAVA https://git.lavasoftware.org/lava/lava/merge_requests/574

### CODE REVIEW

**Comment by gctucker** [comment]
@montjoie The `ox820-cloudengines-pogoplug-series-3` device type doesn't seem to have been upstreamed in LAVA, can you please confirm the status in this respect?

**Comment by montjoie** [comment]
Sorry, this board is setupped since a long time and I forgot it is not in LAVA yet.
i have sent the PR for it
https://git.lavasoftware.org/montjoie/lava/merge_requests/new?merge_request%5Bsource_branch%5D=oxnas

**Comment by gctucker** [comment]
OK I've added an item on a checklist on this PR to wait for it to land upstream before merging this PR.

**Comment by montjoie** [comment]
The Pr was merged in LAVA upstream

**Comment by gctucker** [comment]
Thanks, I'll put a comment with today's results from staging to confirm this is working as expected.

**Comment by gctucker** [comment]
@montjoie I could not find the boot results for this board in the last staging run.  Is it online and well in lab-baylibre?

**Comment by montjoie** [comment]
No boot in our lab, but the device is up and running.

**Comment by gctucker** [comment]
@montjoie The Jenkins job said:
```
dtb not in builds: ox820-cloudengines-pogoplug-series-3.dtb
```

Turns out this is only enabled for `ARCH_OXNAS`:
```
$ grep ox820-cloudengines-pogoplug-series-3.dtb arch/arm/boot/dts/Makefile -B2
dtb-$(CONFIG_ARCH_OXNAS) += \
	ox810se-wd-mbwe.dtb \
	ox820-cloudengines-pogoplug-series-3.dtb
```

which is only enabled in `oxnas_v6_defconfig`:
```
$ grep -r CONFIG_ARCH_OXNAS arch/arm/configs
arch/arm/configs/oxnas_v6_defconfig:CONFIG_ARCH_OXNAS=y
```

which is not build at all in kernelci.org at the moment.

@khilman Should we start building `oxnas_v6_defconfig` to cover this platform?

**Comment by montjoie** [comment]
You are aleady building it https://storage.kernelci.org/mainline/master/v5.2-rc4-9-g01ccc3ad4413/arm/oxnas_v6_defconfig/gcc-8/build.json

**Comment by gctucker** [comment]
Ah yes, sorry.  So I'll add it on staging temporarily to test this PR.

**Comment by gctucker** [comment]
Tested OK on staging today:
https://staging.kernelci.org/boot/id/5d025407cf3a0f85de40974a/

**Pull request merged**
