### PR TITLE
build-configs.yaml: Add for-next branch from matthiasbgg tree

### PR DESCRIPTION
**Pull request by mgalka**
Add builds for mathiasbgg/for-next with minimal set of variants.

Resolves: https://github.com/kernelci/kernelci-core/issues/1465

Signed-off-by: Michal Galka <michal.galka@collabora.com>

### CODE REVIEW

**Comment by mgalka** [comment]
Build OK on staging https://staging.kernelci.org/test/job/matthiasbgg/branch/for-next/kernel/v6.0-next-dts64-19-gcbb1618792e2/

**Review by nuclearcat — APPROVED** [review]
LGTM

**Review by aliceinwire — APPROVED** [review]

**Review by aliceinwire — APPROVED** [review]

**Comment by mgalka** [comment]
Staging rest results:
https://staging.kernelci.org/test/job/matthiasbgg/branch/for-next/kernel/v6.1-rc1-10-g25cc9975caad/plan/baseline/

**Comment by kholk** [comment]
Test results OK. Thanks!

**Pull request merged**
