### PR TITLE
Revert "Allow filters of the same type to be combined"

### PR DESCRIPTION
**Pull request by khilman**
This reverts commit e4e70f0bce4954471ebf3bde7ea9444a1c8cc1e3.

I don't fully understand what's going on here, but this patch has some unintended consequences when using `kci_test generate`.

For example, if a single device-type in test-configs has a lab in the blocklist (e.g. beaglebone-black has this):

    filters:
      - blocklist: *device_config_filter
      - blocklist: {lab: ['lab-baylibre']}

then this somehow has the affect of applying that blocklist to *every* device-type, meaning NO jobs are generated for lab-baylibre for *any* device-type.

If you comment out *either* blocklist line from this beaglebone-black filter, then jobs are generated for lab-baylibre.  ?!?!

Signed-off-by: Kevin Hilman <khilman@baylibre.com>

### CODE REVIEW

**Comment by khilman** [comment]
@mgalka this should be reverted ASAP since it's having the side-effect of having no jobs generated for lab-baylibre.

@eds-collabora could you have a closer look and see why blocklists are being combined for unrelated device-types.

**Comment by eds-collabora** [comment]
@khilman I had a look into this. Essentially what happens is that when we create combined filters, the item dictionaries they contain still share their internal arrays with the default filters. I did not expect that interaction when I wrote the code. There's a candidate fix as #1638, which does not smear the blocklists across random other devices. It might be worth checking whether this solves the problem you saw.

**Comment by khilman** [comment]
Added `staging-skip` so the fix from @eds-collabora can get tested without the revert.

**Comment by khilman** [comment]
Closing this revert since the fix from Ed resolves the issue I was having. 

As to whether we need this feature at all, I admit to being confused by the feature, but TBH I don't fully understand it's utility, so that should probably be brought up in a separate issue.

**Pull request closed without merging**
