### PR TITLE
test-configs: Add ltp-syscalls

### PR DESCRIPTION
**Pull request by aliceinwire**
Enabling LTP syscalls test
Signed-off-by: Alice Ferrazzi <alice.ferrazzi@miraclelinux.com>

### CODE REVIEW

**Review by gctucker — COMMENTED** [review]
A number of jobs have been run but it looks like they all timed out:
https://staging.kernelci.org/test/plan/id/625d2a7121b7239ac205f4da/

Taking a look to see if it's because the kernel hanged or if it's really because the syscalls tests are taking more than 10min to complete.

**Comment by gctucker** [comment]
So I've re-run the job with a much longer timeout and it completed on the arm64 `hana` Chromebook in 1h41min:
https://staging.lava.collabora.dev/scheduler/job/133369

Running jobs that take that long is potentially an issue as it can impact availability of some devices for other projects that require high responsiveness such as Mesa CI.  So I think we could enable it only for linux-next as we know there isn't more than one new revision per 24h and we can tell how many jobs would be run.  As long as the number of jobs doesn't exceed 50% of the available devices in the labs then this should be OK as an experiment.

We do need to change templates to accommodate for longer timeouts, and adjust filters in YAML to only run this test to limit it to linux-next.  I'm adding the `staging-skip` label for now to avoid scheduling jobs that will always timeout until this has been addressed.

**Comment by nuclearcat** [comment]
Any update on this?

**Comment by gctucker** [comment]
@aliceinwire I can see 2 options here:

1. close this now and reopen when we have some more dynamic scheduling logic to only run long tests when devices are available in labs
2. only run `ltp-syscalls` on a small number of platforms that are fast and can cope with the load easily (e.g. some x86 Chromebooks or arm64 servers)

**Comment by gctucker** [comment]
No updates so closing this now.

**Comment by gctucker** [comment]
@broonie Why did you reopen this?

**Comment by broonie** [comment]
I moved the suite to a different, probably faster, board. It might also be a good fit for the QDF2400 but there's the whole thing with the filter on that not doing the right thing for no reason I've been able to discern.

**Comment by gctucker** [comment]
This PR doesn't apply, has had the skip label for a long time and there hasn't been any update for almost a year.  If you want to pick some changes from it to use with your own PR to enable `ltp-syscalls` then please do that.  But this particular PR should be closed as there's no sign it's going to get fixed and merged any time soon.

**Comment by broonie** [comment]
Sorry, got this confused with a very similar PR of mine that you closed.

**Pull request closed without merging**
