### PR TITLE
`kci`: Handle exception while reading YAML configs

### PR DESCRIPTION
**Pull request by JenySadadia**
Fixes https://github.com/kernelci/kernelci-core/issues/2260

Extend the decorator to catch `KerError` exception and raise `ClickException` from it. This is to handle errors while reading YAML configurations in different `kci` tools.

### CODE REVIEW

**Comment by nuclearcat** [comment]
This PR likely causes crash on staging:
```
Traceback (most recent call last):
  File "/data/kernelci-deploy-checkout/kernelci-core/./kci", line 18, in <module>
    from kernelci.cli import (  # pylint: disable=unused-import
  File "/data/kernelci-deploy-checkout/kernelci-core/kernelci/cli/event.py", line 121, in <module>
    @catch_http_error
NameError: name 'catch_http_error' is not defined
```
Set skip-staging label, as soon as it is fixed, please feel free to remove it and retest on staging.

**Comment by JenySadadia** [comment]
Where are you running the command? @nuclearcat 

On staging, it works:
```
kernelci@kernelci-staging:~/kernelci-deploy/checkout/kernelci-core$ ./kci node
usage: node [-h] [--yaml-config YAML_CONFIG] [--extra-config EXTRA_CONFIG] [--settings SETTINGS]
            {get,find,count,submit} ...

optional arguments:
  -h, --help            show this help message and exit
  --yaml-config YAML_CONFIG
                        Path to the Kernel CI directory with YAML config files
  --extra-config EXTRA_CONFIG
                        Path to additional YAML site config files
  --settings SETTINGS   Path to the settings file

Commands:
  {get,find,count,submit}
                        List of available commands
    get                 Get a node with a given ID
    find                Find nodes with arbitrary attributes
    count               Count nodes with arbitrary attributes
    submit              Submit a new node or update an existing one from stdin

```

**Comment by nuclearcat** [comment]
> Where are you running the command? @nuclearcat
> 
> On staging, it works:
> 
> ```
> kernelci@kernelci-staging:~/kernelci-deploy/checkout/kernelci-core$ ./kci node
> usage: node [-h] [--yaml-config YAML_CONFIG] [--extra-config EXTRA_CONFIG] [--settings SETTINGS]
>             {get,find,count,submit} ...
> 
> optional arguments:
>   -h, --help            show this help message and exit
>   --yaml-config YAML_CONFIG
>                         Path to the Kernel CI directory with YAML config files
>   --extra-config EXTRA_CONFIG
>                         Path to additional YAML site config files
>   --settings SETTINGS   Path to the settings file
> 
> Commands:
>   {get,find,count,submit}
>                         List of available commands
>     get                 Get a node with a given ID
>     find                Find nodes with arbitrary attributes
>     count               Count nodes with arbitrary attributes
>     submit              Submit a new node or update an existing one from stdin
> ```
This was crash/stacktrace of deploy script, i think during kci docker commands.

**Comment by nuclearcat** [comment]
```
Dec 24 16:02:48 kernelci-staging staging.kernelci.org[10103]: Pushing tag (staging-mainline-20231224.0) and branch (staging-mainline)
Dec 24 16:02:48 kernelci-staging staging.kernelci.org[10103]: Deleting 1 tags: staging-mainline-20231206.0
Dec 24 16:02:48 kernelci-staging staging.kernelci.org[10103]: Deleting staging-mainline-20231206.0
Dec 24 16:02:48 kernelci-staging staging.kernelci.org[6380]: Updating Docker images
Dec 24 16:02:51 kernelci-staging staging.kernelci.org[10296]: Traceback (most recent call last):
Dec 24 16:02:51 kernelci-staging staging.kernelci.org[10296]:   File "/data/kernelci-deploy-checkout/kernelci-core/./kci", line 18, in <module>
Dec 24 16:02:51 kernelci-staging staging.kernelci.org[10296]:     from kernelci.cli import (  # pylint: disable=unused-import
Dec 24 16:02:51 kernelci-staging staging.kernelci.org[10296]:   File "/data/kernelci-deploy-checkout/kernelci-core/kernelci/cli/event.py", line 121, in <module>
Dec 24 16:02:51 kernelci-staging staging.kernelci.org[10296]:     @catch_http_error
Dec 24 16:02:51 kernelci-staging staging.kernelci.org[10296]: NameError: name 'catch_http_error' is not defined
Dec 24 16:02:51 kernelci-staging kernelci-deploy[10297]: Error in script /home/kernelci/kernelci-deploy/staging.kernelci.org
```
This is more complete log

**Comment by JenySadadia** [comment]
Okay. Thanks. Which command are you running exactly?
Is it `./staging.kernelci.org docker`?
I think we need to run `./pending.py kernelci-core` first to get the latest pull.

**Comment by nuclearcat** [comment]
This script run automatically by schedule, without any arguments (means cmd_all), it includes pull first.

**Comment by JenySadadia** [comment]
Fixed the issue. Tested OK staging script:
```
$ ./staging.kernelci.org docker
Updating Docker images
Checking connectivity: 43919, done.
Building kernelci/staging-kernelci
Pushing kernelci/staging-kernelci to Docker Hub

```

**Comment by nuclearcat** [comment]
@JenySadadia , can you rebase please and retest, and if all ok, i think we can merge

**Comment by JenySadadia** [comment]
> @JenySadadia , can you rebase please and retest, and if all ok, i think we can merge

Done.

**Comment by nuclearcat** [comment]
Thanks!

**Pull request merged**
