### PR TITLE
Add API.Node abstract class

### PR DESCRIPTION
**Pull request by gctucker**
Move the Node API bindings to a nested abstract class API.Node and update all the related implementation accordingly.

### CODE REVIEW

**Comment by gctucker** [comment]
Should we increase the minimum Python version?  3.7 is end of life already now:
https://devguide.python.org/versions/

I'll fix the code to make it work anyway but I think 3.8 or 3.9 should be considered as a new minimum.

**Comment by gctucker** [comment]
Also 3.11 should be tested as the latest supported version.  It's the default one in Debian Bookworm (stable) now too.

**Comment by gctucker** [comment]
Alright I've made #2252 to bump the Python versions.  Still this PR now passes the tests with 3.7 so it doesn't depend on it.

**Review by JenySadadia — APPROVED** [review]
Tested OK locally.

**Comment by gctucker** [comment]
OK thanks.

In the meantime, @nuclearcat reported a problem on staging, I believe that's because the pipeline services need to be updated to match the changes in the API bindings.  I'll prepare a PR for that and for the user-related ones too if applicable.

Please let me know if any other side-effects are found following these changes.

**Comment by nuclearcat** [comment]
```
    def create_job_node(self, job_config, input_node):
        """Create a new job node based on input and configuration"""
        job_node = {
            'parent': input_node['id'],
            'name': job_config.name,
            'path': input_node['path'] + [job_config.name],
            'group': job_config.name,
            'artifacts': input_node['artifacts'],
            'revision': input_node['revision'],
        }
        return self._api.create_node(job_node)
```
This code crash on staging:
```
today at 3:46:33 PM12/20/2023 01:46:33 PM UTC [ERROR] Traceback (most recent call last):
today at 3:46:33 PM  File "/home/kernelci/pipeline/base.py", line 69, in run
today at 3:46:33 PM    status = self._run(context)
today at 3:46:33 PM  File "/home/kernelci/./pipeline/scheduler.py", line 113, in _run
today at 3:46:33 PM    self._run_job(job, runtime, platform, input_node)
today at 3:46:33 PM  File "/home/kernelci/./pipeline/scheduler.py", line 75, in _run_job
today at 3:46:33 PM    node = self._api_helper.create_job_node(job_config, input_node)
today at 3:46:33 PM  File "/usr/local/lib/python3.9/dist-packages/kernelci-1.1-py3.9.egg/kernelci/api/helper.py", line 114, in create_job_node
today at 3:46:33 PM    return self._api.create_node(job_node)
today at 3:46:33 PMAttributeError: 'LatestAPI' object has no attribute 'create_node'
```
@gctucker

**Comment by gctucker** [comment]
I think that's already fixed in #2257.  It seems like you're trying to run staging too often, I don't even have the time to send changes in between ;)

**Comment by nuclearcat** [comment]
Yes, i promised to look into one of the PRs and review it, and also I need to check if my own PRs are working or not (some issues are not reproducible on my local setup), and now i am stuck cause broken PR got merged and i cannot even set staging-skip.

**Comment by gctucker** [comment]
Well that's how development happens, when something's broken it gets fixed.  So, is it fixed now with #2257?

**Comment by nuclearcat** [comment]
Staging machine load too high now, i cannot run another staging cycle yet

**Comment by gctucker** [comment]
Alright I'll check again tomorrow.

**Pull request merged**
