### PR TITLE
test-configs: add orangepi 3 board

### PR DESCRIPTION
**Pull request by montjoie**
This patch adds support for the orangepi 3 board.

### CODE REVIEW

**Comment by gctucker** [comment]
@montjoie This device type is not in upstream LAVA yet, is it?

**Comment by montjoie** [comment]
Not yet, I forgot to do it. I sent the PR for it: https://git.lavasoftware.org/lava/lava/merge_requests/836

**Comment by gctucker** [comment]
OK, let's wait for that to get merged then.

Meanwhile it seems to be working fine from this taging job:
https://staging.kernelci.org/boot/id/5dd70cf5cf3a0f38799940bb/

**Comment by montjoie** [comment]
LAVA devicetype merged upstream

**Comment by gctucker** [comment]
Tested OK on staging: https://staging.kernelci.org/boot/id/5ddd3cf7fc713b0f5ded498c/

**Pull request merged**
