### PR TITLE
T17420 kci rootfs fixup

### PR DESCRIPTION
**Pull request by gctucker**
Depends on #328 to be merged first.

### CODE REVIEW

**Comment by Lakshmipathi** [comment]
LGTM

**Comment by gctucker** [comment]
Tested OK on staging:
https://bot.staging.kernelci.org/job/rootfs-build-trigger/10/
https://storage.staging.kernelci.org/images/rootfs/debian/buster/20200413.1/
Now enabling these binaries on staging for the next round of tests to check they are still OK.

**Comment by gctucker** [comment]
The rootfs image sizes appear to be identical to the ones currently used in production:
https://storage.kernelci.org/images/rootfs/debian/buster/20200325.0

**Comment by gctucker** [comment]
Tested OK, here's a sample LAVA job scheduled from staging:
https://lava.collabora.co.uk/scheduler/job/2339707

Removing the temporary patch with staging rootfs URLs now.

**Pull request merged**
