### PR TITLE
test-configs.yaml: Add CIP device r8a7743-iwg20d-q7

### PR DESCRIPTION
**Pull request by aliceinwire**
Signed-off-by: Alice Ferrazzi <alice.ferrazzi@miraclelinux.com>

### CODE REVIEW

**Comment by gctucker** [comment]
The kernel started but then It failed to boot with the ramdisk:
https://lava.ciplatform.org/scheduler/job/612889

Looking at the health check, there may be something needed with a U-Boot header:
https://lava.ciplatform.org/scheduler/job/612649/definition#defline45
```yaml
    ramdisk:
      url: https://s3-us-west-2.amazonaws.com/download.cip-project.org/ciptesting/cip-lava/rfs/generic-initramfs.cpio.gz
      compression: gz
      # the bootloader needs a u-boot header on the modified ramdisk
      add-header: u-boot
```

**Comment by gctucker** [comment]
I've resubmitted a job by hand with the extra property added, but the dispatcher just went offline:
https://lava.ciplatform.org/scheduler/job/612902

Will check the results later when things are back online.

**Comment by gctucker** [comment]
It failed to boot, looks like the kernel is crashing early on or the serial console is not enabled.  There's nothing after `Starting kernel ...` from U-Boot.

**Comment by gctucker** [comment]
@patersonc @aliceinwire Hello, how about keeping this PR open and try to get the platform working but close the other ones for now?

Then when it's fixed you can re-open other PRs when other platforms become operational. The issue is we have too many stalled open PRs, it makes it harder to keep track of which ones are still live and have a path to being resolved.

**Comment by nuclearcat** [comment]
I'm adding staging-skip until we have updates, as it is blocking other patches in staging

**Comment by patersonc** [comment]
Hi @gctucker 

Is it possible to re-submit the kernelci build / lava test jobs for this MR?
The previous LAVA test jobs are no longer available.

Thanks, Chris

**Comment by gctucker** [comment]
OK I'll take a look.

**Comment by gctucker** [comment]
Started a staging-cip build job, let's see what results we get:
https://bot.staging.kernelci.org/job/kernel-build-trigger/2216/console

**Comment by gctucker** [comment]
The device appears to be online in the lab and passing health checks:
https://lava.ciplatform.org/scheduler/device_type/r8a7743-iwg20d-q7

However there's no results on staging yet:
https://staging.kernelci.org/test/job/kernelci/branch/staging-cip/kernel/staging-cip-20220624.0/plan/baseline/

Investigating why that is.

**Comment by gctucker** [comment]
Ha, the `staging-skip` label was still there. Trying again by hand now with the build meta-data.

**Comment by gctucker** [comment]
@patersonc It doesn't seem to be booting:
https://lava.ciplatform.org/scheduler/job/701463

This is a 5.10 kernel, do you know if it's supposed to work or should we try with mainline or linux-next?

**Comment by gctucker** [comment]
It looks like some other jobs are working with a 5.10 kernel:
https://lava.ciplatform.org/scheduler/job/701281

Probably some config options are missing in `multi_v7_defconfig`. Could you please confirm which defconfig is required for this board, and if any config options are not enabled in any defconfig upstream?

**Comment by nuclearcat** [comment]
It looks like working with https://staging.kernelci.org/test/plan/id/631447045beeb2b703985638/ which is [shmobile_defconfig]
But not [multi_v7_defconfig] https://staging.kernelci.org/test/plan/id/631434bb297cc3d489985661/
Probably better to set filter to shmobile_defconfig only?

**Comment by aliceinwire** [comment]
I will try adding `shmobile_defconfig`

**Comment by aliceinwire** [comment]
updated the pull request with the changes suggested by @nuclearcat

**Pull request merged**
