### PR TITLE
Add support for building Chromium OS images

### PR DESCRIPTION
**Pull request by gctucker**
Add support for building Chromium OS images starting with octopus and the generic amd64 one for QEMU.

### CODE REVIEW

**Review by nuclearcat — COMMENTED** [review]
AFAIK  docker image name kernelci/chromiumos changed to kernelci/cros-sdk

**Comment by gctucker** [comment]
> AFAIK docker image name kernelci/chromiumos changed to kernelci/cros-sdk

There is a patch for that already in `kernelci-jenkins`, I don't see anything in this PR about the Docker image name.

**Comment by nuclearcat** [comment]
It is in commit message, probably it needs to be updated or it should be left as it is?
```
To build amd64-generic image (can run in qemu) we need:

  docker run \
    -itd \
    -v $(pwd):/kernelci-core \
    --device /dev/kvm \
    -v /dev:/dev \
    --privileged \
    kernelci/chromiumos
```

Or maybe i can just update documentation later?

**Comment by gctucker** [comment]
OK thanks, didn't notice that. I've updated it now.

**Comment by nuclearcat** [comment]
Tested manually:
/kci_rootfs build --rootfs-config chromiumos-amd64-generic --data-path config/rootfs/chromiumos --arch amd64 --output /tmp/kci
Images generated properly, now will test on jenkins few images

**Comment by nuclearcat** [comment]
Generated bullseye-cros-flash in jenkins successfully with this PR:
https://storage.chromeos.kernelci.org/images/rootfs/debian/bullseye-cros-flash/debostest/amd64/
Job log: https://bot.staging.kernelci.org/job/denysf/job/rootfs-builder-debos/6/console

**Pull request merged**
