### PR TITLE
CHROMEOS rootfs-configs-chromeos.yaml: add chromiumos-grunt

### PR DESCRIPTION
**Pull request by gctucker**
Add a config entry for building Chromium OS R100 for grunt.

Depends on #1267

### CODE REVIEW

**Comment by gctucker** [comment]
> hey @gctucker I noticed you've added rootfs for grunt in this PR as well.. Anyway I think I can boot and test the image.

Ah yes, I guess I did this at the same time as adding `hatch`. I haven't tried building the `grunt` image yet though. Is the YAML config the same as yours?

**Comment by alexandrasp** [comment]
> > hey @gctucker I noticed you've added rootfs for grunt in this PR as well.. Anyway I think I can boot and test the image.
> 
> Ah yes, I guess I did this at the same time as adding `hatch`. I haven't tried building the `grunt` image yet though. Is the YAML config the same as yours?

yes, the same YAML config..as you suggested, first try was using configurations similar to hatch.

**Comment by gctucker** [comment]
@alexandrasp Have you tried to build it on staging? If so, please provide a link to the job.

**Comment by gctucker** [comment]
@nuclearcat @alexandrasp OK I've run a rebuild of the `kernelci/cros-sdk` image and it has been pushed to the Docker hub. So please try again in Jenkins if this was the only issue causing the builds to fail.

**Comment by nuclearcat** [comment]
Yes if we do flag --no-cache or there is no old cache it should help (so we just have newer depot_tools)

**Comment by gctucker** [comment]
Build started: https://bot.staging.kernelci.org/job/gtucker/job/chromeos/job/rootfs-builder/1/console

**Comment by gctucker** [comment]
> Build started: https://bot.staging.kernelci.org/job/gtucker/job/chromeos/job/rootfs-builder/1/console

Well it didn't go very far:
```
/data/workspace/bot.staging.kernelci.org/kernel-builder/workspace/gtucker/chromeos/rootfs-builder/kernelci-core/config/rootfs/chromiumos/scripts/build_board.sh: line 27: repo: command not found
```

**Comment by gctucker** [comment]
Ah I know, the image was built with the changes that remove `depot_tools`. Alright, updating the image again now.

**Comment by gctucker** [comment]
OK running now with the `gtucker/kernelci-cros-sdk` image:
https://bot.staging.kernelci.org/job/gtucker/job/chromeos/job/rootfs-builder/2/console

**Comment by nuclearcat** [comment]
Forgot to report, built rootfs with this patch: https://bot.staging.kernelci.org/job/denysf/job/cros-rootfs-build/6/consoleFull , used my own tree (for depot-tools fix), but cherry-picked your commit.

**Review by nuclearcat — APPROVED** [review]
LGTM, built on jenkins

**Comment by alexandrasp** [comment]
LGTM ! Now grunt was flashed and it is working :)

**Pull request merged**
