### PR TITLE
Add documentation for TOML settings 

### PR DESCRIPTION
**Pull request by JenySadadia**
Fixes https://github.com/kernelci/kernelci-core/issues/1999

### CODE REVIEW

**Comment by JenySadadia** [comment]
Updated staging https://static.staging.kernelci.org/docs/core/ for the review.

**Comment by JenySadadia** [comment]
@gctucker Should I update `kci_*.md` documentation as well or wait until `.conf` gets deprecated?

**Comment by gctucker** [comment]
> @gctucker Should I update `kci_*.md` documentation as well or wait until `.conf` gets deprecated?

I think it's not really necessary as the old `kci_*` tools should be deprecated at the same time as the old `.conf` settings format.  Also we might have different settings options for the old and new tools, so in practice we would basically have a new way of configuring things in TOML rather than just a translation of the old settings.

**Review by gctucker — APPROVED** [review]
Oh I don't think we should be deprecating the page about user settings.  Just the old format is being deprecated, the new TOML format is still user settings.

I think that's just a matter of organising things in the documentation structure.  We can probably merge it like this anyway as I would like to create a "legacy" section about the things that are going to be deprecated, and the old settings format would be going there anyway.  Just the TOML page would become the new "user settings" file.

**Comment by gctucker** [comment]
Let's just wait for this to land on the staging static website to double check formatting etc. and I think it'll be good to get merged.

**Comment by JenySadadia** [comment]
> Let's just wait for this to land on the staging static website to double check formatting etc. and I think it'll be good to get merged.

Pushed the changes on staging https://static.staging.kernelci.org/docs/core/.

**Comment by gctucker** [comment]
> > Let's just wait for this to land on the staging static website to double check formatting etc. and I think it'll be good to get merged.
> 
> Pushed the changes on staging https://static.staging.kernelci.org/docs/core/.

Yes, just double-checked that.  In principle it should get automatically deployed with the rest of the staging update every 8h but I'm not sure if it's always working as intended.  In any case, that's all sorted now.

**Pull request merged**
