### PR TITLE
test-configs.yaml: Remove ltp-mm from a Collabora lab device

### PR DESCRIPTION
**Pull request by Lakshmipathi**
Remove ltp-mm job from Collabora device bcm2836-rpi-2-b-cbg-0

Signed-off-by: lakshmipathi.g <lakshmipathi.ganapathi@collabora.com>

### CODE REVIEW

**Comment by gctucker** [comment]
This change is actually to stop running `ltp-mm` on the `bcm2836-rpi-2-b` device type, which may also be in other labs.  So it's not really about stopping to run these tests in Collabora's lab.  Please adjust the commit message accordingly.

**Comment by gctucker** [comment]
Tested OK on staging, the other device types are still running `ltp-mm`:
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20210322.0/plan/ltp-mm/

**Comment by Lakshmipathi** [comment]
ok, updated the patch.

**Review by gctucker — APPROVED** [review]
Tested OK on staging: https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20210329.0/plan/ltp-mm/

**Pull request merged**
