### PR TITLE
test-configs.yaml: Enable additional preempt-rt tests

### PR DESCRIPTION
**Pull request by igaw**
While cyclictest is the classic preempt-rt test, cyclicdeadline and the rtla tests are also interesting to run.

Since these are all smoke test there is no point in running them too long. Thus reduce the runtime per test to one minute. This should keep the total preempt-rt runtime roughly in the same time frame.

### CODE REVIEW

**Comment by jan-kiszka** [comment]
@patersonc @aliceinwire, can CIP help out on this?

**Comment by broonie** [comment]
I've created a PR to add @igaw to the list of people who's PRs get automatically included in staging tests: https://github.com/kernelci/kernelci-deploy/pull/132

**Comment by igaw** [comment]
Figured out how to resolve all the dependencies to run `make test` locally. 

Also, I think it would make sense to figure out if we could run a bunch of different workloads. `hackbench` is mostly stressing the scheduler. E.g. I am running `stress-ng` in my lab as workload. But first, I try to figure out the basic stuff how configure kernelci.

**Comment by igaw** [comment]
Also one thing I would like to look into, is an artifact storage service like 

  https://archive.validation.linaro.org/

so that the `rt-tests` data can be analyzed after the run in more detail.

**Comment by nuclearcat** [comment]
Let me know please when PR is ready for testing on staging, as it will require some adjustments for staging patches.

**Comment by igaw** [comment]
@nuclearcat I am ready. I fixed all reports from `make test` and it should at least pass this level of checks.

**Comment by nuclearcat** [comment]
Thanks, i will do staging run in few hours, today (need to test few more pending PR as well).

**Comment by nuclearcat** [comment]
I am sorry for delay, last time i tried to run on staging, it seems something missing on staging specific to CIP instance. (ii tried just by adding one of trees in monitor).
@aliceinwire do you have experience on running CIP-specific tests?
I might try again this week.

**Comment by igaw** [comment]
FWIW, it's not just for `cip` test plan, this should be enabled for the `rt-stable` test plan.

**Comment by igaw** [comment]
Okay, I'll look into it.

**Comment by igaw** [comment]
I'm feeling a bit stupid. `make check` complains all over the place. I really thought I did test my submission. Well, I'm cleanup up the mess now and restructure some more while I am at it and make the preempt-rt tests a bit more flexible to configure. This will be useful in future.

**Comment by igaw** [comment]
Changes:
 - rebased
 - fixed all the warning reported by 'make check'
 - made it possible to provide different parameters for each rt-tests

Because some of the rt-tests are CPU/board depended the last point is kind of important. I haven't looked into the different board configurations available, just assumed that the current default work fine. That is every board tested as as least 2 CPUs.

**Comment by broonie** [comment]
We do currently schedule the preempt-rt tests on Beaglebone Black which is single processor, mainly just because there's lots of boards available in my lab so we can easily schedule tests there. I think it'd be fine to just not use that board so long as we've got something else providing the coverage, or to set up a nosmp variant which we select to run on single processor systems.

**Comment by igaw** [comment]
I think it makes sense to keep the Beaglebone Black in the loop. I am also using this board locally for testing, so good for  reproducing results locally.

I haven't figured out yet how to per board type configurations are expressed. I stare a bit at the code and try to figure out what is there or to do it.

**Comment by igaw** [comment]
Alternatively, I could look into extending the test suite so it automatically selects all available CPUs. In the end we are talking about `cyclictest`, `cyclicdeadline` and `signaltest`. The rest of the test don't have any additional requirements. I think this makes more sense.

**Comment by broonie** [comment]
Support for automatic detection is probably going to be the easiest thing to get working here, yeah.

**Comment by igaw** [comment]
BTW, I haven't changed the defaults in this PR. `cyclictest` was and is still hard coded to use two threads.

Thus we don't have to wait for my PR for test-definition to land first. I'll update the kernelci configuration as soon as my test-definition is available in kernelci.

**Comment by nuclearcat** [comment]
After trying to generate tests:
```
+ kci_test generate --install-path=/data/workspace/bot.staging.kernelci.org/test-runner/workspace/test-runner/artifacts --runtime-json=/data/workspace/bot.staging.kernelci.org/test-runner/workspace/test-runner/artifacts/lab-broonie.json --storage=http://storage.staging.kernelci.org/ --runtime-config=lab-broonie --user=kernel-ci --runtime-token=**** --output=/data/workspace/bot.staging.kernelci.org/test-runner/workspace/test-runner/jobs/lab-broonie --callback-id=kernel-ci-callback-staging --callback-url=https://api.staging.kernelci.org/
Traceback (most recent call last):
  File "/usr/local/bin/kci_test", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kernelci/scripts/kci_test.py", line 409, in main
    status = opts.command(configs, opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kernelci/scripts/kci_test.py", line 346, in __call__
    job = runtime.generate(
          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kernelci/legacy/lava/__init__.py", line 85, in generate
    data = template.render(params)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/etc/kernelci/lava/preempt-rt/generic-uboot-tftp-ramdisk-preempt-rt-template.jinja2", line 1, in top-level template code
    {% extends 'boot/generic-uboot-tftp-ramdisk-boot-template.jinja2' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/kernelci/lava/boot/generic-uboot-tftp-ramdisk-boot-template.jinja2", line 1, in top-level template code
    {% extends 'base/kernel-ci-base-tftp-deploy.jinja2' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/kernelci/lava/base/kernel-ci-base-tftp-deploy.jinja2", line 1, in top-level template code
    {% extends 'base/kernel-ci-base.jinja2' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/kernelci/lava/base/kernel-ci-base.jinja2", line 79, in top-level template code
    {% block actions %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/kernelci/lava/preempt-rt/generic-uboot-tftp-ramdisk-preempt-rt-template.jinja2", line 5, in block 'actions'
    {% include 'preempt-rt/preempt-rt.jinja2' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/etc/kernelci/lava/preempt-rt/preempt-rt.jinja2", line 22, in template
    path: automated/linux/{{ tst_group | tst_cmd }}/{{ tst_cmd }}.yaml
^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateAssertionError: No filter named 'tst_cmd'.
```

**Comment by igaw** [comment]
I've tried hard to get `kci_test` working locally but failed. Thus I tried to use a jinja2 template test and yamllint to figure out if the configuration gets correctly rendered. As it turns out there were some more typos. They should be fixed now.

Sorry for this back and forth. I'll try to get kernelci eventually running in my own lab, so that I can test everything locally.

**Comment by igaw** [comment]
```yaml
plan: preempt-rt-cyclictest
job_timeout: 10
tst_cmd: 'cyclictest'
tst_group:
```

```yaml
- test:
    name: preempt-rt-cyclictest
    timeout:
      minutes: 10

    definitions:
    - from: inline
      repository:
        metadata:
          format: Lava-Test Test Definition 1.0
          name: preempt-rt-prereq
          description: Pre-requisites for PREEMPT_RT
        run:
          steps:
          - apt-get update && apt-get install -y procps rt-tests
      name: preempt-rt-prereq
      path: inline/preempt-rt-prereq.yaml

    - repository: https://github.com/kernelci/test-definitions.git
      from: git
      revision: kernelci.org
      path: automated/linux/cyclictest/cyclictest.yaml
      name: preempt-rt-cyclictest
      parameters:
        ARTIFACTORIAL_TOKEN: 
        ARTIFACTORIAL_URL: 
        AFFINTIY: 0-1
        DURATION: 300s
        BACKGROUND_CMD: hackbench
      
        HISTOGRAM: 
        INTERVAL: 1000
        PRIORITY: 98
        THREADS: 2
```

**Comment by igaw** [comment]
The PR for LAVA has been merged. I am not really familiar how the LAVA test suite is intergrated into kernel-ci. Does it always run against the latest version or is there some sort of sync involved. Just asking if I should update this PR to use the new feature which lets cyclictest run on all CPUs and not just two.

**Comment by igaw** [comment]
@nuclearcat I've update the series and it's ready for the integration test. I really hope i got it right this time

**Comment by igaw** [comment]
@nuclearcat friendly ping.

**Comment by nuclearcat** [comment]
As referenced in PR we are creating -RT testing support in new system, called Maestro. Probably it is completed by now, feel free to open PR or issue in kernelci-pipeline repository if you want to send any updates.
Legacy system is not being updated, so i am closing this PR.

**Comment by igaw** [comment]
Is the new dashboard already online, to see if the RT builds/tests are running?

**Comment by igaw** [comment]
Nevermind, found the docs to it: https://docs.kernelci.org/maestro/api/early-access/

**Comment by padovan** [comment]
@igaw you can also see the results on the WIP grafana dashboard from Helen Koike: https://grafana.kernelci.org/d/OKXc44EIz/wip3a-koike?orgId=1&var-origin=maestro&var-tree=stable-rt&var-branch=All&var-test_path_regex=kernelci_baseline&var-platform=%25&var-config=%25&var-datasource=default

**Comment by igaw** [comment]
I've shared the dashboard with my fellow stable-rt maintainers and we played a bit around. It seems everyone like the direction this project takes.

Anyway, one remark was that there was no `rt` config used for the builds, just the default ones. Which is good as it already found a bug in one of our rt patch series. So the question is if it would be possible to enable the `rt` configs back as well? Thanks!

**Comment by musamaanjum** [comment]
Thank you so much for reporting.

The preempt_rt config builds are already enabled. There is some problem on the dashboard side and those results are missing. I'll investigate.

**Comment by padovan** [comment]
@igaw thanks for the valuable feedback! Let's also setup email notifications for your trees and tests (cc @JenySadadia)

**Comment by igaw** [comment]
For the email notification, could these emails send to <stable-rt@vger.kernel.org> too? We use this mailing list for stable work, so it would be the right place to post any build results etc. Thanks!

**Comment by JenySadadia** [comment]
Hello @igaw 
For starters, I'll start working on reporting build failures and rt-tests failures in the email notification.
Is there any other test failure would you like to see in the report? Such as boot failures?

**Comment by igaw** [comment]
Hi @JenySadadia, cool! Yes, boot failures would also be good to get.

**Comment by JenySadadia** [comment]
> Hi @JenySadadia, cool! Yes, boot failures would also be good to get.

Okay, thanks.

**Comment by nuclearcat** [comment]
Opened issue https://github.com/kernelci/kernelci-core/issues/2643
As it's better to continue discussion there and close PR that is no more relevant. Thank you!

**Pull request closed without merging**
