### PR TITLE
kernelci.build: apply a patch to test regression

### PR DESCRIPTION
**Pull request by JenySadadia**
Apply a patch for `linux/drivers/base/test/property-entry-test.c` to test regression tracker script from pipeline.

### CODE REVIEW

**Comment by gctucker** [comment]
This could also be done via `kernelci-deploy` by adding the patch file directly there.

**Comment by JenySadadia** [comment]
> This could also be done via `kernelci-deploy` by adding the patch file directly there.

`kernelci.build.update_repo` is being called from pipeline service. The patch can not be applied before starting the containers. Hence, I added it here.

**Comment by gctucker** [comment]
The patches in `kernelci-deploy` are used by the staging script to create the `staging-{next,mainline,stable}` branches and these are monitored by the new pipeline too.

**Comment by JenySadadia** [comment]
> The patches in `kernelci-deploy` are used by the staging script to create the `staging-{next,mainline,stable}` branches and these are monitored by the new pipeline too.

As per my understanding from the code, `pending.py` script is applying all the patches. The update repository will be done by pipeline at the runtime. That will overwrite all the changes in the `linux` source if found. So, we can not apply the patch beforehand.
Please correct me if I am wrong.

**Comment by JenySadadia** [comment]
I had a discussion with @mgalka about this and I understood what you meant @gctucker.
So we can add a patch to be run from `kernel.py` directly.

**Comment by JenySadadia** [comment]
Tested regressions by failing test results instead. Closing this one.

**Pull request closed without merging**
