### PR TITLE
test-configs.yaml: add imx8mm-innocomm-wb15-evk

### PR DESCRIPTION
**Pull request by Bastian-Krause**
LAVA device-type is upstream:
https://git.lavasoftware.org/lava/lava/-/merge_requests/2037

### CODE REVIEW

**Comment by Bastian-Krause** [comment]
Hey, is there anything I can do to get this merged?

**Comment by mgalka** [comment]
> Hey, is there anything I can do to get this merged?

Hi,
At the moment I can see that the changes that are running on staging, but for some reason I can't see the test results on a dashboard. I'm going to investigate if there is maybe some glitch which prevents LAVA job definition from being generated. It'd be good if you could have a look from the other end and check if LAVA is handling kernelci jobs properly.

**Review by gctucker — COMMENTED** [review]
The device is offline:
https://hekla.openlab.pengutronix.de/scheduler/device_type/imx8mm-innocomm-wb15-evk

**Comment by nuclearcat** [comment]
Device appeared on dashboard and passing tests: https://staging.kernelci.org/test/plan/id/643ccc780b3162f7f7134cde/

**Pull request merged**
