### PR TITLE
Add bullseye-cros-ec rootfs image

### PR DESCRIPTION
**Pull request by mgalka**
Add Debian bullseye based image configuration for cros-ec tests.

Depends on https://github.com/kernelci/kernelci-core/pull/995

### CODE REVIEW

**Comment by mgalka** [comment]
Tested with a LAVA job using `bullseye-cros-ec` image
https://lava.collabora.co.uk/scheduler/job/5507197

Image was built on staging and pushed to staging storage:
http://storage.staging.kernelci.org/images/rootfs/debian/bullseye-cros-ec/20220124.0/amd64/rootfs.cpio.gz

**Comment by gctucker** [comment]
Could you please check the difference in size between the buster image and this new one which includes `tzdata`?  Some Chromebooks might not have a large enough data buffer to download the ramdisk over TFTP.

**Comment by mgalka** [comment]
> Could you please check the difference in size between the buster image and this new one which includes `tzdata`? Some Chromebooks might not have a large enough data buffer to download the ramdisk over TFTP.

The difference is about `5MB`:

```bash
$ find . -name rootfs.cpio.gz 2>/dev/null | xargs du
34876	./bullseye-cros-ec/amd64/rootfs.cpio.gz
29932	./buster-cros-ec/amd64/rootfs.cpio.gz


$ find . -name rootfs.cpio.gz 2>/dev/null | xargs du -h
35M	./bullseye-cros-ec/amd64/rootfs.cpio.gz
30M	./buster-cros-ec/amd64/rootfs.cpio.gz

```

**Comment by gctucker** [comment]
Great, so that difference is significant enough to not include `tzdata` unless it's needed such as in this case.

Ready to merge this now and build some production images to give them a full round of tests on staging.

**Review by gctucker — APPROVED** [review]

**Pull request merged**
