### PR TITLE
CHROMEOS: test-configs-chromeos: add some new tests in R118

### PR DESCRIPTION
**Pull request by 10ne1**
These are new tests added in R118 which are known to work. We can extend coverage more, especially on the storage side but we need some bugs like b:311421846 fixed first.

### CODE REVIEW

**Comment by a-wai** [comment]
I don't see anything wrong here, I assume you've tested those on multiple devices/architectures?

**Review by nuclearcat — CHANGES_REQUESTED** [review]
cros-tast-platform: https://chromeos.kernelci.org/test/plan/id/6559791fe923647cc5954a2c/
cros-tast-perf: Not finishing within 30 minutes, which is very excessive, please remove too "long running tests"
Example: https://storage.chromeos.kernelci.org/kernelci/linux-6.1.y-arm64-chromeos/linux-6.1.y-arm64-chromeos-20231119.0/x86_64/cros---chromeos-6.1-x86_64-chromeos-intel-pineview.flavour.config+x86-chromebook+CONFIG_MODULE_COMPRESS_GZIP=n/clang-17/lab-collabora/cros-tast-perf-asus-C523NA-A20057-coral_chromeos.html
More here: https://chromeos.kernelci.org/test/job/kernelci/branch/linux-6.1.y-arm64-chromeos/kernel/linux-6.1.y-arm64-chromeos-20231119.0/plan/cros-tast-perf/

**Comment by a-wai** [comment]
> I guess we can split the tests on the 30 seconds boundary, separate all tests that take >30s into a new config and keep the quicker tests.

Thanks for having a look! That makes sense, even going with a 1min boundary would be fine by me (it would translate to ~5min of running tests), but I don't have a strong opinion on the limit.

**Comment by nuclearcat** [comment]
i suggest to split tests and create one more tests set, like cros-tast-perf2

**Comment by nuclearcat** [comment]
https://chromeos.kernelci.org/test/job/kernelci/branch/chromeos-stable/kernel/chromeos-stable-20231123.0/plan/cros-tast-perf-long-duration/
Tests appeared, thanks!

**Pull request merged**
