### PR TITLE
EFI tree updates

### PR DESCRIPTION
**Pull request by broonie**
A couple of tweaks to the configuration for the EFI tree configuration - add the urgent branch for testing fixes and restrict the configurations built to a subset since the main goal for EFI testing is boot rather than build coverage.

@ardbiesheuvel - does this look OK to you?

### CODE REVIEW

**Comment by ardbiesheuvel** [comment]
Acked-by: Ard Biesheuvel <ardb@kernel.org>

Thanks

**Comment by gctucker** [comment]
LGTM - will get this tested on staging tomorrow after the production update.

**Comment by gctucker** [comment]
Actually getting this tested on staging now.

**Comment by gctucker** [comment]
Tested OK on staging:
https://staging.kernelci.org/test/job/efi/branch/next/kernel/efi-changes-for-v5.8-3-g84780c5438ef/

**Pull request merged**
