### PR TITLE
generate_cros_manifest.sh: Add tool to generate ChromiumOS xml manifest

### PR DESCRIPTION
**Pull request by nuclearcat**
To create new version manifest we need to fetch it a bit unusual way using ChromiumOS SDK.
We had it as comments in build_board.sh, but this create more complexity, so it is better to make proper script to automate this process.

### CODE REVIEW

**Comment by nuclearcat** [comment]
Way how this script tested:
```
git clone https://github.com/kernelci/kernelci-core/

docker run \                                                                                                                                                                                                       
    --name kernelci-build-cros \                                                                                                                                                                                   
    -itd \                                                                                                                                                                                                         
    -v $(pwd):/kernelci-core \                                                                                                                                                                                     
    --device /dev/kvm \                                                                                                                                                                                            
    -v /dev:/dev \                                                                                                                                                                                                 
    -v $(pwd)/config:/etc/kernelci \                                                                                                                                                                               
    --privileged \                                                                                                                                                                                                 
    --user cros \                                                                                                                                                                                                  
    kernelci/cros-sdk:kernelci                                                                                                                                                                                     
                                                                                                                                                                                                                   
# Execute shell
docker exec \                                                                                                                                                                                                      
    -it kernelci-build-cros \                                                                                                                                                                                      
    /bin/bash            

# then manually run the script inside docker shell
/etc/kernelci/rootfs/chromiumos/scripts/generate_cros_manifest.sh

Preparing depot tools
... lot of text will be generated...
repo sync has finished successfully.
Generating manifest
Saved manifest to cros-snapshot.xml
Copying manifest
```
After that file cros-snapshot.xml can be found in kernelci-core directory

**Comment by JenySadadia** [comment]
Why can't we un-comment lines from `build_board.sh`  to generate manifest?
What are the complexities will it introduce?

**Comment by nuclearcat** [comment]
> Why can't we un-comment lines from `build_board.sh` to generate manifest? What are the complexities will it introduce?

It was just a hack to have them there as commented, i prefer to introduce separate script and remove commented code from build_board.sh, to not mix each tool purpose.
Especially as build_board.sh becoming too long/complicated and might need better structuring to understand what it does.

**Review by mgalka — APPROVED** [review]
A follow-up should be a clean-up and rework of the build_board.sh script

**Comment by JenySadadia** [comment]
> > Why can't we un-comment lines from `build_board.sh` to generate manifest? What are the complexities will it introduce?
> 
> It was just a hack to have them there as commented, i prefer to introduce separate script and remove commented code from build_board.sh, to not mix each tool purpose. Especially as build_board.sh becoming too long/complicated and might need better structuring to understand what it does.

OK. Maybe we should think of migrating common functions to a script and using them in `build_board` and `generate_cros_manifest` files to avoid re-writing the same code.

**Pull request merged**
