### PR TITLE
Clean up unit tests

### PR DESCRIPTION
**Pull request by gctucker**
Fix all pycodestyle and pylint errors in unit tests and enable coverage accordingly in GitHub actions.

### CODE REVIEW

**Review by nuclearcat — APPROVED** [review]
LGTM
(first i was confused about using 172.17.0.1 then i realize it is just test case for config, nothing else)

**Comment by nuclearcat** [comment]
I will wait until someone can help me to review few things in https://github.com/kernelci/kernelci-core/pull/1650 at Monday, as it depends on it

**Comment by gctucker** [comment]
> LGTM (first i was confused about using 172.17.0.1 then i realize it is just test case for config, nothing else)

It's the standard host IP address when using docker-compose.yaml so it's actually functional.  But it's true it's not used in these unit tests, just the config gets loaded but no code is actually run.

**Comment by gctucker** [comment]
@mgalka @nuclearcat @aliceinwire I've enabled the Merge Queue feature on this repository as an experiment.  It's nice that it's removing the branches automatically, and maybe it can help when merging a number of PRs in a row e.g. ahead of production updates.

**Pull request merged**
