### PR TITLE
Merge videodec and arm64-chromebook fragments

### PR DESCRIPTION
**Pull request by laura-nao**
The videodec fragment was created to hold configs for decoder support, required to run decoder conformance tests on Chromebooks. The fragment is currently holding only one config for the kevin Chromebook, while decoder specific configs for other platforms were added to the arm64-chromebook fragment instead. Add the CONFIG_VIDEO_ROCKCHIP_VDEC
option to the arm64-chromebook fragment and drop the videodec one.

### CODE REVIEW

**Review by a-wai — APPROVED** [review]

**Comment by a-wai** [comment]
@nuclearcat can you please merge this? It has been tested over and over by now ;)

(see `fragments/0_config` from https://staging.kernelci.org:9000/viewer?node_id=661e320980619406aaad365e for example)

**Comment by a-wai** [comment]
@laura-nao please rebase and harass @nuclearcat to merge this one, it's been sitting here far too long ;)

**Comment by laura-nao** [comment]
> @laura-nao please rebase and harass @nuclearcat to merge this one, it's been sitting here far too long ;)

Rebased - thanks for the heads up, _almost_ forgot about this one! @nuclearcat gentle ping :)

**Review by nuclearcat — APPROVED** [review]
LGTM

**Pull request merged**
