### PR TITLE
 test-configs.yaml: Enable ltp-ipc tests on rk3288-veyron-jaq

### PR DESCRIPTION
**Pull request by Lakshmipathi**
Signed-off-by: Lakshmipathi <lakshmipathi.ganapathi@collabora.com>

### CODE REVIEW

**Comment by Lakshmipathi** [comment]
ltp results from different devices:

|                  |                              |            |                 |            |                  |                 |                    |                    |                     |           |                   |                  |
| ---------------- | ---------------------------- | ---------- | --------------- | ---------- | ---------------- | --------------- | ------------------ | ------------------ | ------------------- | --------- | ----------------- | ---------------- |
|                  | hp-x360-12b-ca0004na-octopus | Jetson-tk1 | bcm2836-rpi-2-b | odroid-xu3 | Beaglebone-black | Imx6q-sabrelite | hp-11A-G6-EE-grunt | sun50i-h6-pine-h64 | rk3288-rock2-square | hip07-d05 | rk3288-veyron-jaq | rk3399-gru-kevin |
|                  |                              |            |                 |            |                  |                 |                    |                    |                     |           |                   |                  |
| syscalls         | **fail**                         | **fail**       | **fail**            | **fail**       | **fail**             | **fail**            | pass               | pass               | pass                | **fail**      | pass              | pass             |
| mm               | **fail**                         | pass       | pass            | **fail**       | **fail**             | pass            | pass               | pass               | pass                | **fail**      | pass              | pass             |
| math             | pass                         | pass       | pass            | pass       | **fail**             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| timers           | pass                         | pass       | pass            | pass       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| Fcntl-locktests  | pass                         | pass       | pass            | pass       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| ipc              | pass                         | pass       | pass            | pass       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| fsx              | pass                         | pass       | pass            | pass       | **fail**             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| fs               | **fail**                         | **fail**       | pass            | **fail**       | **fail**             | **fail**            | pass               | pass               | pass                | **fail**      | pass              | pass             |
| hugetlb          | pass                         | pass       | pass            | pass       | **fail**             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| io               | pass                         | **fail**       | pass            | pass       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| nptl             | pass                         | **fail**       | pass            | pass       | **fail**             | pass            | pass               | pass               | pass                | **fail**      | pass              | pass             |
| pty              | pass                         | pass       | pass            | pass       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| containers       | pass                         | **fail**       | **fail**            | **fail**       | **fail**             | **fail**            | pass               | pass               | pass                | pass      | pass              | pass             |
| fs_bind          | pass                         | pass       | pass            | **fail**       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| filecaps         | pass                         | pass       | pass            | pass       | **fail**             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| admin_tools      | pass                         | pass       | pass            | pass       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| connectors       | pass                         | pass       | pass            | pass       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
|                  |                              |            |                 |            |                  |                 |                    |                    |                     |           |                   |                  |
| controllers      | **fail**                         | pass       | **fail**            | **fail**       | **fail**             | **fail**            | **fail**         | pass               | pass                | **fail**      | pass              | pass             |
| crypto           | pass                         | pass       | pass            | **fail**       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| device-drivers   | pass                         | pass       | pass            | pass       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| firmware         | stuck                        | pass       | pass            | pass       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| hotplug          | pass                         | pass       | pass            | pass       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| include          | pass                         | pass       | pass            | pass       | **fail**             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| input            | pass                         | pass       | pass            | pass       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| lib              | pass                         | pass       | pass            | pass       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| logging          | pass                         | pass       | pass            | pass       | **fail**             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| mce-test         | pass                         | pass       | pass            | pass       | **fail**             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| mem              | pass                         | pass       | pass            | pass       | **fail**             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| numa             | pass                         | pass       | pass            | pass       | **fail**             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| power_management | pass                         | **fail**       | pass            | pass       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| sched            | pass                         | **fail**       | **fail**            | **fail**       | **fail**             | **fail**            | pass               | pass               | pass                | pass      | pass              | pass             |
| security         | pass                         | pass       | pass            | pass       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |
| sound            | pass                         | pass       | pass            | pass       | pass             | **fail**            | pass               | pass               | pass                | pass      | pass              | pass             |
| tracing          | pass                         | **fail**       | **fail**            | **fail**       | **fail**             | **fail**            | pass               | pass               | pass                | pass      | pass              | pass             |
| uevents          | pass                         | pass       | pass            | pass       | pass             | pass            | pass               | pass               | pass                | pass      | pass              | pass             |

**Comment by gctucker** [comment]
Thanks for the table with all the initial experiments, I think that could be added to the LTP roadmap item:
https://github.com/kernelci/kernelci-core/issues/506

For this particular PR, we should be looking at the results, to check the LTP tests got run correctly on veyron-jaq.  Can you please take a look at the results on stable, mainline and next from staging.kernelci.org and see if there was any problem?

**Comment by gctucker** [comment]
The jobs failed because the `armhf` flavour of the Buster LTP rootfs is missing:
https://storage.kernelci.org/images/rootfs/debian/buster-ltp/20201002.0/

Maybe it failed to build, we'll get a new set built tomorrow as part of the production update.

**Comment by gctucker** [comment]
Actually, the config only enables `arm64` and `amd64`:
https://github.com/kernelci/kernelci-core/blob/master/rootfs-configs.yaml#L140
```yaml
  buster-ltp:
    rootfs_type: debos
    debian_release: buster
    arch_list:
      - amd64
      - arm64
    script: "scripts/buster-ltp.sh"
```
Any reason why we're not building it for `armhf`?  Maybe this just needs another PR to add it.

**Comment by Lakshmipathi** [comment]
There is no specific reason for not building `armhf` other than we started with `rk3399-gru-kevin` which uses arm64. Let me send another PR for rootfs-config.

**Comment by Lakshmipathi** [comment]
Created new PR https://github.com/kernelci/kernelci-core/pull/523

**Comment by gctucker** [comment]
Thanks, please get some buster-ltp images built on staging for armhf and armel to get this tested before it's deployed in production.

**Comment by Lakshmipathi** [comment]
Built  buster-ltp images: https://storage.staging.kernelci.org/images/rootfs/debian/buster-ltp/20201022.0/ and started LAVA job https://lava.collabora.co.uk/scheduler/job/2741325

**Comment by gctucker** [comment]
Great, that worked :)

**Comment by gctucker** [comment]
Waiting for the new `armhf` builds in production and this should get tested again on staging.

**Review by gctucker — APPROVED** [review]
Tested OK on staging: https://staging.kernelci.org/test/plan/id/5f9bf7468db6c7c42f620c2c/

**Pull request merged**
