### PR TITLE
test-configs.yaml: Enable LTP-pty tests on devices in lab-collabora

### PR DESCRIPTION
**Pull request by Lakshmipathi**
Signed-off-by: lakshmipathi.g <lakshmipathi.ganapathi@collabora.com>

### CODE REVIEW

**Comment by gctucker** [comment]
Please add a description of the changes in the commit message.

**Comment by Lakshmipathi** [comment]
okay added them.

**Comment by alexandrasp** [comment]
@Lakshmipathi I could not see results from this test plan in front-end, are there any?

**Comment by gctucker** [comment]
@Lakshmipathi Please rebase this PR, then it should get deployed on staging.

**Comment by Lakshmipathi** [comment]
@alexandrasp @gctucker ,  Let me rebase this PR, results should appear on front-end after that.

**Comment by gctucker** [comment]
It's conflicting with other PRs so it's not being deployed on staging.  I think we need to sort out the POSIX tests first.

**Comment by gctucker** [comment]
@Lakshmipathi Please rebase now that the Open POSIX changes have been merged.

**Comment by Lakshmipathi** [comment]
Tested on staging: https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20210420.0/plan/ltp-pty/

**Review by gctucker — APPROVED** [review]

**Pull request merged**
