### PR TITLE
feat(kbuild): Add kselftest node

### PR DESCRIPTION
**Pull request by nuclearcat**
Often we have kselftest build failing, but it doesn't register as failure anywhere. Now we will add kbuild sub-node with kselftest suffix to indicate success or failure of kselftest build.

### CODE REVIEW

**Comment by JenySadadia** [comment]
This is setting node `id` and `parent` with the same id.
Such as https://staging.kernelci.org:9000/viewer?node_id=66c72dcd7c8a38c2eb18a604
That's breaking kcidb bridge while getting test data.

**Comment by nuclearcat** [comment]
I fixed that recently

**Comment by JenySadadia** [comment]
> I fixed that recently. I guess we need to add safeguards in API as well, and few other places, to not allow parent to be pointed to itself.

Thanks. Yes, I agree.

**Comment by nuclearcat** [comment]
Tested on staging, works

**Pull request merged**
