### PR TITLE
Enable landlock selftests on Le Potato

### PR DESCRIPTION
**Pull request by broonie**
Enable landlock selftests on Le Potato.

### CODE REVIEW

**Comment by mgalka** [comment]
There seem to be some networking issues during the boot

https://storage.staging.kernelci.org/kernelci/staging-next/staging-next-20221120.0/arm64/defconfig+kselftest/clang-16/lab-broonie/kselftest-landlock-meson-gxl-s905x-libretech-cc.html#L1054

https://storage.staging.kernelci.org/kernelci/staging-next/staging-next-20221121.0/arm64/defconfig+kselftest/clang-16/lab-broonie/kselftest-landlock-meson-gxl-s905x-libretech-cc.html#L1059

**Comment by gctucker** [comment]
Still failing to boot, like #1505:
https://staging.kernelci.org/test/plan/id/64295923ae31fa50a60b9bd1/

If this and other similar PRs blocked with the same boot failures aren't getting fixed then they'll have to be closed at some point.

**Comment by broonie** [comment]
That'll need some progress on the kselftest-slim PR https://github.com/kernelci/kernelci-core/pull/1759

**Comment by gctucker** [comment]
Adding skip label because of #1994

**Comment by nuclearcat** [comment]
Closing, as we are deprecating the legacy system. If this is still an issue or relevant, please re-open it under the Maestro system. Thank you for your contribution, and sorry for the inconvenience.

**Pull request closed without merging**
