### PR TITLE
kernelci.cli.node: add command to submit hierarchy

### PR DESCRIPTION
**Pull request by JenySadadia**
Fixes https://github.com/kernelci/kernelci-core/issues/2521
Add `kci` command to submit hierarchy of results.

### CODE REVIEW

**Comment by JenySadadia** [comment]
Tested OK locally:
```
$ ./kci node submit-hierarchy 662b6d0fc9c2e38720c1463b input.json
```
`input.json`:
```
{
    "node": {
        "result": "pass",
        "artifacts": {},
        "data": {"arch": "x86"}
    },
    "child_nodes": [
        {
            "node": {
                "name": "config",
                "result": "pass"
            },
            "child_nodes": {}
        },
        {
          "node": {
              "name": "exec",
              "result": "pass"
          },
          "child_nodes": {}
        }
    ]
  }

```

**Review by nuclearcat — APPROVED** [review]
Thanks, quite good command to simulate some of test submissions.

**Comment by nuclearcat** [comment]
My 5 cents, AFAIK on LAVA we submit tests such way, as whole hierarchies, as they arrive and being parsed by lava. Not sure if i am right, but this might be handy to debug some corner cases.

**Comment by JenySadadia** [comment]
> @JenySadadia I'm sorry I didn't notice this earlier, but I have a question: what use case does this cover that couldn't be done already with `kci node submit`, which could also submit node hierarchies?

`kci node submit` can add or update a single node. It can't be used for submitting node hierarchy.

**Pull request merged**
