### PR TITLE
config/docker: add clang-15

### PR DESCRIPTION
**Pull request by gctucker**
Update clang-14 Dockerfile and add new one for clang-15 now that the
main repository has moved to clang-15.

Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>

### CODE REVIEW

**Review by musamaanjum — APPROVED** [review]

**Comment by gctucker** [comment]
Tested that the clang-15 image got built and pushed to the Docker hub:
```
$ docker pull kernelci/staging-clang-15
Using default tag: latest
latest: Pulling from kernelci/staging-clang-15
Digest: sha256:26c9ef68fa032eae95db5827d751bffbda1ab7760d4934888063aea3a6aa0316
Status: Image is up to date for kernelci/staging-clang-15:latest
docker.io/kernelci/staging-clang-15:latest
```

**Comment by gctucker** [comment]
I've updated the patches in kernelci-deploy to start using clang-15 on staging with linux-next builds. We should have results for that tomorrow.

**Comment by gctucker** [comment]
Tested OK on staging with clang-15 on linux-next:
https://staging.kernelci.org/build/kernelci/branch/staging-next/kernel/staging-next-20220210.0/

**Comment by gctucker** [comment]
Staging mainline still using clang-11:
https://staging.kernelci.org/build/kernelci/branch/staging-mainline/kernel/staging-mainline-20220210.0/

**Pull request merged**
