### PR TITLE
test-configs.yaml: Enable decoder conformance tests on mt8195-cherry-…

### PR DESCRIPTION
**Pull request by laura-nao**
…tomato-r2

Enable V4L2 decoder conformance tests on mt8195-cherry-tomato-r2 for H264, VP8 and VP9 formats.

### CODE REVIEW

**Comment by laura-nao** [comment]
Reference results from manual LAVA jobs:
- H264: https://lava.collabora.dev/results/11382641 (98/135)
- VP8: https://lava.collabora.dev/results/11382422 (59/61)
- VP9: https://lava.collabora.dev/results/11382652 (276/305)

**Review by nuclearcat — APPROVED** [review]
Present on dashboard: https://chromeos.kernelci.org/test/job/collabora-chromeos-kernel/branch/for-kernelci/kernel/v6.6-rc2-7111-g62fb180d207d/plan/v4l2-decoder-conformance-vp9_chromeos/

**Comment by nuclearcat** [comment]
Hm, just noticed, not sure if it should appear in chromeos results...

**Comment by gctucker** [comment]
> Present on dashboard: https://chromeos.kernelci.org/test/job/collabora-chromeos-kernel/branch/for-kernelci/kernel/v6.6-rc2-7111-g62fb180d207d/plan/v4l2-decoder-conformance-vp9_chromeos/

@nuclearcat @laura-nao  This PR is for the main branch though, are the results also on staging.kernelci.org?

**Comment by gctucker** [comment]
Ha, mid-air message collision :grin:

**Comment by nuclearcat** [comment]
@gctucker this one seems need manual trigger of some kernel with videodec fragment, because
```
      - passlist: {defconfig: ['videodec']}
```
I will try to do that now.

**Comment by laura-nao** [comment]
> Ha, mid-air message collision 😁

:D

> are the results also on staging.kernelci.org?

Fwiw I can see results for the `media` tree in the staging instance (with `videodec` fragment), e.g.:
https://staging.kernelci.org/test/plan/id/650b1892c15452129cb87511/

Can't see any decoder test result for `next` or `mainline` but maybe that's expected on `staging`.

**Comment by gctucker** [comment]
OK I think that's fine then, it shows the tests worked on the device.  I guess someone kicked a `media` tree job on staging for this purpose anyway.  Otherwise, I believe the weekly linux-next jobs are still run so extra results should be visible on Monday.

**Comment by gctucker** [comment]
@nuclearcat Note: if the weekly staging linux-next jobs are disabled at the moment then we probably should re-enable them and factor this in with the Azure cost measurements (should be minor as builds are still all in GCP)

**Comment by nuclearcat** [comment]
I think we are fine at the moment, also i think our efforts very soon will be concentrated on enabling more tests in API/Pipeline, and better to have good staging there ready.

**Comment by gctucker** [comment]
Well we don't have coverage for the new API & Pipeline yet anyway.  If we keep having to review PRs for the legacy system then enabling the weekly linux-next on staging would help with cases like this one.  If it's becoming rare then sure we can just trigger extra trees whenever it makes sense in practice like for the `media` one this week.

**Pull request merged**
