### PR TITLE
kernelci tree email recipients

### PR DESCRIPTION
**Pull request by gctucker**
Add clabbe and ktouil from BayLibre to the list of email recipients for the kernelci tree.

### CODE REVIEW

**Comment by gctucker** [comment]
@khilman Sure, I don't mind as long as all the people working on KernelCI get the email reports.

**Comment by khilman** [comment]
@gctucker Yes.  kernelci@baylibre.com is (currently) an alias for myself, Corentin and Khouloud.

**Comment by gctucker** [comment]
@khilman OK I've updated the PR with kernelci@baylibre.com.  There should be some emails sent tonight for a staging run.

**Comment by gctucker** [comment]
@touilkhouloud @khilman @montjoie did you get the staging email reports from yesterday?

**Comment by touilkhouloud** [comment]
@gctucker Yes for me I did get them.

**Comment by montjoie** [comment]
I get them also.

**Comment by khilman** [comment]
Yes, I got them.

**Pull request merged**
