### PR TITLE
test-configs: Add 4 more amlogic boards

### PR DESCRIPTION
**Pull request by montjoie**
This patchs adds 4 more amlogic boards:
- meson-gxl-s805x-libretech-ac
- meson8b-ec100
- meson-gxl-s905d-p230
- meson-gxl-s905x-p212

### CODE REVIEW

**Comment by khilman** [comment]
@montjoie please add links to LAVA commits where these device-types are merged into LAVA.

**Comment by montjoie** [comment]
For ec100, p212, and meson-gxl-s805x-libretech-ac
https://git.lavasoftware.org/lava/lava/merge_requests/676
For p230
https://git.lavasoftware.org/lava/lava/merge_requests/674

**Comment by gctucker** [comment]
> This patchs adds 4 more amlogic boards:
> 
> * meson-gxl-s805x-libretech-ac

It failed to boot the clang kernel, maybe due to the image size?
https://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190805.1/arm64/defconfig/clang-8/lab-baylibre-dev/boot-meson-gxl-s805x-libretech-ac.html

Otherwise it worked fine with gcc:
https://staging.kernelci.org/boot/id/5d4811d7cf3a0feca253c257/

> * meson8b-ec100

Some jobs were generated on Jenkins but they were not submitted, looks like the board is offline?

> * meson-gxl-s905d-p230

Tested OK on staging:
https://staging.kernelci.org/boot/id/5d48108ccf3a0fe59853c283/
https://staging.kernelci.org/boot/id/5d4810c8cf3a0febc153c2ad/

> * meson-gxl-s905x-p212

Same as ec100, no jobs submitted.  Is the board offline?

**Comment by gctucker** [comment]
@montjoie Please see the comment above, are these issues expected?

**Comment by montjoie** [comment]
The p212 and ec100 was delayed finally and are not already in the lab. I will add them next week.

**Comment by gctucker** [comment]
OK let's keep this PR open until the next round then.

**Comment by gctucker** [comment]
@montjoie Any update on the status of these new boards?

**Comment by montjoie** [comment]
Sorry, I delayed the inclusion of the missing two board

**Comment by gctucker** [comment]
Maybe you could split this PR to merge the boards that are already online and add the others later?

**Pull request closed without merging**
