### PR TITLE
Add cros test plan

### PR DESCRIPTION
**Pull request by eballetbo**
The purpose of these two patches is switch from the dummy cros-ec test to the new cros test plan based on the crostests test suite framework. A new test suite programmed in python to test CrOS specific kernel drivers.

### CODE REVIEW

**Comment by gctucker** [comment]
There appears to be a problem:
```
Traceback (most recent call last):
  File "./kci_test", line 207, in <module>
    test_configs = kernelci.config.test.from_yaml(args.yaml_test_configs)
  File "/home/buildslave/build-trigger/workspace/kernel-build-trigger/kernelci-core/kernelci/config/test.py", line 436, in from_yaml
    for name, test_plan in data['test_plans'].items()
  File "/home/buildslave/build-trigger/workspace/kernel-build-trigger/kernelci-core/kernelci/config/test.py", line 436, in <dictcomp>
    for name, test_plan in data['test_plans'].items()
  File "/home/buildslave/build-trigger/workspace/kernel-build-trigger/kernelci-core/kernelci/config/test.py", line 325, in from_yaml
    'rootfs': file_systems[test_plan['rootfs']],
KeyError: 'debian_buster-crostests_ramdisk'
```
https://staging-ci.kernelci.org/job/kernel-build-trigger/474/console

**Comment by gctucker** [comment]
Also, please rebase on top of current `master` branch.

**Comment by eballetbo** [comment]
I'm going to split this PR in two parts as the second patch depends on have a rootfs available in kernelci.

**Comment by gctucker** [comment]
Sounds good, thanks.

**Pull request closed without merging**
