### PR TITLE
T36372 Update base template for new node schema

### PR DESCRIPTION
**Pull request by JenySadadia**
Need to update the value of `Node.status` and add `Node.result` to accommodate new node schema from API.

### CODE REVIEW

**Review by gctucker — COMMENTED** [review]
LGTM, let's see if we can get it tested on staging.

**Comment by gctucker** [comment]
Please change the commit subjects to something more descriptive. "Modify" doesn't mean much, each git commit is modifying something.

**Comment by JenySadadia** [comment]
> Please change the commit subjects to something more descriptive. "Modify" doesn't mean much, each git commit is modifying something.

Updated the commits.

**Comment by gctucker** [comment]
Tested OK on staging.

**Pull request merged**
