### PR TITLE
T23210 settings file

### PR DESCRIPTION
**Pull request by gctucker**
Add support for a settings file with sections per component and per command line utility, with the possibility to override any of these values with command line arguments to keep compatibility with current use-cases.

### CODE REVIEW

**Comment by gctucker** [comment]
Tested OK on staging.

This PR doesn't require any changes in the Jenkins jobs as they specify everything on the command line and not in any settings file (yet).

**Comment by khilman** [comment]
Done some basic testing of local scripts using `kci_build` and `kci_test` and works pretty well.

A feature request: allow `--yaml-test-configs` and `--yaml-lab-configs` to be set from the settings file. 

This will facilitate using the tools outside of the kernelci-core dir.

**Comment by khilman** [comment]
Also, I haven't tested this with `kci_data` yet, but the `[db]` section(s) here seem to obsolete the need for `db-configs.yaml`, correct?

**Comment by gctucker** [comment]
> Also, I haven't tested this with `kci_data` yet, but the `[db]` section(s) here seem to obsolete the need for `db-configs.yaml`, correct?

It's the other way round: `db-configs.yaml` replaces the database-related command line arguments such as `--api`.  These are obsolete and should be dropped in a follow-up PR.

**Comment by gctucker** [comment]
> A feature request: allow `--yaml-test-configs` and `--yaml-lab-configs` to be set from the settings file.
> 
> This will facilitate using the tools outside of the kernelci-core dir.

Yes, it will be implemented as a follow-up as well since those arguments are not set on a per-command basis.

**Comment by khilman** [comment]
OK, sounds good.  I have no problems with the above things getting updated in follow-up PRs.

**Comment by gctucker** [comment]
Erm, sorry for the noise - I was checking the converted format of the Markdown documentation on GitHub...

**Comment by gctucker** [comment]
Rendered version on the incoming branch: https://github.com/gctucker/kernelci-core/blob/T23210-settings-file/doc/settings.md

**Comment by gctucker** [comment]
Tested OK on staging and manually.

**Pull request merged**
