### PR TITLE
Add snippet.py, modify build.py

### PR DESCRIPTION
**Pull request by bygf**
Import snippet.py in build.py

### CODE REVIEW

**Review by gctucker — COMMENTED** [review]
What is this about?

**Comment by gctucker** [comment]
@bygf Hello, is this some kind of experiment you were doing?  Or are you working on something to actually merge in `main`?

**Comment by gctucker** [comment]
@bygf Hello, if there's no reply by the end of this week we'll have to close it I'm afraid.

**Comment by nuclearcat** [comment]
I guess as no answer received, i'm closing this PR

**Pull request closed without merging**
