### PR TITLE
build-configs-cip: Use cip-kernel-configs for kernels (5.10.y-cip, 4.4.y-cip)

### PR DESCRIPTION
**Pull request by aliceinwire**
Also add Riscv configuration for 5.10.y-cip

Signed-off-by: Alice Ferrazzi <alice.ferrazzi@miraclelinux.com>

### CODE REVIEW

**Comment by patersonc** [comment]
Thank you @aliceinwire 

Should we also do the same for 4.4.y-cip?

**Comment by aliceinwire** [comment]
> Thank you @aliceinwire
> 
> Should we also do the same for 4.4.y-cip?

ok, I will update this PR. Thanks

**Comment by aliceinwire** [comment]
@nuclearcat can you check and eventually merge this?
I already started the tests with staging https://staging.kernelci.org/job/

**Review by nuclearcat — APPROVED** [review]
LGTM

**Pull request merged**
