### PR TITLE
Fix osnoise and timerlat rt-tests

### PR DESCRIPTION
**Pull request by musamaanjum**
I've removed a step at execution time and added rtla package which is needed for execution.

### CODE REVIEW

**Comment by musamaanjum** [comment]
@laura-nao @nuclearcat I need to generate the rt-bookworm rootfs. I think we have some job in github to generate that rootfs and upload to storage? Can you please paste steps to that here? Maybe I don't have the right permissions. But I should get those permissions to avoid asking other to do this for me.

**Comment by laura-nao** [comment]
> @laura-nao @nuclearcat I need to generate the rt-bookworm rootfs. I think we have some job in github to generate that rootfs and upload to storage? Can you please paste steps to that here? Maybe I don't have the right permissions. But I should get those permissions to avoid asking other to do this for me.

I've used this action to build rootfs images for testing on staging (they end up in https://storage.staging.kernelci.org/rootfs/): https://github.com/kernelci/kernelci-core/actions/workflows/rootfs.yml - not sure about the required permissions though.

**Comment by nuclearcat** [comment]
@musamaanjum i added you, please try to generate rootfs image.

**Comment by nuclearcat** [comment]
P.S. Attention, first try to generate staging image and test with it, then if everything ok you can generate production image.

**Comment by musamaanjum** [comment]
The following error appears from a test run on 6th August:
```
+ ./rtla-osnoise.sh -d 60s -w hackbench
./rtla-osnoise.sh: 35: rtla: not found
/lava-15080299/0/tests/0_rt-tests-rtla-osnoise/automated/linux/rtla/output/results/bgcmd/bg_run.sh: line 4: hackbench: command not found
```

I've confirmed rtla and hackbench are installed in the rootfs. There was staging-skip on the PR on that day. So the old rootfs have been used for this run. Let's wait for an updated run with the correct rootfs.

**Comment by nuclearcat** [comment]
@musamaanjum any updates on this?

**Comment by musamaanjum** [comment]
> @musamaanjum any updates on this?

@nuclearcat the latest status is on sister PR: https://github.com/kernelci/kernelci-pipeline/pull/700

**Comment by musamaanjum** [comment]
Rebased the PR

**Review by pawiecz — APPROVED** [review]
LGTM

Verified together with https://github.com/kernelci/kernelci-pipeline/pull/700 [(details)](https://github.com/kernelci/kernelci-pipeline/pull/700#pullrequestreview-2264126199)

**Comment by musamaanjum** [comment]
I've collected the results on https://github.com/kernelci/kernelci-project/issues/439 and fix issues under this ticket. Overall, 3/11 tests have issues in their executor script in https://github.com/Linaro/test-definitions.

**Pull request merged**
