### PR TITLE
Runtime config

### LINKED ISSUE #1726: `kernelci.config.lab` reworked as `kernelci.config.runtime`
The first step in reworking `Lab` into `Runtime` is to move the `kernelci.config.lab` as `kernelci.config.runtime` and update the YAML configurations to be more generic.  There is already a lab type field which can be used to differentiate LAVA from Kubernetes and shell etc. so in theory there might not be a lot of rework needed.  One particular thing to consider is to move the runtime-specific parameters to a `params` dictionary so the main attributes are common for all Runtime implementations.  For example, maybe we can make the LAVA lab priority config just plain parameters since the logic has been moved to the main part of the code?

- [x] `kernelci.config.lab` renamed to `kernelci.config.runtime`
- [x] Runtime config objects consolidated if required
- [x] unit tests updated accordingly and passing
- [x] verified on staging

### PR DESCRIPTION
**Pull request by gctucker**
Rename `kernelci.config.lab` as `kernelci.config.runtime`.  Update all the code and unit tests accordingly.

Fixes #1726

### CODE REVIEW

**Comment by nuclearcat** [comment]
I am not sure if it is relevant to this commit, but looks like staging is broken:
https://bot.staging.kernelci.org/job/kernel-build-trigger/2063/console
I think relevant part of log is:
```
+ mkdir -p /data/workspace/bot.staging.kernelci.org/build-trigger/workspace/kernel-build-trigger__2/labs
[Pipeline] sh
+ kci_test list_labs
[Pipeline] }
[Pipeline] // stage
[Pipeline] dir
Running in /data/workspace/bot.staging.kernelci.org/build-trigger/workspace/kernel-build-trigger__2/labs
[Pipeline] {
[Pipeline] archiveArtifacts
Archiving artifacts
‘*.json’ doesn’t match anything
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
$ docker stop --time=1 aedd43ff7a70a86d37868e943fd6c65aaf4c0aa8eff5601cd6c6f79cbc6cff2b
```
list of labs are empty?

**Comment by gctucker** [comment]
Yes staging is going to be broken by this change until the corresponding changes in kernelci-jenkins are pushed.  Likewise for kernelci-pipeline.

**Comment by gctucker** [comment]
Tested OK on staging Jenkins:
https://bot.staging.kernelci.org/job/gtucker/job/gtucker-kernel-build-trigger/6/console
https://bot.staging.kernelci.org/job/gtucker/job/lava-bisection/48/console
https://staging.kernelci.org/test/job/gtucker/branch/kernelci-staging/kernel/v6.2-rc5-45-g602e974895e5/

Looking for results with the new pipeline now.

**Comment by gctucker** [comment]
Tested OK with new API & Pipeline as per https://github.com/kernelci/kernelci-pipeline/pull/222

**Comment by nuclearcat** [comment]
LGTM, but i see there is recent updates, does it need more testing or it is trivial fixes?

**Comment by gctucker** [comment]
> LGTM, but i see there is recent updates, does it need more testing or it is trivial fixes?

I just rebased the branch today.  I think it's ready to be merged after today's production update.  Then we can merge the Jenkins ones later this week to and have it deployed next Monday if things go well.

**Comment by gctucker** [comment]
OK the production update happened yesterday and this has now all been tested so it's ready to be merged.

**Pull request merged**
