### PR TITLE
CHROMEOS build-configs-chromeos.yaml: Add Kernel 6.1 builds

### PR DESCRIPTION
**Pull request by nuclearcat**
Update and add to build variants Kernel 6.1 as it is new LTS, and possible target for future uprevs.

Signed-off-by: Denys Fedoryshchenko <denys.f@collabora.com>

### CODE REVIEW

**Comment by nuclearcat** [comment]
Many Chromebooks just failing to boot, need to investigate reasons: https://chromeos.kernelci.org/test/job/kernelci/branch/chromeos-stable/kernel/chromeos-stable-20230121.1/

**Comment by nuclearcat** [comment]
Which is actually very strange, because single stage boot works fine:
https://lava.collabora.dev/scheduler/job/8812476
And dual stage with same kernel fails to boot second kernel:
https://lava.collabora.dev/scheduler/job/8812783

**Comment by mgalka** [comment]
@nuclearcat Is my impression right that this is still work in progress? If it's the case, please convert the PR to draft.

**Comment by nuclearcat** [comment]
It was supposed to go test phase, but turned out kernel 6.1 compiled with clang doesnt boot on many devices.
https://github.com/kernelci/kernelci-project/issues/166

**Comment by nuclearcat** [comment]
Turned out regressions are real kernel bug.
Otherwise 6.1 works fine: https://chromeos.kernelci.org/build/kernelci/branch/chromeos-stable/kernel/chromeos-stable-20230126.0/

**Review by mgalka — APPROVED** [review]

**Pull request merged**
