### PR TITLE
K8s build

### PR DESCRIPTION
**Pull request by broonie**

### CODE REVIEW

**Comment by gctucker** [comment]
How about this, to fix pycodestyle and maybe simplify the syntax a bit?
```diff
diff --git a/kernelci/k8s.py b/kernelci/k8s.py
index 0b048c8c2d2e..637e0f323c97 100644
--- a/kernelci/k8s.py
+++ b/kernelci/k8s.py
@@ -159,14 +159,13 @@ class k8s:
         else:
             fetch_template = "build-fetch-tar.jinja2"
 
-        if not in job_dict['spec']['template']['spec'] 'initContainers':
-            job_dict['spec']['template']['spec']['initContainers'] = []
+        init_containers = job_dict['spec']['template']['spec'].setdefault(
+            'initContainers', []
+        )
         template = env.get_template(fetch_template)
         fetch_yaml = template.render(params)
         fetch_dict = yaml.safe_load(fetch_yaml)
-        job_dict['spec']['template']['spec']['initContainers'] =
-            + job_dict['spec']['template']['spec']['initContainers']
-            + fetch_dict
+        init_containers.extend(fetch_dict)
 
         # Everything ready, dump a copy if requested and submit
         if (outdir):
```

**Comment by gctucker** [comment]
Actually, is `fetch_dict` really a dict and `init_containers` a list?  You can't add those two things together.  If it's a dict, then setdefault() can be passed an empty dict `{}` and then you can do `init_containers.update(fetch_dict)` to merge them together.

**Comment by gctucker** [comment]
@broonie Please rebase now that #873 has been merged.

**Comment by gctucker** [comment]
Adding `staging-skip` since this is causing some exceptions on staging:
```
+ ./kci_build check_new_commit --build-config=stable-5.14 --storage=http://storage.staging.kernelci.org
Traceback (most recent call last):
  File "/data/workspace/bot.staging.kernelci.org/build-trigger/workspace/kernel-build-trigger/kernelci-core/./kci_build", line 26, in <module>
    import kernelci.k8s
  File "/data/workspace/bot.staging.kernelci.org/build-trigger/workspace/kernel-build-trigger/kernelci-core/kernelci/k8s.py", line 18, in <module>
    import pygit2
ModuleNotFoundError: No module named 'pygit2'
```
It looks like the k8s Docker image needs to be rebuilt with the updated requirements.txt.

**Comment by broonie** [comment]
initContainers is a list of dicts, we're trying to add a new list element which is a dict to the end of the ordered list of initContainers.

**Comment by gctucker** [comment]
Right, so to add just one element you need to use `.append()`.

**Comment by gctucker** [comment]
I've deleted the k8s Docker image on staging to ensure it gets rebuilt from scratch in the next job.  I guess the change in requirements.txt wasn't seen by Docker.  So we should be able to remove the skip label now.

**Comment by gctucker** [comment]
There's still a problem with missing `pygit2`, I think it needs to be added to `setup.py`.  It's an issue that the dependencies are listed in two places, however I'm not sure what the best solution for that is.  Loading requirements.txt in setup.py isn't the intended way to use it, maybe we should just drop requirements.txt and rely solely on setup.py.  The current situation isn't ideal either as having to maintain 2 lists of dependencies is bound to cause issues again in the future.

See the related docs about that: https://packaging.python.org/discussions/install-requires-vs-requirements/#requirements-files

**Comment by aliceinwire** [comment]
@broonie any update on this?

**Comment by gctucker** [comment]
I believe this will be deprecated before being merged with the new API & pipeline, but maybe there are some ideas we could reuse.

**Comment by mgalka** [comment]
New API is going to have this feature implemented.

**Pull request closed without merging**
