### PR TITLE
Clang: Dockerfile: add arm32 binutils

### PR DESCRIPTION
**Pull request by nickdesaulniers**

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
Should fix errors like:
http://staging-storage.kernelci.org/next-clang/master/next-20190508/arm/am200epdkit_defconfig/clang-8/build.log

**Comment by mattface** [comment]
Was a duplicate of https://github.com/kernelci/kernelci-core/pull/66 but lets use this one instead :)

**Comment by nickdesaulniers** [comment]
sorry, I should have checked pre-existing PRs

**Comment by gctucker** [comment]
That worked: https://staging.kernelci.org/build/id/5cd53d8ccf3a0f62b7388326/

**Comment by gctucker** [comment]
@nickdesaulniers It would have been nice to explain a bit more why this was needed in the commit message, but that's OK.

**Pull request merged**
