### PR TITLE
templates: update kselftest subset parameters

### PR DESCRIPTION
**Pull request by alexandrasp**
this commit changes variable names according used in the linaro's test definitions.

Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>

### CODE REVIEW

**Comment by alexandrasp** [comment]
Tested OK on staging:

- https://staging.kernelci.org/test/plan/id/60194044cccbed9f7281639c/
- https://storage.staging.kernelci.org/kernelci/staging-next/staging-next-20210202.1/arm64/defconfig+kselftest/gcc-8/lab-collabora/kselftest-lib-hip07-d05.html

**Comment by gctucker** [comment]
Yep, and here's the corresponding LAVA job definition:
https://lava.collabora.co.uk/scheduler/job/3159982/definition
```yaml

    - repository: https://github.com/kernelci/test-definitions.git
      from: git
      revision: staging.kernelci.org
      path: automated/linux/kselftest/kselftest.yaml
      name: kselftest-lib
      parameters:
        TESTPROG_URL: http://storage.staging.kernelci.org/kernelci/staging-next/staging-next-20210202.1/arm64/defconfig+kselftest/gcc-8/kselftest.tar.xz
        SKIPFILE: skipfile-lkft.yaml
        TST_CMDFILES: lib
        TST_CASENAME:
```

**Comment by gctucker** [comment]
@alexandrasp There's a problem with your SoB trailer:

> Signed-off-by: Alexandra alexandra@arch.localhost

Please update your git config to use your `@collabora.com` address.

**Comment by gctucker** [comment]
Also, this PR depends on https://github.com/kernelci/test-definitions/pull/5.

**Comment by gctucker** [comment]
OK I've updated the test-definitions main branch in the kernelci fork, and it worked again with this resubmitted LAVA job:
https://lava.collabora.co.uk/results/3166649.

**Review by gctucker — APPROVED** [review]

**Pull request merged**
