### PR TITLE
Coccinelle+Cvehound

### PR DESCRIPTION
**Pull request by evdenis**
Add docker images for running coccinelle and cvehound.

Depends on #811

### CODE REVIEW

**Comment by gctucker** [comment]
There is an issue with Docker image builds on staging, as the `FROM` line needs to be changed to use `kernelc/staging-build-base`.  This is something to fix in a separate PR.  We can work around it by hand in the meantime, but it would be better to fix it properly so the automated jobs build the images as expected both on staging and production.

I guess one way to do this is to have an Docker variable to be able to override the `FROM` value.

**Comment by evdenis** [comment]
@gctucker Do you mean `kernelci-staging/build-base` or `kernelci/staging-build-base`?

**Comment by evdenis** [comment]
Firsh one as simple as reusing -t argument in build-and-push.sh:
```diff
diff --git a/config/docker/build-and-push.sh b/config/docker/build-and-push.sh
index 0b6ee2692a1c..6d4b48b8f4a7 100755
--- a/config/docker/build-and-push.sh
+++ b/config/docker/build-and-push.sh
@@ -75,7 +75,7 @@ docker_push() {
 docker_build_and_tag() {
   tag=${tag_px}$2
   echo_build $tag
-  docker build ${quiet} ${cache_args} $1 -t $tag
+  docker build --build-arg PREFIX=$tag ${quiet} ${cache_args} $1 -t $tag
   if [ "x${push}" == "xtrue" ]
   then
     docker_push $tag
diff --git a/config/docker/build-k8s/Dockerfile b/config/docker/build-k8s/Dockerfile
index 0df9824dfcea..5940b98be358 100644
--- a/config/docker/build-k8s/Dockerfile
+++ b/config/docker/build-k8s/Dockerfile
@@ -1,7 +1,8 @@
 #
 # Container to drive Kubernetes cluster from KernelCI
 #
-FROM kernelci/build-base
+ARG PREFIX=kernelci
+FROM ${PREFIX}/build-base
 MAINTAINER "Kevin Hilman <khilmnan@baylibre.com>"
```

**Comment by gctucker** [comment]
Images built on staging and pushed to the Docker hub:
https://hub.docker.com/repository/docker/kernelci/staging-cvehound
https://hub.docker.com/repository/docker/kernelci/staging-coccinelle

@evdenis Please confirm they are OK and we can merge this too.

**Comment by evdenis** [comment]
Please, rebuild the cvehound container. I pushed a single fix https://github.com/evdenis/cvehound/commit/010b768e5209bdb6f2aacbcb0fab266437662c97 Everything else works as expected. Thanks!

**Pull request merged**
