### PR TITLE
Build kselftest

### PR DESCRIPTION
**Pull request by pawiecz**
This patch is the initial introduction of kselftest. Further changes will follow as patches to job templates and pipeline configuration.

### CODE REVIEW

**Comment by nuclearcat** [comment]
```
Created /tmp/kci/linux/tools/testing/selftests/kselftest_install/kselftest-packages/kselftest.tar.gz
```
https://staging.kernelci.org:9000/viewer?node_id=65dc58dab1747c6008dc73f8

I think you just need to add command to copy kselftest to artifacts directory and it will work

**Comment by pawiecz** [comment]
Previous version of the PR missed `kselftest-packages` directory from the relative path

**Comment by pawiecz** [comment]
I should've checked logs more thoroughly @nuclearcat sorry for the inconvenience it caused

**Comment by pawiecz** [comment]
Looks like build finally works: https://staging.kernelci.org:9000/node/65dcd4d94c0de711cd4a3af8

**Review by nuclearcat — APPROVED** [review]
LGTM, works on staging

**Pull request merged**
