### PR TITLE
rootfs-configs: Trogdor: Add Adreno 630 and Venus-5.2 firmwares

### PR DESCRIPTION
**Pull request by kholk**
This patchset adds the required firmwares for GPU and hardware enc/decoder, necessary to run certain tests on Qualcomm sc7180-trogdor

### CODE REVIEW

**Comment by gctucker** [comment]
Adding `staging-skip` label as this is conflicting with #903 to move from buster-igt to bullseye-igt.  Once #902 and #903 have been merged, this will need to be rebased by adding the firmware files to the bullseye-igt image instead.

**Comment by aliceinwire** [comment]
@kholk #902 and #903 as been merged. 
can you rebase this?

**Comment by kholk** [comment]
@aliceinwire the rebase is done, sorry for the delay.

**Comment by nuclearcat** [comment]
Is there any tests enabled that can use this firmware? So we can test it on staging

**Comment by nuclearcat** [comment]
Update: ss trogdor have some issues with networking and initramfs, i am in progress of fixing that and then enabling IGT tests, so we can test this firmware patches.

**Comment by nuclearcat** [comment]
I tried to add firmware in rootfs and run tests mentioned in https://github.com/kholk/kernelci-core/commits/v4l2-igt , it looks like something is still missing (maybe some kernel option?):
```
IGT-Version: 1.26-gf2f5153 (aarch64) (Linux: 6.0.14 aarch64)
<6>[   17.702816] asix 1-1.3:1.0 enx006f00030a6f: renamed from eth0
Test requirement not met in function drm_open_driver, file ../li<14>[   17.713766] [IGT] msm_submit: exiting, ret=77
```

**Comment by nuclearcat** [comment]
Even things are complicated at trogdor (due racy serial), here is visible firmware is loading:
Commit: https://github.com/kernelci/kernelci-core/pull/852/commits/05102f9258cf9e7a52514a84e1316d69f94841f9
Log: https://storage.staging.kernelci.org/kernelci/staging-stable/staging-stable-20221222.0/arm64/defconfig+arm64-chromebook+crypto/gcc-10/lab-collabora/igt-gpu-msm-sc7180-trogdor-lazor-limozeen.html
```
 1376 08:28:47.944822  <6>[    3.416392] msm ae00000.mdss: [drm:adreno_request_fw] loaded qcom/a630_sqe.fw from new location
 1377 08:28:47.954831  <6>[    3.425721] msm ae00000.mdss: [drm:adreno_request_fw] loaded qcom/a630_gmu.bin from new location
```

**Pull request merged**
