### PR TITLE
dockerfiles: upgrade to clang-9, enable more arch's

### LINKED ISSUE #103: [clang] additional trees/branches
per our discussion on the mailing list, I think it would be worthwhile to expand testing coverage of defconfigs from -next to mainline, and stable for 4.19, 4.14, 4.9, and maybe 4.4 (we do support arm64 and x86_64 defconfigs back to 4.4).

### LINKED ISSUE #105: [clang] additional arches
we should be able to build arm64, arm, x86_64, ppc32le, and ppc64le with clang-9.

### LINKED ISSUE #238: please add clang-9 builds
forked from https://github.com/kernelci/kernelci-core/issues/103#issuecomment-551915209.

IIRC, there were clang-9 images setup.  clang-9 fixes some warnings that were incorrectly emitted.

### PR DESCRIPTION
**Pull request by nickdesaulniers**
Also removes clang-8 support.

The configs we're currently building are https://github.com/ClangBuiltLinux/continuous-integration/blob/a85e3e44c2570847e22ad8f92f317c2b007c4517/driver.sh#L47-L167.

This simply adds 4 32b ARM (v5, v6, v7, allmodconfig), and x86_64 builds.

Fixes #238
Fixes #105
Fixes #103

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
I'm not sure if there's a way I can test this locally?

```sh
$ sudo docker build jenkins/dockerfiles/clang-9/
```
seems to succeed, and
```sh
➜  kernelci-core git:(clang-9) ✗ sudo docker run 6653358fa8e5 which clang-9
/usr/bin/clang-9
➜  kernelci-core git:(clang-9) ✗ sudo docker run 6653358fa8e5 which as     
/usr/bin/as
```
seems to show we have clang and binutils installed.

**Comment by nickdesaulniers** [comment]
cc @nathanchance for help with Docker experience.

**Comment by gctucker** [comment]
Thanks, LGTM.  I'm building the image to have it used by staging.kernelci.org which will be a good integration test.

**Comment by gctucker** [comment]
It seems to have worked fine, except the `arm64 defconfig` build wasn't triggered but that was as per the config filter defined for staging.kernelci.org - I'll get another round with it enabled.

Meanwhile, here are the builds for arm and x86_64:
https://staging.kernelci.org/build/id/5e4f00c5bc8e9a946ca4cb46/
https://staging.kernelci.org/build/id/5e4efc312d51ff0787a4cb46/

**Comment by gctucker** [comment]
And here's an arm64 one now:
https://staging.kernelci.org/build/id/5e4f1ed71ae1fb6ddadc7378/

**Comment by gctucker** [comment]
The baseline tests are interesting, some are failing with gcc-8 but passing with clang-9:
https://staging.kernelci.org/test/job/kernelci/branch/staging.kernelci.org/kernel/staging-20200220.4/plan/baseline/

**Comment by gctucker** [comment]
> The baseline tests are interesting, some are failing with gcc-8 but passing with clang-9:
> https://staging.kernelci.org/test/job/kernelci/branch/staging.kernelci.org/kernel/staging-20200220.4/plan/baseline/

Actually that looks like a bug on the frontend (it's a new page), the boot log shows the same kernel panic with clang as it did with gcc.

**Comment by gctucker** [comment]
@nickdesaulniers Also please squash the 2 commits as `use * rather than & in build-configs.yaml` is a fix for the first one.

**Comment by gctucker** [comment]
> > The baseline tests are interesting, some are failing with gcc-8 but passing with clang-9:
> > https://staging.kernelci.org/test/job/kernelci/branch/staging.kernelci.org/kernel/staging-20200220.4/plan/baseline/
> 
> Actually that looks like a bug on the frontend (it's a new page), the boot log shows the same kernel panic with clang as it did with gcc.

OK that's because previous run were with clang-8, so there has never been a passing boot with clang-9 on these platforms hence no regression detected.  So that's all normal behaviour.  Previous runs show expected regressions with both clang-8 and gcc-8.

**Comment by gctucker** [comment]
Also I think you're not part of the recipients for the staging email reports, so here are some samples from the build and baseline ones:

```
kernelci/staging.kernelci.org build: 14 builds: 1 failed, 13 passed, 38 warnings (staging-20200220.4)

Full Build Summary: https://kernelci.org/build/kernelci/branch/staging.kernelci.org/kernel/staging-20200220.4/

Tree: kernelci
Branch: staging.kernelci.org
Git Describe: staging-20200220.4
Git Commit: 1da48b0a4ec2907c0ed9e25e4f446ec856960608
Git URL: https://github.com/kernelci/linux.git
Built: 7 unique architectures

Build Failure Detected:

arm64:
    defconfig+CONFIG_CPU_BIG_ENDIAN=y: (clang-9) FAIL

Warnings Detected:

arc:

arm64:
    defconfig (gcc-8): 1 warning
    defconfig (clang-9): 19 warnings
    defconfig (gcc-8): 1 warning

arm:
    multi_v7_defconfig (gcc-8): 4 warnings
    multi_v7_defconfig (clang-9): 7 warnings

[...]

--------------------------------------------------------------------------------
defconfig (arm64, clang-9) — PASS, 0 errors, 19 warnings, 0 section mismatches

Warnings:
    net/bluetooth/smp.c:2185:8: warning: variable 'passkey' is uninitialized when used here [-Wuninitialized]
    net/bluetooth/smp.c:2119:13: note: initialize the variable 'passkey' to silence this warning
    1 warning generated.
    fs/btrfs/volumes.c:7338:3: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    1 warning generated.
    drivers/net/ethernet/mellanox/mlx5/core/diag/rsc_dump.h:4:9: warning: '__MLX5_RSC_DUMP_H' is used as a header guard here, followed by #define of a different macro [-Wheader-guard]
    1 warning generated.
    drivers/net/ethernet/mellanox/mlx5/core/diag/rsc_dump.h:4:9: warning: '__MLX5_RSC_DUMP_H' is used as a header guard here, followed by #define of a different macro [-Wheader-guard]
    1 warning generated.
    drivers/net/ethernet/mellanox/mlx5/core/diag/rsc_dump.h:4:9: warning: '__MLX5_RSC_DUMP_H' is used as a header guard here, followed by #define of a different macro [-Wheader-guard]
    1 warning generated.
    drivers/net/ethernet/mellanox/mlx5/core/diag/rsc_dump.h:4:9: warning: '__MLX5_RSC_DUMP_H' is used as a header guard here, followed by #define of a different macro [-Wheader-guard]
    1 warning generated.
    drivers/net/ethernet/mellanox/mlx5/core/diag/rsc_dump.h:4:9: warning: '__MLX5_RSC_DUMP_H' is used as a header guard here, followed by #define of a different macro [-Wheader-guard]
    1 warning generated.
    drivers/net/ethernet/mellanox/mlx5/core/diag/rsc_dump.h:4:9: warning: '__MLX5_RSC_DUMP_H' is used as a header guard here, followed by #define of a different macro [-Wheader-guard]
    1 warning generated.
    drivers/net/ethernet/mellanox/mlx5/core/diag/rsc_dump.h:4:9: warning: '__MLX5_RSC_DUMP_H' is used as a header guard here, followed by #define of a different macro [-Wheader-guard]
    1 warning generated.
```

```
run | platform                     | arch   | lab           | compiler | defconfig                    | results
----+------------------------------+--------+---------------+----------+------------------------------+--------
[...]
11  | bcm2837-rpi-3-b              | arm64  | lab-baylibre  | clang-9  | defconfig                    | 4/5    
12  | bcm2837-rpi-3-b              | arm64  | lab-baylibre  | gcc-8    | defconfig                    | 4/5    
13  | exynos4412-odroidx2          | arm    | lab-collabora | clang-9  | multi_v7_defconfig           | 4/5    
14  | exynos4412-odroidx2          | arm    | lab-collabora | gcc-8    | multi_v7_defconfig           | 4/5    
15  | exynos5422-odroidxu3         | arm    | lab-collabora | clang-9  | multi_v7_defconfig           | 5/5    
16  | exynos5422-odroidxu3         | arm    | lab-collabora | gcc-8    | multi_v7_defconfig           | 5/5    
17  | hifive-unleashed-a00         | riscv  | lab-baylibre  | gcc-8    | defconfig                    | 1/1    
18  | hip07-d05                    | arm64  | lab-collabora | clang-9  | defconfig                    | 3/5    
19  | hip07-d05                    | arm64  | lab-collabora | gcc-8    | defconfig                    | 3/5    
20  | imx6q-sabrelite              | arm    | lab-baylibre  | clang-9  | multi_v7_defconfig           | 5/5    
21  | imx6q-sabrelite              | arm    | lab-collabora | clang-9  | multi_v7_defconfig           | 5/5    
22  | imx6q-sabrelite              | arm    | lab-baylibre  | gcc-8    | multi_v7_defconfig           | 5/5    
23  | imx6q-sabrelite              | arm    | lab-collabora | gcc-8    | multi_v7_defconfig           | 5/5    
[...]
138 | sun8i-h3-libretech-all-h3-cc | arm    | lab-baylibre  | clang-9  | multi_v7_defconfig           | 0/1    
139 | sun8i-h3-libretech-all-h3-cc | arm    | lab-baylibre  | gcc-8    | multi_v7_defconfig           | 0/1    
140 | tegra124-jetson-tk1          | arm    | lab-baylibre  | clang-9  | multi_v7_defconfig           | 5/5    
141 | tegra124-jetson-tk1          | arm    | lab-collabora | clang-9  | multi_v7_defconfig           | 5/5    
142 | tegra124-jetson-tk1          | arm    | lab-baylibre  | gcc-8    | multi_v7_defconfig           | 5/5    
143 | tegra124-jetson-tk1          | arm    | lab-collabora | gcc-8    | multi_v7_defconfig           | 5/5    
144 | tegra124-nyan-big            | arm    | lab-collabora | clang-9  | multi_v7_defconfig           | 5/5    
145 | tegra124-nyan-big            | arm    | lab-collabora | gcc-8    | multi_v7_defconfig           | 5/5    
```

**Comment by nickdesaulniers** [comment]
> Also please squash the 2 commits as use * rather than & in build-configs.yaml is a fix for the first one.

IIRC, github should give you the option when merging a PR; I think there's a little drop down near the big green merge button, and you can say "squash and merge."

>     defconfig+CONFIG_CPU_BIG_ENDIAN=y: (clang-9) FAIL

Ah, I should probably disable that for now.

**Comment by gctucker** [comment]
> > Also please squash the 2 commits as use * rather than & in build-configs.yaml is a fix for the first one.
> 
> IIRC, github should give you the option when merging a PR; I think there's a little drop down near the big green merge button, and you can say "squash and merge."

Yes, just that I've only enabled "rebase and merge" to avoid abuse when the history is useful and gets squashed at merge time.  So it's at the discretion of each contributor to squash things or not, it's only a `git push --force` away.

But yes I can still enable squash merge just for this PR.

> > ```
> > defconfig+CONFIG_CPU_BIG_ENDIAN=y: (clang-9) FAIL
> > ```
> 
> Ah, I should probably disable that for now.

Actually it's only enabled on staging, precisely because there's a known problem with using config fragments with Clang builds.  The intent was to fix it on staging but nobody has found the time to do that yet, and it didn't appear to be that urgent either.  So I don't believe you need to change anything in this PR in this respect, big-endian is not currently built with clang-8 either in production.

The issue is that the `merge_config.sh` kernel script calls `make` without propagating variables such as `HOSTCC`, creating an implicit dependency on `gcc`.  The Docker images we use have only `clang` and as such, it fails.  Installing `gcc` there is not what we want, and in fact we've tried and it wasn't enough to fix the problem.  I also tried to fix it in the kernel `Makefile` by using `HOSTCC ?= gcc` as this would have worked using environment variables but it wasn't accepted as it could have broken other people's build systems that rely on current behaviour.

So, we either need to have a custom function in `kernelci-core` to generate the config file rather than rely on `merge_config.sh` or a special Makefile that wraps `merge_config.sh` as a way to have variables such as `HOSTCC` propagated to sub-makes.  It's a _bit_ over-complicated...

**Pull request merged**
