### PR TITLE
add UEFI tests

### PR DESCRIPTION
**Pull request by gctucker**
This is a fixup PR for #100 to make the templates and test config more maintainable.

### CODE REVIEW

**Comment by roxell** [comment]
LGTM

**Comment by gctucker** [comment]
@roxell It all seems to be working now with the latest UEFI firmware, including the new variant for x86-mixed:
https://lkft.validation.linaro.org/scheduler/alljobs?length=25&search=uefi#table
https://lkft.validation.linaro.org/scheduler/job/883914

So now I'll clean up this PR and copy the UEFI binaries to storage.kernelci.org and get another round of tests.  If that works and you approve the PR then it looks like it'll be ready to be merged.

**Comment by gctucker** [comment]
OK that seems to be working as expected:
https://lkft.validation.linaro.org/scheduler/alljobs?length=10&search=uefi&page=1#table
and a couple of examples:
https://lkft.validation.linaro.org/scheduler/job/884888
https://lkft.validation.linaro.org/scheduler/job/884884

@roxell Please confirm if this is all fine before we merge it (I can't add you to the reviewers for some reason...).

**Comment by roxell** [comment]
LGTM

**Pull request merged**
