### PR TITLE
Riscv

### PR DESCRIPTION
**Pull request by montjoie**
This pull request add support for having a riscV debian rootfs.

### CODE REVIEW

**Review by khilman — CHANGES_REQUESTED** [review]
This is a duplicate of: `https://github.com/kernelci/kernelci-core/pull/1401`
Maybe you should rebase on my PR

**Review by khilman — CHANGES_REQUESTED** [review]
This is a duplicate of: https://github.com/kernelci/kernelci-core/pull/1398

**Review by khilman — APPROVED** [review]

**Review by khilman — APPROVED** [review]

**Review by khilman — APPROVED** [review]

**Comment by khilman** [comment]
@mgalka can you have a look at this and let us know what else is needed to get sid-based rootfs generation going for riscv?

**Comment by mgalka** [comment]
Rootfs build OK on staging.
https://bot.staging.kernelci.org/job/rootfs-builder/465

**Review by mgalka — APPROVED** [review]

**Pull request merged**
