### PR TITLE
Add buster-cros-ec configs

### PR DESCRIPTION
**Pull request by eballetbo**
Include buster-cros-ec rootfs configurations.

Signed-off-by: Enric Balletbo i Serra <enric.balletbo@collabora.com>

### CODE REVIEW

**Comment by gctucker** [comment]
Please rebase to clear the Travis CI errors that have now been fixed on master.

**Comment by gctucker** [comment]
Built OK on staging: https://storage.kernelci.org/images/rootfs/debian/buster-cros-ec/20200410.0/

Updating the URLs on staging now to use these rootfs images in the next round.

**Comment by gctucker** [comment]
Tested OK on staging:
https://lava.collabora.co.uk/scheduler/job/2411085
https://staging.kernelci.org/test/plan/id/5ec3a3edc6449a9c8b79f2b9/
@eballetbo Please check that the results look OK.

**Comment by eballetbo** [comment]
Results are the expected, thanks.

**Pull request merged**
