### PR TITLE
build-configs.yaml: enable i386 for clang-10 and clang-11 of next

### PR DESCRIPTION
**Pull request by wangmingyu84**
Signed-off-by: Wang Mingyu <wangmy@cn.fujitsu.com>

### CODE REVIEW

**Comment by gctucker** [comment]
Tested locally, from within a `kernelci-core` checkout and a `linux` checkout inside it.

First, create this local config file in the same directory, called `kernelci.conf.i386-clang`:
```ini
[kci_build]
kdir: linux
build_env: clang-10
j: 4
arch: i386
output: linux/build-i386-clang-10
verbose: true
install: true
```
Then run these commands using Docker:
```
$ docker run -it -v $PWD:/root/kernelci-core kernelci/build-clang-10 /bin/bash
# cd /root/kernelci-core
# ./kci_build --settings=kernelci.conf.i386-clang init_bmeta --build-config=next
# ./kci_build --settings=kernelci.conf.i386-clang make_config --defconfig=i386_defconfig
# ./kci_build --settings=kernelci.conf.i386-clang make_kernel
# ./kci_build --settings=kernelci.conf.i386-clang make_modules
```

The same thing can be done with `clang-11`, the build worked fine with both versions.

Here's the generated meta-data in `linux/build-i386-clang-10/bmeta.json`:
```json
{
    "build": {
        "duration": 1460.7438714504242,
        "status": "PASS"
    },
    "environment": {
        "arch": "i386",
        "compiler": "clang",
        "compiler_version": "10",
        "compiler_version_full": "Debian clang version 10.0.1-++20200708124224+ef32c611aa2-1~exp1~20200707224822.188 ",
        "cross_compile": "",
        "cross_compile_compat": "",
        "make_opts": {
            "KBUILD_BUILD_USER": "KernelCI"
        },
        "name": "clang-10",
        "platform": {
            "uname": [
                "Linux",
                "d3a98bd1be61",
                "4.19.0-12-amd64",
                "#1 SMP Debian 4.19.152-1 (2020-10-18)",
                "x86_64",
                ""
            ]
        },
        "use_ccache": true
    },
    "kernel": {
        "defconfig": "i386_defconfig",
        "defconfig_extras": [],
        "defconfig_full": "i386_defconfig",
        "image": "bzImage",
        "vmlinux_bss_size": 577536,
        "vmlinux_data_size": 1811968,
        "vmlinux_file_size": 26187000,
        "vmlinux_text_size": 11638005
    },
    "revision": {
        "branch": "master",
        "commit": "950c3769192512118a87432dd42e71c5241dbd10",
        "describe": "v5.10-rc7-223-g950c37691925",
        "describe_v": "v5.10-rc7-223-g950c37691925",
        "tree": "next",
        "url": "https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git"
    }
}
```
That shows the i386 builds worked as expected with Clang.

**Comment by gctucker** [comment]
Then to check whether the i386 Clang builds are included in the configuration for linux-next:
```
$ ./kci_build list_kernel_configs --build-config=next --kdir=linux | grep clang | grep i386
i386 allnoconfig clang-10
i386 i386_defconfig clang-11
i386 i386_defconfig clang-10
i386 allmodconfig clang-11
i386 allmodconfig clang-10
i386 allnoconfig clang-11
```
Then for mainline:
```
$ ./kci_build list_kernel_configs --build-config=mainline --kdir=linux | grep clang | grep i386
i386 i386_defconfig clang-10
i386 allmodconfig clang-10
i386 allnoconfig clang-10
```
so it looks like it's all fine.

**Comment by gctucker** [comment]
@nickdesaulniers Please check the comment above - does that look like the combinations of branches, defconfigs and Clang versions you're expecting for i386?

**Review by gctucker — APPROVED** [review]
Looks fine to me, just waiting confirmation that the build coverage is as expected.

**Comment by nickdesaulniers** [comment]
LGTM thanks @wangmingyu84 !! 🔥 (cc @nathanchance)

**Pull request merged**
