### PR TITLE
jenkins/buildroot-builder: add fragment

### PR DESCRIPTION
**Pull request by khilman**
Support addition fragments when building.  This will initially be used
to build the additional "baseline" fragment for bootrr.

Signed-off-by: Kevin Hilman <khilman@baylibre.com>

### CODE REVIEW

**Comment by khilman** [comment]
@gctucker We need this to start building the `baseline` version of buildroot.

**Comment by gctucker** [comment]
Ha, I know :)  Actually I did this today, which also uploads the rootfs files in a separate directory:
```diff
commit bcda118fa43ea36c38d3945f189fb3acc9717b5d (HEAD -> gtucker)
Author: Guillaume Tucker <guillaume.tucker@collabora.com>
Date:   Mon Jun 3 17:09:41 2019 +0100

    WIP buildroot-builder.sh: add variant argument

diff --git a/jenkins/buildroot-builder.sh b/jenkins/buildroot-builder.sh
index 5fbf592f4787..7c25271e8c0f 100755
--- a/jenkins/buildroot-builder.sh
+++ b/jenkins/buildroot-builder.sh
@@ -1,11 +1,13 @@
 #!/bin/bash
 env
 
-# Build 
-./configs/frags/build ${arch}
+variant=${1:-base}
+
+# Build
+./configs/frags/build ${arch} ${variant}
 
 # Publish
 set -x
-PUBLISH_PATH=images/rootfs/buildroot/$(git describe)/${arch}/base
+PUBLISH_PATH=images/rootfs/buildroot/$(git describe)/${arch}/${variant}
 ls -l output/images
 (cd output/images; push-source.py --token ${API_TOKEN} --api ${API} --publish_path ${PUBLISH_PATH} --file *)
```

**Comment by khilman** [comment]
You don't actually need this line:
`+variant=${1:-base}`
because the build script already includes `base`.  Other than, our changes (after my force push) are the same except for I use `frag` and use use `variant`

**Comment by gctucker** [comment]
@khilman I also use the `${variant}` variable in the path where the builds are uploaded.

**Comment by khilman** [comment]
@gctucker I do as well in the force-pushed version (after the original commit)

**Comment by khilman** [comment]
I'm going to drop this PR in favor of your patch above which will ensure proper uploads.

**Comment by gctucker** [comment]
The patch above has been added to #55.

**Pull request closed without merging**
