### PR TITLE
rootfs: add sid-kselftest and sid-ltp

### PR DESCRIPTION
**Pull request by montjoie**
Add 2 new rootfs for riscV.

Signed-off-by: Corentin Labbe <clabbe@baylibre.com>

### CODE REVIEW

**Comment by montjoie** [comment]
Note that this PR need https://github.com/kernelci/kernelci-core/pull/1478
And for running kselftest it miss a few package.
I will update it later

**Comment by mgalka** [comment]
@montjoie
I think, I don't fully understand if you're going to update the PR or do you plan to create another PR with the package update?

**Comment by montjoie** [comment]
I need to check, packages that was needed was for apt, which is finaly not needed since fullrootfs have it.
Let me verify tomorow that I miss nothing

**Comment by montjoie** [comment]
Everything is ok for me, and I have updated the commitlog which was really too short.

**Comment by mgalka** [comment]
Staging rootfs builds went OK

https://storage.staging.kernelci.org/images/rootfs/debian/sid-kselftest/20221213.1/riscv64/
https://storage.staging.kernelci.org/images/rootfs/debian/sid-ltp/20221213.0/

**Review by mgalka — APPROVED** [review]

**Pull request merged**
