### PR TITLE
build.jpl: enable --verbose kernel builds

### PR DESCRIPTION
**Pull request by gctucker**
Run kci_build build_kernel --verbose to have the full output stored in
the build log.

Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>

### CODE REVIEW

**Comment by mattface** [comment]
Will this cause an upsurge in the storage requirements?

**Comment by gctucker** [comment]
@khilman Here's a sample full build output:
http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/v5.2-rc3-25-g9ad5a74a1b7a/arm64/defconfig/gcc-8/build.log

@mattface It seems to be taking about 300~500KB per build, which is relatively small.  It varies across architectures and defconfigs, but taking the example of arm64 defconfig with gcc-8, the binaries are 25MB and the log is 330KB so that's an increase in storage space of 1.3%.

**Comment by mattface** [comment]
@gctucker Ok thats probably acceptable.

As log files are so compressible we should probably put storing them compressed onto the ever growing wishlist :)

**Comment by gctucker** [comment]
It makes it harder to read them though ;)

**Comment by mattface** [comment]
> It makes it harder to read them though ;)

Nothing nginx cant handle :D

**Comment by broonie** [comment]
LGTM.

**Comment by gctucker** [comment]
Sample build report, showing the compiler warnings as expected:
```
kernelci/staging.kernelci.org build: 9 builds: 0 failed, 9 passed, 88 warnings (v5.2-rc3-25-g9b36b029efa7)

Full Build Summary: https://staging.kernelci.org/build/kernelci/branch/staging.kernelci.org/kernel/v5.2-rc3-25-g9b36b029efa7/

Tree: kernelci
Branch: staging.kernelci.org
Git Describe: v5.2-rc3-25-g9b36b029efa7
Git Commit: 9b36b029efa799f588c0668a5d063fcc91ea9969
Git URL: https://github.com/kernelci/linux.git
Built: 6 unique architectures

Warnings Detected:

arc:

arm64:
    defconfig (clang-8): 42 warnings

arm:
    multi_v7_defconfig (clang-8): 42 warnings

mips:

riscv:
    rv32_defconfig (gcc-8): 4 warnings

x86_64:


Warnings summary:

    6    drivers/soc/rockchip/pm_domains.c:832:20: warning: shift count is negative [-Wshift-count-negative]
    6    drivers/soc/rockchip/pm_domains.c:820:21: warning: shift count is negative [-Wshift-count-negative]
    6    drivers/soc/rockchip/pm_domains.c:819:22: warning: shift count is negative [-Wshift-count-negative]
    6    drivers/soc/rockchip/pm_domains.c:818:22: warning: shift count is negative [-Wshift-count-negative]
    4    drivers/soc/rockchip/pm_domains.c:834:21: warning: shift count is negative [-Wshift-count-negative]
    4    drivers/soc/rockchip/pm_domains.c:833:21: warning: shift count is negative [-Wshift-count-negative]
    4    drivers/soc/rockchip/pm_domains.c:822:21: warning: shift count is negative [-Wshift-count-negative]
    4    drivers/soc/rockchip/pm_domains.c:821:21: warning: shift count is negative [-Wshift-count-negative]
    4    drivers/soc/rockchip/pm_domains.c:796:21: warning: shift count is negative [-Wshift-count-negative]
    4    drivers/soc/rockchip/pm_domains.c:795:21: warning: shift count is negative [-Wshift-count-negative]
    4    drivers/soc/rockchip/pm_domains.c:794:21: warning: shift count is negative [-Wshift-count-negative]
    4    drivers/soc/rockchip/pm_domains.c:793:22: warning: shift count is negative [-Wshift-count-negative]
    4    drivers/soc/rockchip/pm_domains.c:792:21: warning: shift count is negative [-Wshift-count-negative]
    4    drivers/soc/rockchip/pm_domains.c:791:21: warning: shift count is negative [-Wshift-count-negative]
    4    drivers/soc/rockchip/pm_domains.c:790:21: warning: shift count is negative [-Wshift-count-negative]
    4    drivers/soc/rockchip/pm_domains.c:789:21: warning: shift count is negative [-Wshift-count-negative]
    4    drivers/soc/rockchip/pm_domains.c:788:21: warning: shift count is negative [-Wshift-count-negative]
    4    drivers/soc/rockchip/pm_domains.c:752:21: warning: shift count is negative [-Wshift-count-negative]
    2    drivers/soc/rockchip/pm_domains.c:747:21: warning: shift count is negative [-Wshift-count-negative]
    2    <stdin>:830:2: warning: #warning syscall fstat64 not implemented [-Wcpp]
    2    <stdin>:1127:2: warning: #warning syscall fstatat64 not implemented [-Wcpp]
    2    41 warnings generated.

================================================================================

Detailed per-defconfig build reports:

--------------------------------------------------------------------------------
32r2el_defconfig (mips, gcc-8) — PASS, 0 errors, 0 warnings, 0 section mismatches

--------------------------------------------------------------------------------
defconfig (riscv, gcc-8) — PASS, 0 errors, 0 warnings, 0 section mismatches

--------------------------------------------------------------------------------
defconfig (arm64, gcc-8) — PASS, 0 errors, 0 warnings, 0 section mismatches

--------------------------------------------------------------------------------
defconfig (arm64, clang-8) — PASS, 0 errors, 42 warnings, 0 section mismatches

Warnings:
    drivers/soc/rockchip/pm_domains.c:747:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:752:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:752:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:788:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:788:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:789:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:789:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:790:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:790:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:791:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:791:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:792:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:792:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:793:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:793:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:794:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:794:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:795:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:795:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:796:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:796:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:818:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:818:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:818:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:819:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:819:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:819:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:820:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:820:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:820:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:821:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:821:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:822:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:822:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:832:20: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:832:20: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:832:20: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:833:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:833:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:834:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:834:21: warning: shift count is negative [-Wshift-count-negative]
    41 warnings generated.

--------------------------------------------------------------------------------
multi_v7_defconfig (arm, gcc-8) — PASS, 0 errors, 0 warnings, 0 section mismatches

--------------------------------------------------------------------------------
multi_v7_defconfig (arm, clang-8) — PASS, 0 errors, 42 warnings, 0 section mismatches

Warnings:
    drivers/soc/rockchip/pm_domains.c:747:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:752:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:752:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:788:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:788:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:789:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:789:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:790:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:790:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:791:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:791:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:792:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:792:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:793:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:793:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:794:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:794:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:795:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:795:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:796:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:796:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:818:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:818:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:818:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:819:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:819:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:819:22: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:820:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:820:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:820:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:821:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:821:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:822:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:822:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:832:20: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:832:20: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:832:20: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:833:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:833:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:834:21: warning: shift count is negative [-Wshift-count-negative]
    drivers/soc/rockchip/pm_domains.c:834:21: warning: shift count is negative [-Wshift-count-negative]
    41 warnings generated.

--------------------------------------------------------------------------------
nsim_hs_defconfig (arc, gcc-8) — PASS, 0 errors, 0 warnings, 0 section mismatches

--------------------------------------------------------------------------------
rv32_defconfig (riscv, gcc-8) — PASS, 0 errors, 4 warnings, 0 section mismatches

Warnings:
    <stdin>:830:2: warning: #warning syscall fstat64 not implemented [-Wcpp]
    <stdin>:1127:2: warning: #warning syscall fstatat64 not implemented [-Wcpp]
    <stdin>:830:2: warning: #warning syscall fstat64 not implemented [-Wcpp]
    <stdin>:1127:2: warning: #warning syscall fstatat64 not implemented [-Wcpp]

--------------------------------------------------------------------------------
x86_64_defconfig (x86_64, gcc-8) — PASS, 0 errors, 0 warnings, 0 section mismatches

---
For more info write to <info@kernelci.org>
```

**Pull request merged**
