### PR TITLE
CHROMEOS test-configs-chromeos: add tests for arcada

### PR DESCRIPTION
**Pull request by a-wai**
This is a `sarien` board, so we can use the same parameters here.

### CODE REVIEW

**Comment by a-wai** [comment]
Successfully tested: https://lava.collabora.dev/scheduler/device/dell-latitude-5300-8145U-arcada-cbg-0?recent_length=25&recent_search=cros-test_cros-tast

**Comment by nuclearcat** [comment]
Yes, i need to see it on dashboard first, for example i can't see arcada here:
https://chromeos.kernelci.org/test/job/stable/branch/linux-6.1.y/kernel/v6.1.67/plan/cros-tast-kernel/

**Comment by nuclearcat** [comment]
Please rebase (after merging skyrim seems conflict)

**Comment by a-wai** [comment]
Rebase done

**Review by nuclearcat — APPROVED** [review]
THis particular chromebook have issues, but tests are starting: https://storage.chromeos.kernelci.org/stable/linux-6.6.y/v6.6.9/x86_64/cros---chromeos-6.6-x86_64-chromeos-intel-pineview.flavour.config+x86-chromebook+CONFIG_MODULE_COMPRESS_GZIP=n/clang-17/lab-collabora/cros-tast-kernel-dell-latitude-5300-8145U-arcada_chromeos.html

**Pull request merged**
