### PR TITLE
docker/api: Update recipe

### PR DESCRIPTION
**Pull request by nuclearcat**
Unfortunately pyproject.toml is not up to date in kernelci-api, so fall back to recipe similar as we are using on staging.

### CODE REVIEW

**Comment by JenySadadia** [comment]
Instead of these changes, shouldn't we consider updating `pyproject.toml` for API?

**Comment by nuclearcat** [comment]
For sure, just i had to fix it asap, as bug we are fixing became stale and i found out that reason is our current staging system, and as @pawiecz completed most of work, i just did quick workaround. We might discuss this topic during our today weekly, when it should be done.

**Comment by nuclearcat** [comment]
I opened issue https://github.com/kernelci/kernelci-api/issues/469

**Comment by JenySadadia** [comment]
> I opened issue [kernelci/kernelci-api#469](https://github.com/kernelci/kernelci-api/issues/469)

I'll try to resolve this asap.

**Comment by JenySadadia** [comment]
> I think we can merge this one, and then improve API deployment recipe when pyproject.toml is ready, so we dont do that in rush and dont miss deadlines, because next week i plan to deploy api/pipeline in production k8s. @JenySadadia whats your opinion in that?

https://github.com/kernelci/kernelci-api/pull/473 is ready for testing. I'd suggest directly merging it if it's tested OK instead of merging these interim changes and discarding them later.

**Comment by JenySadadia** [comment]
@nuclearcat I am testing https://github.com/kernelci/kernelci-api/pull/473 locally and found some issues.
If this is blocking you and is super urgent, please go ahead and merge this PR. Meanwhile, I am working on fixes.

**Comment by nuclearcat** [comment]
I am going to try deploy current version production after we fixed disappearing data bug, and this friday i will make sure generated data is consistent, so team can work on stable kernels regressions. We are too much behind the schedule on this topic, so yes, unfortunately it became super urgent.
We can install now with workaround (this PR), and reverse this workaround it as soon as proper pyproject.toml recipe is ready.

**Comment by JenySadadia** [comment]
> I am going to try deploy current version production after we fixed disappearing data bug, and this friday i will make sure generated data is consistent, so team can work on stable kernels regressions. We are too much behind the schedule on this topic, so yes, unfortunately it became super urgent. We can install now with workaround (this PR), and reverse this workaround it as soon as proper pyproject.toml recipe is ready.

Sure. Please go ahead.
Just to clarify, API `pyproject.toml` is ready and working when being installed from `kernelci-api` project repository.
The issues while using `docker/api` recipe are due to missing the latest version of `kernelci` python package. We are using a workaround (https://github.com/kernelci/kernelci-api/blob/main/docker/api/Dockerfile#L27C1-L39C14) in the `kernelci-api` repo itself already and that needs to be fixed.

**Comment by nuclearcat** [comment]
Merged as temporary solution, tested on staging

**Pull request merged**
