### PR TITLE
Sparc

### PR DESCRIPTION
**Pull request by montjoie**

### CODE REVIEW

**Comment by gctucker** [comment]
I've started a `sparc64_defconfig` build on staging:
https://bot.staging.kernelci.org/job/kernel-build/65183/console

**Comment by nuclearcat** [comment]
It seems build process failed:

Cancelling nested steps due to timeout
Sending interrupt signal to process
Terminated
script returned exit code 143

**Comment by montjoie** [comment]
The jenkins link is 404, so i cannot saw what failed.

**Comment by nuclearcat** [comment]
I think it got deleted due age.
I saved it, but there is not much useful info, just pod failed by some reason.
Probably easier to repeat build and check pod logs if it will fail again.

**Comment by gctucker** [comment]
Yes it should be run by hand to see what's going on.

**Comment by gctucker** [comment]
Well I tried to build `sparc64_defconfig` in the Docker image and it didn't go very far:
```
gcc: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
gcc: error: unrecognized argument in option ‘-mcmodel=medlow’
gcc: note: valid arguments to ‘-mcmodel=’ are: 32 kernel large medium small
gcc: error: unrecognized command-line option ‘-mno-fpu’; did you mean ‘-mno-fma’?
make[2]: *** [../scripts/Makefile.build:262: scripts/mod/empty.o] Error 1
make[2]: *** Waiting for unfinished jobs....
gcc: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
gcc: error: unrecognized argument in option ‘-mcmodel=medlow’
gcc: note: valid arguments to ‘-mcmodel=’ are: 32 kernel large medium small
gcc: error: unrecognized command-line option ‘-mno-fpu’; did you mean ‘-mno-fma’?
make[2]: *** [../scripts/Makefile.build:99: scripts/mod/devicetable-offsets.s] Error 1
make[1]: *** [/root/linux/Makefile:1134: prepare0] Error 2
make[1]: Leaving directory '/root/linux/build'
make: *** [Makefile:179: sub-make] Error 2
make: Leaving directory '/root/linux'
```

**Comment by gctucker** [comment]
@montjoie Please rebase now that #1136 has been merged

**Comment by montjoie** [comment]
> @montjoie Please rebase now that #1336 has been merged

Rebased and updated, since arch is now only sparc

**Comment by gctucker** [comment]
OK removed `staging-skip`, let's check the results in the next staging jobs.

**Comment by gctucker** [comment]
@montjoie Jobs got scheduled but failed because there's no `sparc` rootfs image for baseline:
```
Resource unavailable at 'http://storage.kernelci.org/images/rootfs/buildroot/buildroot-baseline/20230310.0/sparc/rootfs.cpio.gz' (404)
```
https://lava.collabora.dev/scheduler/job/9746088

So please make another PR to fix this.

**Comment by mgalka** [comment]
@montjoie Do you have any updates on it?

**Comment by montjoie** [comment]
I have https://github.com/kernelci/buildroot/pull/15 which wait merging.

**Comment by mgalka** [comment]
@montjoie It seems that the PR have now everything to be run on staging. There are rootfs and qemu docker images with sparc64 tools on board, but for some reason I cannot see tests results on the dashboard.
Is there something specific that needs to be set for qemu device to accept this tests?

**Comment by mgalka** [comment]
> @montjoie It seems that the PR have now everything to be run on staging. There are rootfs and qemu docker images with sparc64 tools on board, but for some reason I cannot see tests results on the dashboard. Is there something specific that needs to be set for qemu device to accept this tests?

@montjoie ping?

**Comment by montjoie** [comment]
Sorry I am on holidays, but I will try to check soon.

**Comment by montjoie** [comment]
Just did a quick check, the qemu worker was dead, I restarted it.

**Comment by montjoie** [comment]
Job fails with Job error: Invalid job data: ["Resource unavailable at 'http://storage.kernelci.org/images/rootfs/buildroot/buildroot-baseline/20230421.0/sparc/rootfs.cpio.gz' (404)"]

**Comment by mgalka** [comment]
> Job fails with Job error: Invalid job data: ["Resource unavailable at 'http://storage.kernelci.org/images/rootfs/buildroot/buildroot-baseline/20230421.0/sparc/rootfs.cpio.gz' (404)"]

Ah, this is probably because of the recent rootfs images update, let me fix it and I'll check if it runs fine now.

**Comment by mgalka** [comment]
> Job fails with Job error: Invalid job data: ["Resource unavailable at 'http://storage.kernelci.org/images/rootfs/buildroot/buildroot-baseline/20230421.0/sparc/rootfs.cpio.gz' (404)"]

I updated rootfs images config so it should be using staging images placed at https://storage.staging.kernelci.org/images/rootfs/buildroot/buildroot-baseline/20230418.0/

@montjoie Could you have another look at it

**Comment by gctucker** [comment]
@montjoie Please take a look or this will need to be closed if there's no update next week.

**Comment by montjoie** [comment]
rootfs are still not found https://lava.baylibre.com/scheduler/job/3656501

**Comment by gctucker** [comment]
Please add sparc - sparc64 to the map in YAML

**Comment by montjoie** [comment]
> Please add sparc - sparc64 to the map in YAML

I tried:
--- a/config/core/test-configs.yaml
+++ b/config/core/test-configs.yaml
@@ -14,6 +14,7 @@ file_system_types:
       armel:   [{arch: arm}]
       x86:     [{arch: i386}, {arch: x86_64}]
       mipsel:  [{arch: mips}]
+      sparc:   [{arch: sparc64, endian: big}]

no change

**Comment by montjoie** [comment]
I will update the PR, but seems few kernel are built on staging, I cannot successful boot (next is failling).

**Comment by gctucker** [comment]
OK so either someone fixes Sparc on linux-next or we get a build on staging with a stable kernel revision known to work well.  How about 6.1?

**Comment by gctucker** [comment]
Yes.  But which stable kernel version is known to work with Sparc64?

**Comment by gctucker** [comment]
Adding skip label because of #1994

**Comment by nuclearcat** [comment]
I am closing PR related to legacy and SPARC. We might open topic again when we finish migrating legacy configurations to Maestro

**Pull request closed without merging**
