### PR TITLE
kselftest.jinja2: update test-definitions

### PR DESCRIPTION
**Pull request by alexandrasp**
update to test on staging changes in test definitions.

Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>

### CODE REVIEW

**Comment by gctucker** [comment]
Skipping as this is causing a conflict with the patch on staging to use the staging.kernelci.org branch.

@alexandrasp Can you try to use the modified test-definitions with your own Jenkins jobs instead?

**Comment by alexandrasp** [comment]
> Skipping as this is causing a conflict with the patch on staging to use the staging.kernelci.org branch.
> 
> @alexandrasp Can you try to use the modified test-definitions with your own Jenkins jobs instead?
 
I modified and tested it on my own, seems to be working as we expect, so the idea is test it on staging by "normal" pipeline and have some results on our front-end. 
Take a look on this lava jobs: 
https://lava.collabora.co.uk/scheduler/job/4206496#L2959
https://lava.collabora.co.uk/scheduler/job/4206488#L2804

**Comment by gctucker** [comment]
@alexandrasp In that case, please submit some PRs for https://github.com/kernelci/test-definitions and it'll get tested on staging.

**Comment by gctucker** [comment]
OK I see https://github.com/kernelci/test-definitions/pull/11

So I think this PR can be closed now.

**Pull request closed without merging**
