### PR TITLE
Fix sparc64 build (#1178)

### PR DESCRIPTION
**Pull request by gctucker**
Cherry-pick the change from #1178 to enable sparc64 builds and fix a few issues to get it to work as expected.  This does not include the QEMU changes for running tests.

### CODE REVIEW

**Review by montjoie — APPROVED** [review]

**Comment by nuclearcat** [comment]
Build fails:
```
make_kernel
make KBUILD_BUILD_USER=KernelCI ARCH=sparc64 HOSTCC=gcc CROSS_COMPILE=sparc64-linux-gnu- CC="ccache sparc64-linux-gnu-gcc" O=/root/kernelci-quickstart/kernelci-core/linux-build -Clinux-kdir -j34 -s zImage
<stdin>:1517:2: warning: #warning syscall clone3 not implemented [-Wcpp]
WARNING: modpost: EXPORT symbol "_mcount" [vmlinux] version generation failed, symbol will not be versioned.
Is "_mcount" prototyped in <asm/asm-prototypes.h>?
  kernel: arch/sparc/boot/image is ready
  kernel: arch/sparc/boot/zImage is ready
No kernel image found
```
I think because for sparc, it generates image in arch/sparc/boot, there is no arch/sparc64

**Comment by nuclearcat** [comment]
Should i retest or its not fixed yet?

**Comment by gctucker** [comment]
I'm testing this on staging

**Review by gctucker — COMMENTED** [review]
Tested OK on staging: https://staging.kernelci.org/build/id/62ea3147871156cf5fe19da7/

**Pull request merged**
