### PR TITLE
 CHROMEOS test-configs-chromeos.yaml: add asus-C436FA-Flip-hatch_chromeos device type

### PR DESCRIPTION
**Pull request by mgalka**
Add asus-C436FA-Flip-hatch_chromeos device type

### CODE REVIEW

**Review by gctucker — COMMENTED** [review]
Please put a comment with a link to a cros-flash job to confirm it worked.  Then we can start looking into getting cros-boot to work too.

**Comment by mgalka** [comment]
Flashing job completed: https://lava.collabora.co.uk/scheduler/job/6670087 with https://storage.chromeos.kernelci.org/images/rootfs/chromeos/chromiumos-hatch/20220621.0/

**Comment by mgalka** [comment]
Chrome OS booted fine: https://lava.collabora.co.uk/scheduler/job/6673527

**Comment by gctucker** [comment]
> Chrome OS booted fine: https://lava.collabora.co.uk/scheduler/job/6673527

@mgalka There's a problem though with installing the modules:
https://lava.collabora.co.uk/scheduler/job/6673527#L2933
```
mount: /lava-6673527/0/tests/0_modules/nvme0n1: special device /dev/mmcblk0p3 does not exist.
```
So I think this worked out of luck since the Chrome OS kernel modules were already part of the image when it was flashed and it's the same modules that are trying to get installed.

At least this shows the kernel image and modules are working. But the cros-flash image doesn't have the changes to specify the block device apparently.

**Comment by mgalka** [comment]
> > Chrome OS booted fine: https://lava.collabora.co.uk/scheduler/job/6673527
> 
> @mgalka There's a problem though with installing the modules: https://lava.collabora.co.uk/scheduler/job/6673527#L2933
> 
> ```
> mount: /lava-6673527/0/tests/0_modules/nvme0n1: special device /dev/mmcblk0p3 does not exist.
> ```
> 
> So I think this worked out of luck since the Chrome OS kernel modules were already part of the image when it was flashed and it's the same modules that are trying to get installed.
> 
> At least this shows the kernel image and modules are working. But the cros-flash image doesn't have the changes to specify the block device apparently.

@gctucker I accidentally left the old `bullseye-cros-flash` URL. I've corrected it and re-run the tests

https://lava.collabora.co.uk/scheduler/job/6675895

**Review by gctucker — APPROVED** [review]
Tested OK on staging.

**Pull request merged**
