### PR TITLE
kernelci.cli.user: send token to GET users requests

### PR DESCRIPTION
**Pull request by JenySadadia**
Depends https://github.com/kernelci/kernelci-api/pull/430

Send API token for getting existing users' information as the endpoint has made accessible to only authorized users.

### CODE REVIEW

**Review by nuclearcat — APPROVED** [review]
Verified by user find command, works ok on staging

**Comment by gctucker** [comment]
@JenySadadia Why has authentication been added there?  Is this a `fastapi-users` requirement?

**Comment by nuclearcat** [comment]
We had discussion and decided it is not good idea to expose usernames and emails without authentication from privacy standpoint.

**Comment by gctucker** [comment]
OK, this seems a bit arbitrary.  I would have added a field to let users mask their email address if they didn't want to share it publicly.  I guess that can always be done later.

Only real issue as far as I'm concerned is I need to rebase my PRs again so I can finally get my old changes merged ;)

**Pull request merged**
