### PR TITLE
CHROMEOS MT8192-asurada-spherion passing tast on 6.1

### PR DESCRIPTION
**Pull request by nfraprado**
This PR adds the needed kernel config and patches to get ChromeOS working and the tast tests passing on mt8192-asurada-spherion running 6.1.

This is the list of backported patches (all of them are merged upstream, except for the last one, which should be merged soon):
* [MT8192 Asurada devicetree - Part 2](https://lore.kernel.org/all/20221102190611.283546-1-nfraprado@collabora.com/#r)
* [soc: mediatek: Introduce mediatek-regulator-coupler driver](https://lore.kernel.org/all/20221006115816.66853-1-angelogioacchino.delregno@collabora.com/#r)
* [MTK: Undesired set_rate on main PLLs and GPU DVFS](https://lore.kernel.org/all/20221024102307.33722-1-angelogioacchino.delregno@collabora.com/#r)
* [arm64: dts: mt8186: Add power domains controller](https://lore.kernel.org/all/20221123135531.23221-3-allen-kh.cheng@mediatek.com/#r) (just to resolve conflict)
* [Panfrost: Improve and add MediaTek SoCs support](https://lore.kernel.org/all/20230228102704.708150-1-angelogioacchino.delregno@collabora.com/)
* [Enable GPU with DVFS support on MediaTek SoCs](https://lore.kernel.org/all/20230301095523.428461-1-angelogioacchino.delregno@collabora.com/#r)

### CODE REVIEW

**Comment by nuclearcat** [comment]
Started testing https://bot.staging.kernelci.org/job/chromeos/job/kernel-tree-monitor/255/console

**Comment by nuclearcat** [comment]
It looks like asurada not booting into tast with this tree yet? 
https://chromeos.kernelci.org/test/job/collabora-chromeos-kernel/branch/6.1-cros-tast-mt8192-asurada-spherion/kernel/v6.1-3793-gf6bce49920df/

**Comment by nfraprado** [comment]
@nuclearcat  Ohh looks like it is using just the chromiumos-arm64 config because of the change in filter in #1848...

OK, I just made the filter in that PR branch specific, so it shouldn't interfere anymore. Can you re-run please?

**Comment by nuclearcat** [comment]
Doing now

**Comment by nfraprado** [comment]
Changed the config to use the kernel added in https://github.com/kernelci/kernelci-deploy/pull/77. That branch will automatically apply the needed patches on top of the latest 6.1.y kernel.

**Comment by nuclearcat** [comment]
Tast tests being run on asurada and jacuzzi as intended. They actually fail to run due serial console issue, but this is more area of improvements for tast tests than any issue with this PR.

**Review by nuclearcat — APPROVED** [review]
LGTM

**Pull request merged**
