### PR TITLE
Add kci node sub-command

### PR DESCRIPTION
**Pull request by gctucker**
Add an initial sub-command `kci node` with the following syntax:
```
kci node get <ID>
kci node find attr1=value attr2=value
kci node count attr1=value attr2=value
```

Sample `kernelci.conf`:
```ini
[DEFAULT]
verbose: True
api_config: docker-host

[api:docker-host]
api_token: <secret token here>

[node]
```

For example:
```
kernelci@015bba541c79:~/kernelci-core$ ./kci node get 6374b725e778513908e04384 --indent='  '
{
  "_id": "6374b725e778513908e04384",
  "kind": "node",
  "name": "checkout",
  "path": [
    "checkout"
  ],
  "group": null,
  "revision": {
    "tree": "mainline",
    "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git",
    "branch": "master",
    "commit": "59d0d52c30d4991ac4b329f049cc37118e00f5b0",
    "describe": null,
    "version": null
  },
  "parent": null,
  "state": "done",
  "result": null,
  "artifacts": null,
  "created": "2022-11-16T10:10:45.120000",
  "updated": "2022-11-16T10:11:05.139000",
  "timeout": "2022-11-16T10:11:05.120000",
  "holdoff": "2022-11-16T10:11:05.120000"
}
```

```
kernelci@015bba541c79:~/kernelci-core$ ./kci node find --limit=2 revision.tree=mainline 
[{"_id": "6374b725e778513908e04384", "kind": "node", "name": "checkout", "path": ["checkout"], "group": null, "revision": {"tree": "mainline", "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git", "branch": "master", "commit": "59d0d52c30d4991ac4b329f049cc37118e00f5b0", "describe": null, "version": null}, "parent": null, "state": "done", "result": null, "artifacts": null, "created": "2022-11-16T10:10:45.120000", "updated": "2022-11-16T10:11:05.139000", "timeout": "2022-11-16T10:11:05.120000", "holdoff": "2022-11-16T10:11:05.120000"}, {"_id": "6374b86b559dc6bb05f7c6c5", "kind": "node", "name": "checkout", "path": ["checkout"], "group": null, "revision": {"tree": "mainline", "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git", "branch": "master", "commit": "59d0d52c30d4991ac4b329f049cc37118e00f5b0", "describe": null, "version": null}, "parent": null, "state": "done", "result": null, "artifacts": null, "created": "2022-11-16T10:16:11.810000", "updated": "2022-11-16T10:18:11.842000", "timeout": "2022-11-16T10:18:11.800000", "holdoff": "2022-11-16T10:16:11.810000"}]
```

```
kernelci@015bba541c79:~/kernelci-core$ ./kci node count revision.tree=mainline 
118
```

### CODE REVIEW

**Comment by gctucker** [comment]
@JenySadadia This PR currently depends on a few others to be merged first, but maybe you could take a look from a user point of view?  It doesn't cover things like sending or updating nodes, this is read-only but I thought you could already compare that with raw `curl` commands etc.

**Comment by JenySadadia** [comment]
> @JenySadadia This PR currently depends on a few others to be merged first, but maybe you could take a look from a user point of view? It doesn't cover things like sending or updating nodes, this is read-only but I thought you could already compare that with raw `curl` commands etc.

Sure, I see this PR couldn't get merged on staging. I tested it locally.
How do I get all the nodes from the API ? `kci node find` command is complaining if at least one attribute is not provided.

**Comment by gctucker** [comment]
Try doing a search in Google with nothing in the input box ;)

**Comment by gctucker** [comment]
I think we'll need to extend queries for a web dashboard use-case, things like aggregation to get the list of test groups or kernel trees etc. directly from the database.

About your question to get all the nodes, that's not really searching for nodes but I guess it could be done by setting the attributes argument as optional.  One reason for allowing this would be to expose the same kind of functionality as the raw API.  I can give this a try.

**Comment by JenySadadia** [comment]
> Try doing a search in Google with nothing in the input box ;)

Lol. I will still get some suggestions there to start with.

**Comment by JenySadadia** [comment]
> I think we'll need to extend queries for a web dashboard use-case, things like aggregation to get the list of test groups or kernel trees etc. directly from the database.
> 
> About your question to get all the nodes, that's not really searching for nodes but I guess it could be done by setting the attributes argument as optional. One reason for allowing this would be to expose the same kind of functionality as the raw API. I can give this a try.

So maybe you need to introduce a sub-command for this.

**Pull request merged**
