### PR TITLE
config/docker: update all ChromeOS Docker images to kci docker

### PR DESCRIPTION
**Pull request by gctucker**
Merge and consolidate all the changes from the `chromeos` branch to use the new `kci docker` templates for the Docker images used to run ChromeOS tests on chromeos.kernelci.org.

### CODE REVIEW

**Comment by gctucker** [comment]
Note: I've already rebased the `chromeos` branch on top of this PR so the next set of staging ChromeOS jobs should be using the same version of the templates etc.

**Comment by gctucker** [comment]
Here's the diff between the newly rebased branch and before this PR was created:
```diff
diff --git a/config/docker/cros-baseline.jinja2 b/config/docker/cros-baseline.jinja2
index 3736d06146ab..2af9f96a7a0a 100644
--- a/config/docker/cros-baseline.jinja2
+++ b/config/docker/cros-baseline.jinja2
@@ -12,7 +12,6 @@ RUN apt-get update && apt-get install --no-install-recommends -y \
     curl \
     git \
     inetutils-ping \
-    sudo \
     ssh \
     wget
 
diff --git a/config/docker/cros-qemu-modules.jinja2 b/config/docker/cros-qemu-modules.jinja2
index ee1eba5ddcbd..17c89bdc440f 100644
--- a/config/docker/cros-qemu-modules.jinja2
+++ b/config/docker/cros-qemu-modules.jinja2
@@ -17,7 +17,10 @@ RUN apt-get update && \
 ENV LIBGUESTFS_BACKEND=direct \
     HOME=/root
 
-ADD https://raw.githubusercontent.com/kernelci/kernelci-core/chromeos.kernelci.org/config/docker/data/add_modules.sh /add_modules.sh
+ADD https://raw.githubusercontent.com/kernelci/kernelci-core/\
+7f58ddf26d08bd046ddff553681b59a0e7b48bc6/\
+config/docker/data/add_modules.sh \
+/add_modules.sh
 
 # Needed by LAVA to install the overlay
 USER root
diff --git a/config/docker/cros-tast.jinja2 b/config/docker/cros-tast.jinja2
index 27d9bae859cb..6be1b6a283b3 100644
--- a/config/docker/cros-tast.jinja2
+++ b/config/docker/cros-tast.jinja2
@@ -14,7 +14,6 @@ RUN apt-get update && apt-get install --no-install-recommends -y \
     inetutils-ping \
     python3 \
     python-pkg-resources \
-    sudo \
     ssh \
     wget
 
@@ -22,8 +21,15 @@ RUN apt-get update && apt-get install --no-install-recommends -y \
 
 {{ super() }}
 
-ADD https://raw.githubusercontent.com/kernelci/kernelci-core/chromeos.kernelci.org/config/docker/data/tast_parser.py /home/cros/tast_parser.py
-ADD https://raw.githubusercontent.com/kernelci/kernelci-core/chromeos.kernelci.org/config/docker/data/ssh_retry.sh /home/cros/ssh_retry.sh
+ADD https://raw.githubusercontent.com/kernelci/kernelci-core/\
+7f58ddf26d08bd046ddff553681b59a0e7b48bc6/\
+config/docker/data/tast_parser.py \
+/home/cros/tast_parser.py
+
+ADD https://raw.githubusercontent.com/kernelci/kernelci-core/\
+7f58ddf26d08bd046ddff553681b59a0e7b48bc6/\
+config/docker/data/ssh_retry.sh \
+/home/cros/ssh_retry.sh
 
 # Needed by LAVA to install the overlay
 USER root
diff --git a/config/docker/fragment/cros-lava.jinja2 b/config/docker/fragment/cros-lava.jinja2
index 5b4a71bef734..7e14b7f1e751 100644
--- a/config/docker/fragment/cros-lava.jinja2
+++ b/config/docker/fragment/cros-lava.jinja2
@@ -1,8 +1,11 @@
+RUN apt-get update && apt-get install --no-install-recommends -y sudo
+
 RUN \
   mkdir -p /home/cros && \
   useradd cros -d /home/cros && \
   chown cros: -R /home/cros && \
   adduser cros sudo && \
+  echo 'PATH=/home/cros-tast/trunk/chromite/scripts:$PATH' >/home/cros-tast/.profile && \
   echo "cros ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
 USER cros
 ENV HOME=/home/cros
```

**Comment by nuclearcat** [comment]
One thing confusing me is:
```
 
-ADD https://raw.githubusercontent.com/kernelci/kernelci-core/chromeos.kernelci.org/config/docker/data/tast_parser.py /home/cros/tast_parser.py
-ADD https://raw.githubusercontent.com/kernelci/kernelci-core/chromeos.kernelci.org/config/docker/data/ssh_retry.sh /home/cros/ssh_retry.sh
+ADD https://raw.githubusercontent.com/kernelci/kernelci-core/\
+7f58ddf26d08bd046ddff553681b59a0e7b48bc6/\
+config/docker/data/tast_parser.py \
+/home/cros/tast_parser.py
+
+ADD https://raw.githubusercontent.com/kernelci/kernelci-core/\
+7f58ddf26d08bd046ddff553681b59a0e7b48bc6/\
+config/docker/data/ssh_retry.sh \
+/home/cros/ssh_retry.sh
```
It looks like it is pointing to specific version of ssh_retry.sh and tast parser. I am not sure what is best here. In long term it might be obsolete version, but pointing to chromeos.kernelci.org, while it is main branch code - not right a well

**Comment by gctucker** [comment]
Yes, the idea is to have this merged and then update the revision.  It's important to pick a particular revision to know when the script is being updated.  We could also use the `chromeos` branch I guess but that's still a bit undecided until the chromeos.kernelci.org instance become an actual production instance.

**Comment by gctucker** [comment]
Tested OK, the Docker images got built fine and Tast results are working:
https://chromeos.kernelci.org/test/job/kernelci/branch/chromeos-stable/kernel/chromeos-stable-20230622.0/plan/cros-tast-perf/

That doesn't cover all the Docker images involved here but it should be enough to check it's working as expected based on the diff between this PR and the original `chromeos` branch.

**Pull request merged**
