### PR TITLE
CHROMEOS rootfs-configs-chromeos.yaml: add chromiumos-hatch

### PR DESCRIPTION
**Pull request by gctucker**
Add a config entry for building Chromium OS R100 for hatch.

Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>

### CODE REVIEW

**Comment by gctucker** [comment]
@mgalka @nuclearcat  The config entry for hatch got dropped in the latest rebase as there's now a `rootfs-configs-chromeos.yaml` file in `main`.  So this is to add it back.  I'm making another PR to do the same with `grunt` although it'll probably need more work to get it to boot properly since it has a different graphic stack (AMD).

**Comment by gctucker** [comment]
I just started a built for hatch: https://bot.staging.kernelci.org/job/chromeos/job/rootfs-builder/41/console

**Comment by nuclearcat** [comment]
I started manual build too, seems going fine

**Review by nuclearcat — APPROVED** [review]
LGTM, manual build completed successfully

**Comment by gctucker** [comment]
Chromium OS image build completed fine (12h build time):
https://storage.chromeos.kernelci.org/images/rootfs/chromeos/chromiumos-hatch/20220621.0/amd64/

**Review by mgalka — APPROVED** [review]
LGTM

**Pull request merged**
