### PR TITLE
Extend kselftest coverage

### PR DESCRIPTION
**Pull request by gctucker**
Enable the newly added kselftest collections lkdtm and seccomp on x86 devices.

Depends on #735 and #737

### CODE REVIEW

**Review by kees — APPROVED** [review]
Looks great to me!

**Comment by kees** [comment]
(Should I fix my test-configs.yaml commit, or is the FIXUP sufficient?)

**Comment by gctucker** [comment]
> (Should I fix my test-configs.yaml commit, or is the FIXUP sufficient?)

@kees Please fix yours and then I'll rebase mine without the FIXUP.  In fact you need to fix yours for the GitHub checks to pass and then have it merged, as the YAML is currently failing validation.

**Comment by gctucker** [comment]
This is being tested on staging now with the `staging-next-20210624.0` kernel revision which includes Kees' patch series with LKDTM improvements:
https://lore.kernel.org/lkml/20210623203936.3151093-1-keescook@chromium.org/

Will check the results later to confirm this is all working as expected.

**Comment by gctucker** [comment]
Tested OK on staging:
https://staging.kernelci.org/test/job/kernelci/branch/staging-next/kernel/staging-next-20210624.0/plan/kselftest-lkdtm/

The `$SHELL`  environment variable is set to `/bin/bash`.  The `bc` package is installed.  The `lkdtm` tests are being run as expected.  Here's a debug job resubmitted with the same buster-kselftest rootfs just to check the changes had the desired effects:
https://lava.collabora.co.uk/scheduler/job/4092437#L2619

**Pull request merged**
