### PR TITLE
config/core/test-configs-cip: update isar-cip-core rootfs to 20231004 bookworm

### PR DESCRIPTION
**Pull request by aliceinwire**
updating isar-cip-core rootfs to currently the last one 20231004 this also update the image from buster to bookworm

### CODE REVIEW

**Comment by aliceinwire** [comment]
I closed the previous PR and create a smaller PR for just upgrading the isar-cip-rootfs to the latest version
This should be more easy to merged
@patersonc is this ok for you?

**Comment by patersonc** [comment]
> I closed the previous PR and create a smaller PR for just upgrading the isar-cip-rootfs to the latest version This should be more easy to merged @patersonc is this ok for you?

Looks okay to me. Is there a kernelci pipeline where this new rfs has been tested?

**Comment by aliceinwire** [comment]
@gctucker

**Comment by nuclearcat** [comment]
Thanks!

**Pull request merged**
