### PR TITLE
T41723 Implement unit tests for `APIHelper`

### PR DESCRIPTION
**Pull request by JenySadadia**
Fixes https://github.com/kernelci/kernelci-core/issues/1854

Added `tests/api` directory for API specific tests.
Moved `tests/test_api.py` file to `tests/api` directory.
Added unit tests to the file. Also, added `conftest.py` file for pytest fixtures.

### CODE REVIEW

**Review by gctucker — COMMENTED** [review]
I think you'll need at least an empty `tests/api/__init__.py` file to make it a package, right?

**Comment by JenySadadia** [comment]
> I think you'll need at least an empty `tests/api/__init__.py` file to make it a package, right?

Yes

**Comment by JenySadadia** [comment]
Added `APIHelperTestData` class to generate and get test data for fixtures and test definitions.

**Review by mgalka — APPROVED** [review]

**Comment by mgalka** [comment]
@JenySadadia I approved this PR. Thank you for valuable input. Do you think it'd be worth to implement e.g. a test for `APIHelper._prepare_results()` as a follow-up?

**Comment by JenySadadia** [comment]
> @JenySadadia I approved this PR. Thank you for valuable input. Do you think it'd be worth to implement e.g. a test for `APIHelper._prepare_results()` as a follow-up?

Thank you @mgalka for reviewing this.
Here `APIHelper._prepare_results()` is being used by `APIHelper.submit_results()` method. As we don't have any public wrapper for the method `_prepare_results` and it is an internal logic, I'd say we should include it in e2e tests rather than unit tests.

**Comment by JenySadadia** [comment]
Bdw I have added a small fixup as a follow-up here https://github.com/kernelci/kernelci-core/pull/1888

**Comment by gctucker** [comment]
I think unit tests should cover individual methods, in this case I think the `submit_results()` method is very close to it but we could also have a test with just `_prepare_results()`.  I don't believe it's really necessary as if `_prepare_results()` is broken the test using `submit_results()` will fail and it should be obvious enough to debug it.  If you look at the unit tests for the YAML config, you'll see some are using the `._filters` private field with `pylint: disable=protected-access` at the top of the file explaining why it's OK to do this with unit tests.

End-to-end tests are about trying the system as a whole, so the internal methods being used aren't relevant to them.

**Comment by JenySadadia** [comment]
Please see https://github.com/kernelci/kernelci-core/pull/1891

**Pull request merged**
