### PR TITLE
test-configs:   Bump CIP core image to 20220920

### PR DESCRIPTION
**Pull request by aliceinwire**

### CODE REVIEW

**Comment by gctucker** [comment]
@aliceinwire What's the status of this? If it's working then please drop the "Draft" bit in the subject and update the commit messages and get the GitHub checks to pass ;)

**Comment by aliceinwire** [comment]
@gctucker updated the code

**Comment by mgalka** [comment]
@aliceinwire Please, resolve the conflicts

**Comment by aliceinwire** [comment]
@mgalka can you please merge this PR?

**Review by mgalka — APPROVED** [review]

**Pull request merged**
