### PR TITLE
rootfs-configs.yaml: add buster-kselftest

### PR DESCRIPTION
**Pull request by alexandrasp**
Include instructions to create a rootfs buster-kselftest to satisfy run time dependencies from kselftest.

Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>

### CODE REVIEW

**Comment by gctucker** [comment]
Have you built this rootfs on staging?

**Comment by alexandrasp** [comment]
> Have you built this rootfs on staging?
 
 [yes, I have.](https://storage.staging.kernelci.org/images/rootfs/debian/buster-kselftest/)

**Comment by alexandrasp** [comment]
> OK, I think it's worth adding to the rootfs all the packages that are getting installed in this job:
> https://lava.collabora.co.uk/scheduler/job/3782461#L5593

done: https://lava.collabora.co.uk/scheduler/job/3786122

**Review by gctucker — APPROVED** [review]
LGTM

https://lava.collabora.co.uk/scheduler/job/3786122#L5559
```
INFO: Installing sed perl wget xz-utils iproute2
Hit:1 http://deb.debian.org/debian buster InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
iproute2 is already the newest version (4.20.0-2+deb10u1).
perl is already the newest version (5.28.1-6+deb10u1).
sed is already the newest version (4.7-1).
wget is already the newest version (1.20.1-1.1).
xz-utils is already the newest version (5.2.4-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by gctucker** [comment]
@alexandrasp As a follow-up, please create a PR to make kselftest test plans use the buster-kselftest rootfs image.

**Pull request merged**
