### PR TITLE
kci_rootfs: add default value for --data-path

### PR DESCRIPTION
**Pull request by gctucker**
Add a default value for the --data-path argument based on the rootfs
type.

Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>

### CODE REVIEW

**Comment by mgalka** [comment]
@gctucker 
ooi, Is it just for simplifying debos images building or is there other reason for that?

**Review by mgalka — APPROVED** [review]
lgtm

**Comment by gctucker** [comment]
> @gctucker ooi, Is it just for simplifying debos images building or is there other reason for that?

I found this while working on the How-To guide.  Other default values assume the command line tools are running directly in the repository checkout (e.g. path to YAML config files), so this makes things a bit easier.  It makes the documentation examples shorter too.

**Comment by Lakshmipathi** [comment]
LGTM

**Comment by gctucker** [comment]
Tested OK on staging, no regressions found.

**Pull request merged**
