### PR TITLE
test-configs: Additional tests for Tritium

### PR DESCRIPTION
**Pull request by broonie**
I have three Tritiums available in my lab which are mostly idle with the
current loading, add some more hardware agnostic tests to make use of
them.

Signed-off-by: Mark Brown <broonie@kernel.org>

### CODE REVIEW

**Comment by nuclearcat** [comment]
It seems kselftest-arm64 doesn't pass in lab-baylibre for sun50i-h5-libretech-all-h3-cc:
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220712.0/plan/kselftest-arm64/

https://staging.kernelci.org/test/plan/id/62ccd17f1a6e8333de74f1cc/
https://storage.staging.kernelci.org/kernelci/staging-mainline/staging-mainline-20220712.0/arm64/defconfig/gcc-10/lab-baylibre/kselftest-arm64-sun50i-h5-libretech-all-h3-cc.html

**Comment by broonie** [comment]
The sun50i-h5-libretech-all-h3-cc: issue in the Baylibre lab is a clear infra issue - it's getting permission denied trying to mount the rootfs over NFS. @montjoie

**Comment by nuclearcat** [comment]
sun50i-h5-libretech-all-h3-cc checking in lab-broonie all test passing:
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-arm64
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-capabilities
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-cgroup
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-clone3
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-cpufreq
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-exec
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-filesystems
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-futex
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-kcmp
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-kvm
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-lib
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-membarrier
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-mincore
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-openat2
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-seccomp
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20220718.0/plan/kselftest-timers

Except preempt-rt, which i cannot find matching builds yet, investigating together with https://github.com/kernelci/kernelci-core/pull/1286

**Comment by nuclearcat** [comment]
https://staging.kernelci.org/test/plan/id/62d8387dd4a38e9bd0e19da5/
preempt-rt passing ok now too in staging, i guess PR ready to be merged

**Review by nuclearcat — APPROVED** [review]
All tests passing ok on staging

**Pull request merged**
