### PR TITLE
Rust 1.74

### PR DESCRIPTION
**Pull request by ojeda**
Rust 1.74.1 will likely be the next version supported by the kernel [1].

Therefore, add it as a new build environment.

Link: https://lore.kernel.org/rust-for-linux/20231214092958.377061-1-ojeda@kernel.org/ [1]

See also: https://github.com/kernelci/kernelci-deploy/pull/113 and https://github.com/kernelci/kernelci-deploy/pull/114.

### CODE REVIEW

**Review by aliceinwire — APPROVED** [review]

**Comment by aliceinwire** [comment]
Thanks, currently testing this

**Comment by aliceinwire** [comment]
tested and worked but as the [rust: upgrade to Rust 1.74.1](https://lore.kernel.org/rust-for-linux/20231214092958.377061-1-ojeda@kernel.org/#r) is not yet in rust-next it throws errors and kernel not build
wait for the rust-next to be upgraded to Rust 1.74.1 before merging

**Comment by ojeda** [comment]
Thanks a lot Alice!

> wait for the rust-next to be upgraded to Rust 1.74.1 before merging

I think @gctucker preferred to update KernelCI first (https://github.com/kernelci/kernelci-core/pull/1890#pullrequestreview-1403639261). For me, either way it is OK :)

In any case, I will apply the upgrade to `rust-next` soon (e.g. later today perhaps).

**Comment by ojeda** [comment]
I applied Rust 1.74.1 yesterday, i.e. `rust-next` is now using it.

**Comment by aliceinwire** [comment]
> Thanks a lot Alice!
> 
> > wait for the rust-next to be upgraded to Rust 1.74.1 before merging
> 
> I think @gctucker preferred to update KernelCI first ([#1890 (review)](https://github.com/kernelci/kernelci-core/pull/1890#pullrequestreview-1403639261)). For me, either way it is OK :)
> 
> In any case, I will apply the upgrade to `rust-next` soon (e.g. later today perhaps).

I see, I'm also ok on updating KernelCI first

**Comment by ojeda** [comment]
Thanks!

**Pull request merged**
