### PR TITLE
Update baseline-nfs to use debian/buster ramdisk + full rootfs

### PR DESCRIPTION
**Pull request by khilman**

### CODE REVIEW

**Comment by gctucker** [comment]
Looks good at first glance.

Please also add the `dmesg.sh` script which will look for kernel errors.  It's in the buildroot baseline overlay directory:
https://github.com/kernelci/buildroot/blob/kernelci/latest/kernelci/baseline/rootfs_overlay/opt/kernelci/dmesg.sh

**Comment by khilman** [comment]
OK, updated to include the a baseline overlay (same contents as buildroot overlay)

**Comment by gctucker** [comment]
I think `buildroot_baseline_nfs` can be dropped from test-configs.yaml now.

**Comment by khilman** [comment]
> I think `buildroot_baseline_nfs` can be dropped from test-configs.yaml now.

OK, looks like it's unused, so I  added one more patch to do that.

**Comment by khilman** [comment]
@gctucker this should be ready to merge now.

**Pull request merged**
