### PR TITLE
Enable preempt_rt on rt enabled CIP kernels

### PR DESCRIPTION
**Pull request by aliceinwire**
This pr depends on https://github.com/kernelci/kernelci-core/pull/898

### CODE REVIEW

**Comment by gctucker** [comment]
Please rebase now that #898 has been merged.

**Comment by aliceinwire** [comment]
@gctucker rebased

**Comment by gctucker** [comment]
There was a problem with the preempt-rt fragment not being generated in the last staging build.  This should have been fixed now, so I'm starting another `cip_4.19-rt` build on staging.  I'll check the results a bit later.

**Review by gctucker — COMMENTED** [review]
The builds seem to have worked for arm, arm64 and x86_64.

The preempt-rt test plan was run for only one platform and it failed to boot:
https://staging.kernelci.org/test/plan/id/61ae2d9f5a32b9d5ef3d35bc/

**Comment by aliceinwire** [comment]
> The builds seem to have worked for arm, arm64 and x86_64.
> 
> The preempt-rt test plan was run for only one platform and it failed to boot: https://staging.kernelci.org/test/plan/id/61ae2d9f5a32b9d5ef3d35bc/

Looks like the realtek module "r8a779x_usb3_v3.dlmem" is failing to load

**Comment by gctucker** [comment]
There are other platforms with preempt-rt enabled in `test-configs.yaml`, it would be good to see why they're not running the tests.  Maybe we can enable another platform that's known to work, so this PR could be merged and we can then focus on fixing issues for each device type one by one.

I'll try to see if there's any x86 Chromebook in the Collabora lab that could run preempt-rt.

**Comment by gctucker** [comment]
@aliceinwire Please rebase now that the build-configs-cip.yaml has been tidied up and preempt-rt is working with mainline on x86 and arm64 Chromebook devices.  You should be able to reuse the same rootfs image and preempt_rt config fragment for the CIP tests.

**Comment by gctucker** [comment]
@aliceinwire There's a problem with the YAML config validation:
```
E               yaml.composer.ComposerError: found undefined alias 'arm_defconfig'
E                 in "config/core/build-configs-cip.yaml", line 76, column 13
```

**Comment by aliceinwire** [comment]
@gctucker updated

**Comment by gctucker** [comment]
Started a job on staging: https://bot.staging.kernelci.org/job/kernel-build-trigger/1686/

**Comment by gctucker** [comment]
Replaced with #1094.

**Pull request closed without merging**
