### PR TITLE
config/docker: use godebos/debos as base image for debos

### LINKED ISSUE #1440: Building krnelci/debos image fails
Running 
```
./kci_docker build --verbose debos --fragment=kernelci
```
fails with the following message

```
Building kernelci/debos:kernelci
Traceback (most recent call last):
  File "./kci_docker", line 136, in <module>
    main(parser.parse_args())
  File "./kci_docker", line 103, in main
    _, build_log = _build_image(dockerfile, name, buildargs)
  File "./kci_docker", line 39, in _build_image
    fileobj=dockerfile_obj, tag=tag_name, buildargs=buildargs
  File "/home/mgalka/projects/kernelci/kernelci-core/venv3.6/lib/python3.6/site-packages/docker/models/images.py", line 285, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: The command '/bin/sh -c go get github.com/go-debos/debos/cmd/debos &&     go install github.com/go-debos/debos/cmd/debos' returned a non-zero code: 2

```

After a bit more investigation the following error messages can be found:

```
Step 10/32 : RUN go get github.com/go-debos/debos/cmd/debos &&     go install github.com/go-debos/debos/cmd/debos
 ---> Running in c1f31bae7899
# golang.org/x/sys/unix
usr/local/go/src/golang.org/x/sys/unix/syscall.go:83:16: undefined: unsafe.Slice
usr/local/go/src/golang.org/x/sys/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
usr/local/go/src/golang.org/x/sys/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
# github.com/klauspost/compress/huff0
usr/local/go/src/github.com/klauspost/compress/huff0/decompress.go:774:20: cannot convert out (type []byte) to type *[256]byte
usr/local/go/src/github.com/klauspost/compress/huff0/decompress.go:775:20: cannot convert out[dstEvery:] (type []byte) to type *[256]byte
usr/local/go/src/github.com/klauspost/compress/huff0/decompress.go:776:20: cannot convert out[dstEvery * 2:] (type []byte) to type *[256]byte
usr/local/go/src/github.com/klauspost/compress/huff0/decompress.go:777:20: cannot convert out[dstEvery * 3:] (type []byte) to type *[256]byte
usr/local/go/src/github.com/klauspost/compress/huff0/decompress.go:1013:20: cannot convert out (type []byte) to type *[256]byte
usr/local/go/src/github.com/klauspost/compress/huff0/decompress.go:1014:20: cannot convert out[dstEvery:] (type []byte) to type *[256]byte
usr/local/go/src/github.com/klauspost/compress/huff0/decompress.go:1015:20: cannot convert out[dstEvery * 2:] (type []byte) to type *[256]byte
usr/local/go/src/github.com/klauspost/compress/huff0/decompress.go:1016:20: cannot convert out[dstEvery * 3:] (type []byte) to type *[256]byte
The command '/bin/sh -c go get github.com/go-debos/debos/cmd/debos &&     go install github.com/go-debos/debos/cmd/debos' returned a non-zero code: 2
```

### PR DESCRIPTION
**Pull request by gctucker**
Move debos.jinja2 to base/debos.jinja2 and use godebos/debos as the base image since we can now just add fragments on top of it.

Fixes #1440

### CODE REVIEW

**Comment by gctucker** [comment]
Built OK in production:
```
Pushing kernelci/debos:kernelci to Docker Hub
The push refers to repository [docker.io/kernelci/debos]
kernelci: digest: sha256:2a2cb7985770b2b14eb2e8423a44ae7a996092fb8e437077ba0c398baab2c7b6 size: 4725
```
Next step is to try it with the base Debian rootfs image builds I guess.

**Comment by gctucker** [comment]
Tested fine in production: https://storage.kernelci.org/images/rootfs/debian/bullseye/20220920.1/amd64/

The other architectures are still building.

**Comment by gctucker** [comment]
Pushed to the `kernelci.org` branch for deploying in production, the `bullseye` images all built fine.

**Review by mgalka — APPROVED** [review]
Builds OK on my local setup

**Pull request merged**
