### PR TITLE
Add kernelci.config.api

### PR DESCRIPTION
**Pull request by gctucker**
Add kernelci.config.api to load the YAML configuration required to access a KernelCI API instance.  This is intended to replace the config.db which was about providing an abstraction layer for various API and backend / database implementations.

### CODE REVIEW

**Comment by JenySadadia** [comment]
Staging is not working with these changes:
```
today at 11:05:2502/07/2023 05:35:25 AM UTC [ERROR] Traceback (most recent call last):
today at 11:05:25  File "/home/kernelci/pipeline/base.py", line 68, in run
today at 11:05:25    status = self._run(context)
today at 11:05:25  File "/home/kernelci/./pipeline/trigger.py", line 96, in _run
today at 11:05:25    self._iterate_build_configs(force, build_configs_list)
today at 11:05:25  File "/home/kernelci/./pipeline/trigger.py", line 74, in _iterate_build_configs
today at 11:05:25    self._run_trigger(config, force)
today at 11:05:25  File "/home/kernelci/./pipeline/trigger.py", line 37, in _run_trigger
today at 11:05:25    node_list = self._db.count_nodes({
today at 11:05:25  File "/usr/local/lib/python3.10/site-packages/kernelci-1.1-py3.10.egg/kernelci/db/kernelci_api.py", line 109, in count_nodes
today at 11:05:25    resp = self._get('count', params=attributes)
today at 11:05:25  File "/usr/local/lib/python3.10/site-packages/kernelci-1.1-py3.10.egg/kernelci/db/kernelci_api.py", line 50, in _get
today at 11:05:25    url = self._make_url(path)
today at 11:05:25  File "/usr/local/lib/python3.10/site-packages/kernelci-1.1-py3.10.egg/kernelci/db/kernelci_api.py", line 40, in _make_url
today at 11:05:25    version_path = '/'.join((self.config.version, path))
today at 11:05:25AttributeError: 'DatabaseAPI' object has no attribute 'version'
today at 11:05:25
today at 11:25:31Container stopped
```

**Review by JenySadadia — COMMENTED** [review]
Shouldn't the `version` attribute be added to `config/core/api-configs.yaml`?

**Comment by gctucker** [comment]
> Shouldn't the `version` attribute be added to `config/core/api-configs.yaml`?

There's a default value `latest`.  We could decide to drop the default.

**Comment by JenySadadia** [comment]
> > Shouldn't the `version` attribute be added to `config/core/api-configs.yaml`?
> 
> There's a default value `latest`. We could decide to drop the default.

The default should be added to config file instead to modify it easily without touching the code.

**Comment by gctucker** [comment]
> > > Shouldn't the `version` attribute be added to `config/core/api-configs.yaml`?
> > 
> > 
> > There's a default value `latest`. We could decide to drop the default.
> 
> The default should be added to config file instead to modify it easily without touching the code.

I don't understand what you mean.  The default is in the code so it doesn't need to be specified in the YAML config.  If we have to define the version in the YAML config, then it's not a default any more.

**Comment by JenySadadia** [comment]
> > > > Shouldn't the `version` attribute be added to `config/core/api-configs.yaml`?
> > > 
> > > 
> > > There's a default value `latest`. We could decide to drop the default.
> > 
> > 
> > The default should be added to config file instead to modify it easily without touching the code.
> 
> I don't understand what you mean. The default is in the code so it doesn't need to be specified in the YAML config. If we have to define the version in the YAML config, then it's not a default any more.

Do you think is it beneficial to discard the default value from the constructor and add it to the `api-configs.yaml` instead?
I think that way it can be altered more easily if required in the future.

**Review by JenySadadia — CHANGES_REQUESTED** [review]
There is a typo in the second last commit message:

Add a version attribute to the API YAML configuration.  This can be
used in the URLs for making queries and also to create an API object
that **matches** the API version when we start supporting multiple
versions.

**Comment by gctucker** [comment]
> Do you think is it beneficial to discard the default value from the constructor and add it to the `api-configs.yaml` instead?
> I think that way it can be altered more easily if required in the future.

I think `latest` is a special value used in the API and it makes sense as a default here.  So if someone sets up an instance without specifying a particular version in YAML then it will be using the latest.

**Comment by JenySadadia** [comment]
> > Do you think is it beneficial to discard the default value from the constructor and add it to the `api-configs.yaml` instead?
> > I think that way it can be altered more easily if required in the future.
> 
> I think `latest` is a special value used in the API and it makes sense as a default here. So if someone sets up an instance without specifying a particular version in YAML then it will be using the latest.

Makes sense. So is it possible to configure it from the pipeline?

**Comment by gctucker** [comment]
> Makes sense. So is it possible to configure it from the pipeline?

Just like any part of the YAML configuration, yes.

**Review by gctucker — COMMENTED** [review]
Tested OK on staging:
```
[INFO] Listening for events... 
[INFO] Press Ctrl-C to stop.
[INFO] Time                        Commit        Node Id                   State      Result    Name
[INFO] 2023-02-10 17:35:40.579328  f3fbc982f678  63e6806c2a8c8ff21d312f52  Running    -         checkout
[INFO] 2023-02-10 17:36:37.622352  f3fbc982f678  63e6806c2a8c8ff21d312f52  Available  -         checkout
[INFO] 2023-02-10 17:36:37.718588  f3fbc982f678  63e680a52a8c8ff21d312f53  Running    -         kver
[INFO] 2023-02-10 17:36:37.836213  f3fbc982f678  63e680a52a8c8ff21d312f54  Running    -         kunit
[INFO] 2023-02-10 17:37:01.810400  f3fbc982f678  63e680a52a8c8ff21d312f53  Done       Pass      kver
[INFO] 2023-02-10 17:44:12.781973  2a71288b233e  63e67fb12a8c8ff21d312f4f  Closing    -         checkout
```
The `kunit` job seems to have hit an issue but I think that's another kind of problem.  I'll be investigating that next.

Runner log:
```
02/10/2023 05:35:10 PM UTC [INFO] Listening for available checkout events
02/10/2023 05:35:10 PM UTC [INFO] Press Ctrl-C to stop.
Getting kernel source tree...
Source directory: /tmp/kci/linux-kernelci-staging-mainline-staging-mainline-20230210.8
Running job...
Checking kernel revision
Result: pass
```

**Pull request merged**
