### PR TITLE
lab-configs: Add yet more tests for my lab

### PR DESCRIPTION
**Pull request by broonie**
Since we have to manually list all the testsuites we're willing to run
in each lab add patterns for all the currently defined ones to my lab.

Signed-off-by: Mark Brown <broonie@kernel.org>

### CODE REVIEW

**Review by nuclearcat — APPROVED** [review]
LGTM, required for some pending PR such as https://github.com/kernelci/kernelci-core/pull/1186

**Comment by gctucker** [comment]
> Since we have to manually list all the testsuites we're willing to run in each lab

Not true, just drop the `passlist` filter if you want to run everything (see comments on #1186.

**Comment by broonie** [comment]
Like I say that seems to be new if it's true now - looking at history I added a passlist because kselftest and ltp weren't getting scheduled. I'm wondering if there's a default filter setup somewhere which only allows baseline, it might happen to work for the Collabora lab since it does have a block for the Android trees but at the time I had to add the passlist for testsuites I didn't block Android.

**Comment by gctucker** [comment]
The same thing is being discussed on #1186. At any rate, there aren't any default filters and dropping the `passlist` just works so I think this PR can be closed if you really want to enable all the test plans.

```
$ git diff
diff --git a/config/core/lab-configs.yaml b/config/core/lab-configs.yaml
index 3a71df4e..b166e6c8 100644
--- a/config/core/lab-configs.yaml
+++ b/config/core/lab-configs.yaml
@@ -23,16 +23,6 @@ labs:
     priority_max: 40
     queue_timeout:
       days: 1
-    filters:
-      - blocklist: {tree: [android]}
-      - passlist:
-          plan:
-            - baseline
-            - kselftest
-            - ltp
-            - preempt-rt
-            - sleep
-            - smc
 
   lab-cip:
     lab_type: lava.lava_xmlrpc
$ wget -P data/arm https://storage.kernelci.org/mainline/master/v5.19-rc3-38-gca1fdab7fd27e/arm/multi_v7_defconfig/gcc-10/{bmeta,artifacts,steps}.json
$ ./kci_test generate --lab-config=lab-broonie --install-path=data/arm --output=data/jobs
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm-multi_v7_defconfig-gcc-10-no-dtb-qemu_arm-virt-gicv2-uefi-baseline_qemu.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm-multi_v7_defconfig-gcc-10-am335x-boneblack.dtb-beaglebone-black-baseline.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm-multi_v7_defconfig-gcc-10-no-dtb-qemu_arm-virt-gicv3-uefi-baseline_qemu.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm-multi_v7_defconfig-gcc-10-imx6dl-udoo.dtb-imx6dl-udoo-baseline.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm-multi_v7_defconfig-gcc-10-no-dtb-qemu_arm-virt-gicv3-baseline_qemu.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm-multi_v7_defconfig-gcc-10-imx6q-udoo.dtb-imx6q-udoo-baseline-nfs.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm-multi_v7_defconfig-gcc-10-imx6dl-udoo.dtb-imx6dl-udoo-baseline-nfs.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm-multi_v7_defconfig-gcc-10-am335x-boneblack.dtb-beaglebone-black-ltp-ipc.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm-multi_v7_defconfig-gcc-10-imx6q-udoo.dtb-imx6q-udoo-baseline.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm-multi_v7_defconfig-gcc-10-no-dtb-qemu_arm-virt-gicv3-smc_qemu.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm-multi_v7_defconfig-gcc-10-am335x-boneblack.dtb-beaglebone-black-kselftest-alsa.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm-multi_v7_defconfig-gcc-10-no-dtb-qemu_arm-virt-gicv2-baseline_qemu.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm-multi_v7_defconfig-gcc-10-imx6dl-udoo.dtb-imx6dl-udoo-kselftest-alsa.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm-multi_v7_defconfig-gcc-10-am335x-boneblack.dtb-beaglebone-black-baseline-nfs.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm-multi_v7_defconfig-gcc-10-imx6q-udoo.dtb-imx6q-udoo-kselftest-alsa.yaml
$ wget -P data/arm64-kselftest https://storage.kernelci.org/mainline/master/v5.19-rc3-38-gca1fdab7fd27e/arm/multi_v7_defconfig/gcc-10/{bmeta,artifacts,steps}.json
$ ./kci_test generate --lab-config=lab-broonie --install-path=data/arm64-kselftest --output=data/jobs
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm64-defconfig+kselftest-gcc-10-sun50i-a64-pine64-plus.dtb-sun50i-a64-pine64-plus-kselftest-seccomp.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm64-defconfig+kselftest-gcc-10-juno.dtb-juno-uboot-kselftest-lkdtm.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm64-defconfig+kselftest-gcc-10-sun50i-a64-pine64-plus.dtb-sun50i-a64-pine64-plus-kselftest-lib.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm64-defconfig+kselftest-gcc-10-meson-gxl-s905x-libretech-cc.dtb-meson-gxl-s905x-libretech-cc-kselftest-lib.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm64-defconfig+kselftest-gcc-10-meson-gxl-s905x-libretech-cc.dtb-meson-gxl-s905x-libretech-cc-kselftest-cpufreq.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm64-defconfig+kselftest-gcc-10-meson-gxl-s905x-libretech-cc.dtb-meson-gxl-s905x-libretech-cc-kselftest-seccomp.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm64-defconfig+kselftest-gcc-10-juno.dtb-juno-uboot-kselftest-lib.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm64-defconfig+kselftest-gcc-10-sun50i-a64-pine64-plus.dtb-sun50i-a64-pine64-plus-kselftest-cpufreq.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm64-defconfig+kselftest-gcc-10-juno.dtb-juno-uboot-kselftest-seccomp.yaml
data/jobs/mainline-master-v5.19-rc3-38-gca1fdab7fd27e-arm64-defconfig+kselftest-gcc-10-juno.dtb-juno-uboot-kselftest-cpufreq.yaml
```

**Comment by broonie** [comment]
This change is dropping the passlist - if we don't apply it then I'll be left with a passlist explicitly enumerating tests?

**Comment by broonie** [comment]
This PR *is* dropping the passlist.

**Review by gctucker — APPROVED** [review]
Tested OK on staging, we're now getting the LIMA test results:
https://staging.kernelci.org/test/job/next/branch/master/kernel/next-20220624/plan/igt-gpu-lima/

**Pull request merged**
