### PR TITLE
Add baseline-fastboot test plan variant

### PR DESCRIPTION
**Pull request by gctucker**
Add baseline-fastboot test plan as a combination of baseline and the
plan fastboot boot:

* replace boot_fastboot with baseline-fastboot in test-configs.yaml
* add templates/baseline variant for fastboot
* add baseline-fastboot email reports for kernelci tree
* run baseline-fastboot in lab-baylibre instead of boot_fastboot

Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>

### CODE REVIEW

**Comment by gctucker** [comment]
Did a quick test on staging before creating this PR, here's the YAML job definition that it generated (and submitted in lab-baylibre):
```yaml
metadata:
  image.type: 'kernel-ci'
  image.url: http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190923.1/arm64/defconfig/gcc-8/
  kernel.tree: kernelci
  kernel.version: staging-20190923.1
  kernel.endian: little
  kernel.defconfig: defconfig
  kernel.defconfig_base: defconfig
  kernel.arch_defconfig: arm64-defconfig
  platform.dtb: amlogic/meson-g12a-sei510.dtb
  platform.dtb_short: meson-g12a-sei510.dtb
  platform.fastboot: true
  platform.name: meson-g12a-sei510
  platform.mach: amlogic
  test.plan: baseline-fastboot
  git.commit: 0922a883d9fc142e1a6a908f342c39471066f8ed
  git.describe: staging-20190923.1
  git.branch: staging.kernelci.org
  git.url: https://github.com/kernelci/linux.git
  device.type: meson-g12a-sei510
  job.arch: arm64
  job.name: kernelci-staging.kernelci.org-staging-20190923.1-arm64-defconfig-gcc-8-meson-g12a-sei510.dtb-meson-g12a-sei510-baseline-fastboot
  job.kernel_url: http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190923.1/arm64/defconfig/gcc-8/Image
  job.kernel_image: Image
  job.modules_url: http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190923.1/arm64/defconfig/gcc-8/modules.tar.xz
  job.initrd_url: https://staging-storage.kernelci.org/images/rootfs/buildroot/kci-2019.02-6-gaa3933f214/arm64/baseline/rootfs.cpio.gz
  job.nfsrootfs_url: None
  job.dtb_url: http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190923.1/arm64/defconfig/gcc-8/dtbs/amlogic/meson-g12a-sei510.dtb
  job.file_server_resource: kernelci/staging.kernelci.org/staging-20190923.1/arm64/defconfig/gcc-8
  job.build_environment: gcc-8



device_type: meson-g12a-sei510


notify:
  criteria:
    status: finished
  callback:
    url: https://staging-api.kernelci.org/callback/lava/test?lab_name=lab-baylibre-dev&status={STATUS}&status_string={STATUS_STRING}
    method: POST
    dataset: all
    token: kernel-ci-callback-staging
    content-type: json


job_name: kernelci-staging.kernelci.org-staging-20190923.1-arm64-defconfig-gcc-8-meson-g12a-sei510.dtb-meson-g12a-sei510-baseline-fastboot
timeouts:
  job:
    minutes: 50
  action:
   minutes: 10
  actions:
    power-off:
      seconds: 30
priority: medium
visibility: public

tags:
  - fastboot
protocols:
  lava-lxc:
    name: lxc-meson-g12a-sei510-kernelci-fastboot
    template: debian
    distribution: debian
    release: buster



actions:

- deploy:
    namespace: host
    timeout:
      minutes: 15
    to: lxc
    packages:
    - android-tools-adb
    - android-tools-fastboot
    - cpio
    - mkbootimg

- boot:
    namespace: host
    prompts:
    - 'root@(.*):/#'
    timeout:
      minutes: 5
    method: lxc

- deploy:
    timeout:
      minutes: 40
    namespace: target
    to: download
    images:
     kernel:
      url: http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190923.1/arm64/defconfig/gcc-8/Image
      type: image
     ramdisk:
      url: https://staging-storage.kernelci.org/images/rootfs/buildroot/kci-2019.02-6-gaa3933f214/arm64/baseline/rootfs.cpio.gz
     modules:
      url: http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190923.1/arm64/defconfig/gcc-8/modules.tar.xz
     dtb:
      url: http://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190923.1/arm64/defconfig/gcc-8/dtbs/amlogic/meson-g12a-sei510.dtb

- test:
    namespace: host
    timeout:
      minutes: 30
    definitions:
    - from: inline
      name: meson-g12a-sei510-images
      path: inline/meson-g12a-sei510-images.yaml
      repository:
        metadata:
          description: meson-g12a-sei510 images
          format: Lava-Test Test Definition 1.0
          name: meson-g12a-sei510-images
        run:
          steps:
          - cd /lava-lxc
          - tar xf modules.tar.xz
          - gunzip rootfs.cpio.gz
          - find lib/ | cpio -o --format=newc --append -F rootfs.cpio
          - mkbootimg --kernel Image --second meson-g12a-sei510.dtb --ramdisk rootfs.cpio --cmdline "console=ttyAML0,115200 consoleblank=0 earlycon" --kernel_offset 0x01080000 --ramdisk_offset 0x6000000 --second_offset 0x1000000 -o boot.img

- deploy:
    timeout:
      minutes: 40
    to: fastboot
    namespace: target
    images:
      boot:
        url: lxc:///boot.img

- boot:
    namespace: target
    prompts:
    - '/ #'
    timeout:
      minutes: 15
    method: fastboot
    transfer_overlay:
      download_command: wget
      unpack_command: tar -C / -xvpf


- test:
    timeout:
      minutes: 10
    definitions:
    - repository:
        metadata:
          format: Lava-Test Test Definition 1.0
          name: baseline
          description: "baseline test plan"
          os:
            - debian
          scope:
            - functional
          environment:
            - lava-test-shell
        run:
          steps:
            - >
                for level in warn err; do
                  dmesg --level=$level --notime -x -k > dmesg.$level
                done
            - >
                for level in crit alert emerg; do
                  dmesg --level=$level --notime -x -k > dmesg.$level
                  test -s dmesg.$level && res=fail || res=pass
                  count=$(cat dmesg.$level | wc -l)
                  lava-test-case $level \
                    --result $res \
                    --measurement $count \
                    --units lines
                done
            - cat dmesg.emerg dmesg.alert dmesg.crit dmesg.err dmesg.warn
      from: inline
      name: dmesg
      path: inline/dmesg.yaml

- test:
    timeout:
      minutes: 10
    definitions:
    - repository:
        metadata:
          format: Lava-Test Test Definition 1.0
          name: baseline
          description: "baseline test plan"
          os:
            - debian
          scope:
            - functional
          environment:
            - lava-test-shell
        run:
          steps:
            - export PATH=/opt/bootrr/helpers:$PATH
            - cd /opt/bootrr && sh helpers/bootrr-auto
      lava-signal: kmsg
      from: inline
      name: bootrr
      path: inline/bootrr.yaml
```

**Comment by gctucker** [comment]
@touilkhouloud @khilman The job above was submitted on staging but I can't see any result sent to the backend, so it probably failed mid-way through.  Can you please take a look?  I changed the rootfs to buildroot as it has wget and gunzip but maybe Debian is needed for other reasons.  I can give it another try with the Debian rootfs to check and then leave it up to you.

**Comment by khilman** [comment]
It's failing because the `test` actions in the baseline jinja are missing a `namespace`, which is required when using an LXC job.

**Comment by khilman** [comment]
@gctucker fix: https://github.com/gctucker/kernelci-core/pull/1

**Comment by gctucker** [comment]
Tested up to login prompt on staging:
https://staging-storage.kernelci.org/kernelci/staging.kernelci.org/staging-20190925.0/arm64/defconfig/gcc-8/lab-baylibre-dev/baseline-fastboot-meson-g12a-sei510.html

However the test cases failed to run because the LAVA test overlay failed to get applied due to networking issues.

As discussed previously, it's hard to have the overlay applied on the dispatcher since the image for fastboot is created in an lxc container.  Using nfsroot may be an option but apparently it's not supported with this fastboot.  So it seems the next step is to fix the network interface so wget can download the overlay - over to @khilman for that part.

**Comment by khilman** [comment]
@gctucker sent you a couple more patches on top of your `baseline-fastboot` branch which get things working again.

In summary
- target needs to enable networking before `wget` of overlay tarball
- we need gzip support in the busybox tar
- need to use `tar -z` when unpacking the overlay tarball.

Full log of LAVA run with all these applied: https://termbin.com/f33v

**Comment by khilman** [comment]
hmm, that termbin didn't work due to some non-printable chars in the log.  Attaching the log here.
[lava.txt](https://github.com/kernelci/kernelci-core/files/3654496/lava.txt)

**Comment by gctucker** [comment]
Thanks, sounds good.  Giving it another spin on staging.

**Comment by gctucker** [comment]
Tested OK on staging, here's the email report showing that the 5 test cases passed (login, dmesg x3, bootrr):
```
kernelci/staging.kernelci.org baseline-fastboot: 1 runs, 0 regressions (staging-20190925.2)

Test results summary
--------------------

run | platform          | arch  | lab              | compiler | defconfig | errors
----+-------------------+-------+------------------+----------+-----------+-------
1   | meson-g12a-sei510 | arm64 | lab-baylibre-dev | gcc-8    | defconfig | 0/5   


  Test:     baseline-fastboot
  Tree:     kernelci
  Branch:   staging.kernelci.org
  Describe: staging-20190925.2
  URL:      https://github.com/kernelci/linux.git
  SHA:      3b1e2136e0fd34a055cbebc975f3a55eeaad0868 
```

**Pull request merged**
