### PR TITLE
rootfs-configs.yaml: Add bullseye-v4l2 rootfs

### PR DESCRIPTION
**Pull request by Lakshmipathi**
Add bullseye-v4ltp rootfs image

Signed-off-by: Lakshmipathi Ganapathi <lakshmipathi.ganapathi@collabora.com>

### CODE REVIEW

**Comment by Lakshmipathi** [comment]
LAVA Job started: https://bot.staging.kernelci.org/job/rootfs-build-trigger/84/

**Comment by Lakshmipathi** [comment]
Above job is successful. https://storage.staging.kernelci.org/images/rootfs/debian/bullseye-v4l2/

**Comment by gctucker** [comment]
Great. Could you please resubmit a LAVA job with it just to check it's producing good results?

**Comment by Lakshmipathi** [comment]
LAVA job: https://lava.collabora.co.uk/scheduler/job/5414014

**Review by gctucker — APPROVED** [review]
Tested OK with a staging build

**Comment by gctucker** [comment]
Great, starting a production build for the bullseye-v4l2 images now.

**Pull request merged**
