### PR TITLE
runtime/lava: Generate more info on exception

### PR DESCRIPTION
**Pull request by nuclearcat**
In case we experience problem during template rendering, we often cannot identify even task caused this exception.
Add some more debug to help with that.

### CODE REVIEW

**Comment by a-wai** [comment]
@nuclearcat please fix CI issues, rebase and merge, or set `staging-skip`; PRs left open for a long time increase the chances of a conflict preventing other PRs from being deployed to staging.

**Comment by nuclearcat** [comment]
/staging is working only for website (kernelci-project) yet, i am doing to add to rest of projects gradually as well. I will run staging now and verify this patch.

**Comment by nuclearcat** [comment]
It looks fine on tests, can you fix linter warnings and we merge it?

**Comment by a-wai** [comment]
> It looks fine on tests, can you fix linter warnings and we merge it?

This PR is yours :wink:

**Comment by nuclearcat** [comment]
LOL! I am sorry

**Comment by nuclearcat** [comment]
Tested on staging

**Pull request merged**
