### PR TITLE
Revert "config/docker: upgrade debos to Bullseye"

### PR DESCRIPTION
**Pull request by alexandrasp**
This reverts commit 69cff1b4df3e6cecac4b9778c93807aedf7c7dab.

### CODE REVIEW

**Comment by gctucker** [comment]
What is this about?

**Comment by aliceinwire** [comment]
What's happen with Bullseye? Any problem to link ?

**Comment by alexandrasp** [comment]
@gctucker This is about libcamera bug, I have tried with qemu 6 from Bullseye backports and got the same error. I put a comment on issue #887, I also tried using a Debian testing, same problem. So, you have suggested to revert that commit as a workaround until we've come up with a better way of building things from source, ok? 

@aliceinwire The problem is not with Bullseye, but with the qemu package used by Bullseye, it is breaking the build for libcamera rootfs on arm64.

**Comment by gctucker** [comment]
@alexandrasp No, I was referring to the commit in libcamera that @nfraprado mentioned.

OK so we don't need to revert to Buster, closing this now.

**Pull request closed without merging**
