### PR TITLE
build-configs.yaml: add chrome-platform tree

### PR DESCRIPTION
**Pull request by eballetbo**
Add Chrome Platform's tree and the 'for-kernelci' branch.

Signed-off-by: Enric Balletbo i Serra <enric.balletbo@collabora.com>

### CODE REVIEW

**Comment by khilman** [comment]
Do we have some basic evidence that this tree is already building for all upstream defconfigs?

**Comment by eballetbo** [comment]
Yes, it is basically the rc1 tag plus the patches we're testing to queue for next merge window. Shouldn't break any build. 
We'd like to have the for-kernelci to test the patches before they really go to linux-next.

**Comment by gctucker** [comment]
I guess you might want to receive the results of the `cros-ec` tests?

If so, there needs to be a new block in the `jenkins/kernel-arch-complete.sh` script for your tree.  You can also decide who should receive build and boot reports, or for any other test plan.

**Comment by khilman** [comment]
Do we have an idea of whether this tree is already building for all the upstream defconfigs?  Often new downstream trees will produce lots of noise in failed builds.

**Comment by gctucker** [comment]
@khilman It's more of a maintainer tree than a downstream tree, see the diffstat compared to mainline:
```
$ git diff --stat v5.2-rc1..chrome-platform/for-kernelci
 Documentation/ABI/testing/debugfs-wilco-ec        |  16 +-
 Documentation/ABI/testing/sysfs-platform-wilco-ec |   9 +
 drivers/platform/chrome/Kconfig                   |  13 +
 drivers/platform/chrome/Makefile                  |   1 +
 drivers/platform/chrome/cros_ec_ishtp.c           | 763 ++++++++++++++++++++++++++++++++++++++
 drivers/platform/chrome/cros_ec_spi.c             |  68 +++-
 drivers/platform/chrome/wilco_ec/Makefile         |   2 +-
 drivers/platform/chrome/wilco_ec/core.c           |  13 +-
 drivers/platform/chrome/wilco_ec/debugfs.c        |  10 +-
 drivers/platform/chrome/wilco_ec/mailbox.c        |  21 +-
 drivers/platform/chrome/wilco_ec/properties.c     | 132 +++++++
 drivers/platform/chrome/wilco_ec/sysfs.c          |  77 ++++
 drivers/spi/spi.c                                 |  36 +-
 include/linux/platform_data/wilco-ec.h            |  92 ++++-
 include/linux/spi/spi.h                           |   2 +
 15 files changed, 1192 insertions(+), 63 deletions(-)
```

**Comment by gctucker** [comment]
Having said that, it would be easy to schedule 20~30 builds on staging from that tree to get a good idea in practice.  I can get that done on Monday.

**Comment by khilman** [comment]
Ah, ok.  With that diffstat, I have no objections to adding.

**Pull request merged**
