### PR TITLE
test-configs.yaml: Add V4L2 decoder conformance tests on rk3399-gru-kevin

### PR DESCRIPTION
**Pull request by laura-nao**
Add the V4L2 decoder conformance test plans for the AV1, H264, H265, VP8 and VP9 formats.
Run the tests only on next, mainline and media trees for now.
Enable the H264, VP8 and VP9 test plans on the `rk3399-gru-kevin` Chromebook.

### CODE REVIEW

**Comment by aliceinwire** [comment]
tested correctly
https://staging.kernelci.org/build/id/630afeed8e2ba5cda3e19daa/

**Review by aliceinwire — APPROVED** [review]

**Comment by mgalka** [comment]
@aliceinwire I can't find test plans defined by this PR in the link you provided. This PR defines a set of `v4l2-decoder-conformance-* ` tests as well as a new rootfs type. 

I don't really know how setting  `CONFIG_VIDEO_ROCKCHIP_VDEC=m` is connected to this PR.  Maybe it's a comment which was meant to be added to a different PR?

**Comment by laura-nao** [comment]
@mgalka About the `CONFIG_VIDEO_ROCKCHIP_VDEC=m` option, I added it [here](https://github.com/kernelci/kernelci-core/pull/1360/files#diff-b4c01adfba1d882e6af8a7d426dc947b374cdd6caf03dc65d3c975b134e7ebc8R232) as it's needed to enable the RkVDEC driver on `rk3399-gru-kevin`, which supports H264 and VP9. I defined a passlist [here](https://github.com/kernelci/kernelci-core/pull/1360/files#diff-9c44438cf471692cc977e583855b6955cc12e54fe6b18b04ad8fa6b942898393R2895) for the `rk3399-gru-kevin` test plans accordingly.

Please let me know if `CONFIG_VIDEO_ROCKCHIP_VDEC` is better suited to a separate PR.

**Comment by mgalka** [comment]
> @mgalka About the `CONFIG_VIDEO_ROCKCHIP_VDEC=m` option, I added it [here](https://github.com/kernelci/kernelci-core/pull/1360/files#diff-b4c01adfba1d882e6af8a7d426dc947b374cdd6caf03dc65d3c975b134e7ebc8R232) as it's needed to enable the RkVDEC driver on `rk3399-gru-kevin`, which supports H264 and VP9. I defined a passlist [here](https://github.com/kernelci/kernelci-core/pull/1360/files#diff-9c44438cf471692cc977e583855b6955cc12e54fe6b18b04ad8fa6b942898393R2895) for the `rk3399-gru-kevin` test plans accordingly.
> 
> Please let me know if `CONFIG_VIDEO_ROCKCHIP_VDEC` is better suited to a separate PR.

Sorry, I missed this one when looking into the build config. I guess it's fine to leave it in this PR.

**Comment by mgalka** [comment]
bullseye-gst-fluster rootfs image builds OK on staging:

https://bot.staging.kernelci.org/job/rootfs-builder/453/console
https://bot.staging.kernelci.org/job/rootfs-builder/454/console
https://bot.staging.kernelci.org/job/rootfs-builder/455/console

https://storage.staging.kernelci.org/images/rootfs/debian/bullseye-gst-fluster/20220831.0/

**Comment by aliceinwire** [comment]
thanks you

**Pull request merged**
