### PR TITLE
CHROMEOS test-configs-chromeos.yaml: add chromiumos-grunt

### PR DESCRIPTION
**Pull request by alexandrasp**
Enable grunt device to run cros-flash test-plan.

Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>

### CODE REVIEW

**Comment by alexandrasp** [comment]
@nuclearcat @gctucker With this changes we can but lava templates to run cros-flash at grunt, but It still missing the filters part, not sure about if it will cause any problem, so I put the `staging-skip` tag.

I already did some tests:
https://lava.collabora.dev/scheduler/job/6854818
https://lava.collabora.dev/scheduler/job/6854757

**Review by gctucker — COMMENTED** [review]
With these changes you should be able to drop the `staging-skip` label.

**Comment by alexandrasp** [comment]
PR updated, I also removed `kernel_reference` in order to add in the next PR that includes baseline test_plan.
Re-tested: https://lava.collabora.dev/scheduler/job/6863323

**Comment by alexandrasp** [comment]
wow, I will rebase my branch..

**Comment by gctucker** [comment]
I think it would be good to have this merged with the known issue around the block device number.  As `detect` isn't working, we could just set it to `mmcblk1` since it's the one that comes up the most often and keep track of an issue on the ChromeOS GitHub workboard about how to fix this properly.

Having the changes merged now will simplify rebase and checking the issue gets resolved.

**Comment by alexandrasp** [comment]
> I think it would be good to have this merged with the known issue around the block device number. As `detect` isn't working, we could just set it to `mmcblk1` since it's the one that comes up the most often and keep track of an issue on the ChromeOS GitHub workboard about how to fix this properly.
> 
> Having the changes merged now will simplify rebase and checking the issue gets resolved.

@gctucker updated to `mmcblk1`.

**Review by gctucker — APPROVED** [review]
Thanks, let's merge this now and fix issues with the block device as a follow-up.

**Pull request merged**
