### PR TITLE
Test the new 'test_template' object in the POST/send API

### PR DESCRIPTION
**Pull request by touilkhouloud**
This patch send email reports using the test_template option which gives
the possibility to choose the test template to be used in the email
report.

Signed-off-by: Khouloud Touil <ktouil@baylibre.com>

### CODE REVIEW

**Comment by gctucker** [comment]
@touilkhouloud Please don't send PRs for `staging.kernelci.org`, they need to be sent for the `master` branch.

**Comment by gctucker** [comment]
Also instead of duplicating the entry, we should be replacing it using the new API template parameter.

**Comment by touilkhouloud** [comment]
So we should remove the hard-coded part in `app/utils/report/test.py` ?

**Comment by gctucker** [comment]
Yes, that's the idea.

**Pull request closed without merging**
