### PR TITLE
LTP: Add timeout parameter

### PR DESCRIPTION
**Pull request by Lakshmipathi**
Added LTP job timeout to avoid job being stuck forever

Signed-off-by: Lakshmipathi <lakshmipathi.ganapathi@collabora.com>

### CODE REVIEW

**Comment by Lakshmipathi** [comment]
LAVA job: https://lava.collabora.co.uk/scheduler/job/2778714

**Comment by gctucker** [comment]
OK looks good.  Please check the jobs running in LAVA have the expected 15min timeout and that it's enough to let all the tests complete on all the platforms.

**Comment by Lakshmipathi** [comment]
Yes, verified that devices which run "ipc" tests need only 15 minutes to complete.

**Comment by gctucker** [comment]
Well all the kernel builds have been failing on staging for a few days and as a result no tests are being run.

**Review by gctucker — APPROVED** [review]
Tested OK on staging:
https://staging.kernelci.org/test/job/kernelci/branch/staging-mainline/kernel/staging-mainline-20201118.0/plan/ltp-ipc/

LAVA job with 15min timeout:
https://lava.collabora.co.uk/scheduler/job/2839167/definition#defline102

**Pull request merged**
